Tencent/Hippy

ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyJavaScriptExecutor.h, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/component/image/HippyImageView.m, ios/sdk/component/viewPager/HippyViewPager.m, ios/sdk/debug/websocket/HippyWebSocketExecutor.mm, ios/sdk/module/animation/HippyExtAnimationModule.m, ios/sdk/module/animation/HippyExtAnimationViewParams.m
fix(ios): sync all changes.fix some bugs
=> fix(ios): sync all changes.fix some bugs

README.md, README.zh_CN.md
As the title says, fixed typo mistakes in README.zh_CN.md and README.md including mistakes mentioned in [another pull request](https://github.com/Tencent/Hippy/pull/26).
=> fixed two typo mistakes in README.zh_CN.md and README.md

packages/hippy-react-web/src/index.ts
=> fix(web): fixed import case sensitive issue

.github/workflows/pull-request.yml
Added the testing for the newer Node LTS 12.x too: https://nodejs.org/en/about/releases/
=> Test also for NodeJS 12.x LTS

android/support_ui/build.gradle
=> chore(android): fix gradle build error

core/engine.cc, core/napi/jsc/js-native-api-jsc.cc, core/napi/v8/js-native-api-v8.h
=> fix: remove unnecessary null pointer check before delete

examples/android-demo/example/src/main/AndroidManifest.xml, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/BaseActivity.java, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/MyAPIProvider.java, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/module/TestModule.java
=> chore(demo): added TestModule

README.md, README.zh_CN.md
=> doc: update android studio link

scripts/js2cpp/build.js
=> fix: fix script bug

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/NetworkModule.java
=> fix: remove the modify of CookieManager when 'fetch' function is called

docs/guide/debug.md
=> docs: fix link typo

docs/hippy-vue/native-event.md
=> chore(doc): fix typo

docs/ios/integration.md, hippy.podspec
add hippy.podspec config file to git
=> chore(doc): add podspec config file

examples/hippy-vue-demo/src/components/demos/demo-div.vue
=> 修复dome中div在原生端无法滚动

LICENSE, packages/hippy-react-web/src/adapters/apply-layout.ts, packages/hippy-react-web/src/adapters/find-node.ts, packages/hippy-react-web/src/adapters/image-loader.ts, packages/hippy-react-web/src/adapters/unitless-numbers.ts
=> chore(license): added license to the code based on hippy-react-web

examples/hippy-vue-demo/package-lock.json, package-lock.json, packages/hippy-debug-server/package-lock.json, packages/hippy-react-web/package-lock.json, packages/hippy-react/package-lock.json, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-router/package-lock.json, packages/hippy-vue/package-lock.json
=> chore: added lock files to project

README.md, README.zh_CN.md, docs/README.md, docs/_coverpage.md
=> doc: added links

.github/workflows/pull-request.yml
=> chore(ci): make CI checking in parallelly

examples/hippy-vue-demo/src/components/demos/demo-iframe.vue
=> fix(vue-demo): fix ios vh error

ios/sdk/utils/HippyUtils.m
=> fix(ios): pass block parameter directly to dispatch_async()

ios/sdk/layout/x5LayoutUtil.m
=> fix(ios): fix main thread checker

packages/hippy-react-web/README.md
=> fix(hippy-react-web): typo fix

packages/hippy-vue/src/renderer/__tests__/view-node.test.js, packages/hippy-vue/src/renderer/view-node.js, packages/hippy-vue/src/runtime/node-ops.js
=> fix(hippy-vue): remove childNode if exist when append childNodes

packages/hippy-react/src/renderer/host-configs.ts
=> fix(react-host): complete commitTextUpdate interface

scripts/js2cpp/build.js
fix the issue https://github.com/Tencent/Hippy/issues/39#issuecomment-569850059
=> fix: `npm run build` scripts windows path error

.github/workflows/pull-request.yml, README.md, README.zh_CN.md
=> chore(ci): change to use coveralls to instead of codecov

.github/workflows/pull-request.yml, README.md, README.zh_CN.md
Add codecov for coverage report.
=> chore(ci): restore to use codecov for coverage

examples/hippy-vue-demo/src/components/demos/demo-input.vue
=> fix(vue-demo): fix compatibility error

packages/hippy-vue/src/elements/index.js, packages/hippy-vue/src/renderer/native/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/event/__tests__/dispatcher.test.js, packages/hippy-vue/src/runtime/index.js
=> feat(vue): added disableBuiltinElements options to Vue

scripts/build-example.js
=> fix(build-example.js):update cp

docs/_navbar.md, docs/_sidebar.md, docs/core/_sidebar.md, docs/core/custom.md, docs/core/introduction.md, docs/index.html
=> chore(doc): added core doc

package.json
=> chore(scripts): extracted buildcore from build command

examples/hippy-react-demo/src/externals/MyView/index.jsx
=> chore(react): fixed MyView changeColor execution issue

examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/view/MyViewController.java
=> chore(android-demo): fixed MyView changeColor can not work

examples/hippy-react-demo/README.md, examples/hippy-react-demo/package.json, examples/hippy-react-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.android.js, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-react-demo/scripts/hippy-webpack.web.js, examples/hippy-vue-demo/README.md, examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js
Make the examples be able to build without SDK building.
* Limit the aliases to local only when development mode -- removed local aliases in the production build.
* Auto check the local sdk build status and use as the alias.
**The PR is `Rebase and merge` ready, don't use `Squash and Merge`.**
=> #130 - Make aliases generation automatically.

packages/hippy-vue/src/renderer/native/style/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/style/css-selectors.js
=> fix(hippy-vue): fix css selectors TypeSelector match

ios/sdk/base/HippyFont.mm
=> fix(ios): fix issue of invalidation of customized font

ios/sdk/component/view/HippyView.h, ios/sdk/component/view/HippyView.m, ios/sdk/component/view/HippyViewManager.mm
add shadow feature for HippyView
=> feat(ios): add shadow feature for HippyView

ios/sdk/base/HippyTouchHandler.m, ios/sdk/component/scrollview/HippyScrollView.m, ios/sdk/component/scrollview/HippyScrollableProtocol.h, ios/sdk/component/videoplayer/HippyVideoPlayer.h, ios/sdk/component/view/HippyView.m, ios/sdk/component/view/UIView+Private.h
fix:
1.fix process of non-hippy view gesture
2.fix return type of [HippyScrollableProtocol scrollListener] method
3.fix some return types of properties in class HippyVideoPlayer
=> fix(ios): fix some bugs

packages/hippy-vue-native-components/src/swiper.js, packages/hippy-vue-native-components/src/ul-refresh.js, packages/hippy-vue-native-components/src/utils.js
Make the event binding for hippy-vue-native-components by dynamic.
=> refactor(hippy-vue-native-components): dynamic event binding

ios/sdk/component/textinput/HippyTextViewManager.mm
fix(ios): fix return type of TextInput.getValue method
=> fix(ios): fix return type of TextInput.getValue method

android/sdk/build.gradle, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
=> fix(android): textinput focus and blur problem

android/sdk/src/main/java/com/tencent/mtt/hippy/utils/ArgumentUtils.java
=> fix(android): compile problem

hippy.podspec
=> chore: fix podspec use_framework not found libhippy.a

packages/hippy-vue/src/renderer/view-node.js
=> fix(hippy-vue): fix wrong preSibling of childNode's nexSibling

packages/hippy-react/src/renderer/render.ts
=> fix(hippy-react): ui operation merge

packages/hippy-react/src/components/text-input.tsx
=> fix(hippy-react): text-input style

.eslintrc.js
=> chore(lint): moved no-unused-vars rule to typescript override

docs/core/custom.md
=> docs: fix docs core typo

packages/hippy-react/src/components/text.tsx
=> fix(hippy-react): text nest

examples/hippy-react-demo/src/pages/gallery.jsx, packages/hippy-react/src/dom/view-node.ts, packages/hippy-react/src/global.ts, packages/hippy-react/src/hippy.ts, packages/hippy-react/src/index.ts, packages/hippy-react/src/modules/animation-set.ts, packages/hippy-react/src/modules/animation.ts, packages/hippy-react/src/modules/back-android.ts, packages/hippy-react/src/modules/clipboard.ts, packages/hippy-react/src/modules/cookie-module.ts, packages/hippy-react/src/modules/image-loader-module.ts, packages/hippy-react/src/modules/network-info.ts, packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-react/src/native.ts, types/global.ts
Most important goal is making version determine available on runtime, and make native interface collected in default export.
=> refactor(react): make a default export for hippy-react

examples/hippy-react-demo/src/pages/gallery.jsx
For make sure the web page working correctly.
The feature will be restored after hippy-react-web implemented default export.
=> chore(example): disable default import for hippy-react-demo

ios/sdk/component/textinput/HippyTextField.m
=> fix(ios): fixed TextInput blur and focus event trigger when click

packages/hippy-react-web/src/modules/animation-set.ts
=> fix(react-web): annimation-set support opacity

layout/android/build_flexbox_so.sh
=> chore: add for mac strip

android/sdk/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
=> fix(android): input can not auto scroll when reach max length

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
=> fix(android): change style of font size invalid

docs/hippy-react/best-practices.md, docs/hippy-react/modules.md
=> chore(doc): fixed deprecated onHippyAnimation typo to onAnimation

packages/hippy-react-web/src/components/scroll-view.tsx
=> feat(react-web): support layout event

packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/native/index.js
=> Refactor batch node operations

packages/hippy-vue/src/renderer/__tests__/element-node.test.js, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/native/style/index.js, packages/hippy-vue/src/runtime/index.js, packages/hippy-vue/src/util/index.js
=> feat(hippy-vue): make beforeStyleLoad hooks applied in runtime

ios/sdk/base/HippyModuleMethod.mm
=> fix(iOS): fixed the value of _JSMethodName in HippyModuleMethod

examples/hippy-react-demo/src/components/ViewPager/index.jsx, examples/hippy-react-demo/src/modules/UIManagerModule/index.jsx, examples/hippy-react-demo/src/modules/index.js, examples/hippy-react-demo/src/pages/gallery.jsx, examples/hippy-react-demo/src/routes.js, packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-react/src/utils/node.ts, types/event.ts
1. added getElementFromFiberRef() for get the element from class ref.
2. refiend getNodeIdByRef() and callUIFunction() with getElementFromFiberRef().
3. added UIManagerModule demo.
=> refactor(hippy-react): refined the UIManagerModule

examples/hippy-react-demo/package.json, examples/hippy-react-demo/src/app.jsx, examples/hippy-react-demo/src/pages/entry.jsx, examples/hippy-react-demo/src/shared/Header.jsx, packages/hippy-react-web/src/components/image.tsx, packages/hippy-react-web/src/hippy.ts, packages/hippy-react-web/src/index.ts, packages/hippy-react-web/src/utils/index.ts, packages/hippy-react/src/utils/index.ts, scripts/react-configs.js
1. added defualt export for hippy-react-web
2. added version demo for hippy-react-web
3. fixed some typo mistake
=> feat(hippy-react-web): added default export for hippy-react web

PUBLISH.zh_CN.md
=> chore(doc): fixed mistakes in PUBLISH.zh_CN.md

android/support_ui/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
修复imageview在list中的loadmore时出现闪烁的问题 https://github.com/Tencent/Hippy/issues/120
=> fix(android): imageview will flash when list loadmore

ios/sdk/component/image/HippyImageView.m, ios/sdk/module/dev/HippyDevLoadingView.m
=> fix(iOS): fix HippyDevLoadingView height on iPhoneX

ios/sdk/component/listview/HippyBaseListView.m, ios/sdk/component/scrollview/HippyScrollView.m, ios/sdk/component/viewPager/HippyViewPager.m, ios/sdk/module/animation/HippyExtAnimationViewParams.m, ios/sdk/utils/HippyDeepCopyProtocol.h, ios/sdk/utils/NSArray+HippyArrayDeepCopy.h, ios/sdk/utils/NSArray+HippyArrayDeepCopy.m, ios/sdk/utils/NSDictionary+HippyDictionaryDeepCopy.h, ios/sdk/utils/NSDictionary+HippyDictionaryDeepCopy.m, ios/sdk/utils/NSNumber+HippyNumberDeepCopy.h, ios/sdk/utils/NSNumber+HippyNumberDeepCopy.m
=> ios bug fixes

examples/hippy-react-demo/package.json, examples/hippy-react-demo/src/components/ListView/index.jsx, packages/hippy-react-web/package-lock.json, packages/hippy-react-web/package.json, packages/hippy-react-web/src/components/list-view.tsx, packages/hippy-react-web/src/utils/validation.js, scripts/react-configs.js
=> refactor(react-web): refined the ListView component with rmc-list-view

ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): code format, add a break to match static analysis

packages/hippy-vue/src/runtime/index.js
=> fix(hippy-vue): make callback execute before $mount in $start

examples/hippy-vue-demo/src/components/demos/demo-img.vue, packages/hippy-vue/src/elements/built-in.js, packages/hippy-vue/src/renderer/native/__tests__/index.test.js
=> refactor(hippy-vue): make defualt background color of img to transparent

packages/hippy-vue-native-components/src/swiper.js
=> fix(swiper): fixed props passing

ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): fix box shadow propery

android/sdk/build.gradle
=> fix(android): revert build gradle publish config

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java
=> chore(android): removed the rude words

ios/sdk/component/footerrefresh/HippyFooterRefresh.h, ios/sdk/component/footerrefresh/HippyFooterRefresh.m, ios/sdk/component/footerrefresh/HippyFooterRefreshManager.h, ios/sdk/component/footerrefresh/HippyFooterRefreshManager.m, ios/sdk/component/headerrefresh/HippyHeaderRefresh.h, ios/sdk/component/headerrefresh/HippyHeaderRefresh.m, ios/sdk/component/headerrefresh/HippyHeaderRefreshManager.h, ios/sdk/component/headerrefresh/HippyHeaderRefreshManager.m, ios/sdk/component/refresh/HippyRefresh.h, ios/sdk/component/refresh/HippyRefresh.m
=> docs: correct copyright

android/sdk/build.gradle
=> fix(android): change hippy.jar storage path

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyInstanceContext.java, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/adapter/MyImageLoader.java
=> fix(android): memory leak suspect

android/sdk/src/main/java/com/tencent/mtt/supportui/adapters/image/IDrawableTarget.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/IShadow.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BaseDrawable.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/ContentDrawable.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/BaseLayoutManager.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/IBlockTouchListener.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/LinearLayoutManager.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerAdapter.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerViewBase.java
=> fix(android): fix support-ui code style

docs/guide/debug.md, examples/ios-demo/HippyDemo/TestModule.m, ios/sdk/base/HippyBridge.h
=> docs: add remote debug docs

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
=> fix(android): module load listener memory leak

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/ContentDrawable.java
=> fix(android): support ui fetch image and react bug fix

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
=> fix(android): revert fetch image optimize in support ui

docs/hippy-react/modules.md
=> chore(doc): fix typo in hippy-react api document

packages/hippy-react/src/events/hub.ts
For lower iOS version compatibility.
=> fix(hippy-react): removed unncessary Object.values()

ios/sdk/component/footerrefresh/HippyFooterRefresh.m, ios/sdk/component/footerrefresh/HippyFooterRefreshManager.m, ios/sdk/component/headerrefresh/HippyHeaderRefresh.m
=> fix(ios): fix footer pull method name

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix imageload failed message

examples/hippy-vue-demo/src/components/demos/demo-shadow.vue, examples/hippy-vue-demo/src/components/demos/index.js, packages/hippy-vue-css-loader/src/css-parser.js, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/util/index.js
box-shadow style is completed in iOS SDK, and android is still in working.
and and in iOS SDK, the `box-shadow-offset` style property is using { width, height } but not { x, y }  for position, still in WIP.
=> [WIP] feat(hippy-vue): box-shadow style support

android/sdk/src/main/java/com/tencent/mtt/hippy/views/refresh/RefreshWrapper.java
=> fix(android): avoid null pointer before bouncing RefreshWrapper

ios/sdk/base/HippyJSEnginesMapper.mm, ios/sdk/utils/HippyAssert.m
=> feat(ios): no exception thrown in release mode in HippyFatal method

packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-vue/src/runtime/native.js
=>  feat: add new method measureInAppWindow 

ios/sdk/module/uimanager/HippyUIManager.mm
=> [WIP] fix(ios): fix measureInWindow method,add measureInAppWindow

ios/sdk/component/view/HippyView.m, ios/sdk/module/timing/HippyTiming.mm
=> some improve

ios/sdk/component/image/HippyImageView.h
=> feat(ios): expose image method public

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/modal/HippyModalHostView.h, ios/sdk/component/modal/HippyModalHostView.m, ios/sdk/component/modal/HippyModalHostViewInteractor.h, ios/sdk/component/modal/HippyModalHostViewManager.h, ios/sdk/component/modal/HippyModalHostViewManager.mm, ios/sdk/component/modal/HippyModalTransitioningDelegate.h, ios/sdk/component/modal/HippyModalTransitioningDelegate.mm
=> feat(ios): add custom viewcontroller transition animation

ios/sdk/component/modal/HippyModalHostView.h
=> feat(ios): expose some properties and methods for Modal component

packages/hippy-react/src/modules/animation-set.ts
=> fix(hippy-react): fix hippy-react animationSet destroy problem

packages/hippy-react/src/components/list-view.tsx
Restore the https://github.com/Tencent/Hippy/commit/9de74e331b797c2137b1d0e3d08cd0dde0ee821a#diff-ccaf44058906717491bd079958ea5684a93acaa5d726e22cb34c0a6c82c79ffc
=> fix(hippy-react): restore the ListView type props be number

packages/hippy-react/src/modules/animation-set.ts, packages/hippy-vue-native-components/src/animation.js, packages/hippy-vue/src/runtime/native.js
=> fix(hippy-vue): fix hippy-vue transform multi-animation not working

PUBLISH.zh_CN.md
=> docs: change publish readme

docs/android/integration.md
=> fix(android): update install document

packages/hippy-vue-native-components/src/animation.js, packages/hippy-vue/src/util/__tests__/index.test.js, packages/hippy-vue/src/util/index.js
=> fix(hippy-vue): fixed tryConvertNumber bug & some compatible issue

CHANGELOG.md, android/sdk/build.gradle, core/napi/jsc/native-source-code-ios.cc, core/napi/v8/native-source-code-android.cc, hippy.podspec, ios/sdk/base/HippyBridge.mm, lerna.json, packages/hippy-debug-server/CHANGELOG.md, packages/hippy-debug-server/package.json, packages/hippy-react-web/CHANGELOG.md, packages/hippy-react-web/package-lock.json, packages/hippy-react-web/package.json, packages/hippy-react/CHANGELOG.md, packages/hippy-react/package-lock.json, packages/hippy-react/package.json, packages/hippy-vue-css-loader/CHANGELOG.md, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json, packages/hippy-vue-native-components/CHANGELOG.md, packages/hippy-vue-native-components/package.json, packages/hippy-vue-router/CHANGELOG.md, packages/hippy-vue-router/package-lock.json, packages/hippy-vue-router/package.json, packages/hippy-vue/CHANGELOG.md, packages/hippy-vue/package-lock.json, packages/hippy-vue/package.json
=>  chore(release): released 2.1.1

android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/thirdparty/HippyThirdPartyAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
=> improve(android): add HippyThirdPartyAdapter.onRuntimeDestroy

docs/README.md, docs/_navbar.md, docs/_sidebar.md, docs/style/appearance.md
=> chore(doc): update homepage

packages/hippy-debug-server/utils/content.js
=> fix(hippy-debug-server): fixed the way the server read from file

packages/hippy-debug-server/server/index.js, packages/hippy-debug-server/utils/content.js
=> fix(hippy-debug-server): response 404 when file not found

packages/hippy-debug-server/server/index.js, packages/hippy-debug-server/utils/mimes.js
=> feat(hippy-debug-server): modify debug server to support multiple files

packages/hippy-vue/src/runtime/native.js
=> feat(hippy-vue): added iOS12 statusBarHeight

packages/hippy-react/src/utils/index.ts, packages/hippy-vue/src/util/__tests__/index.test.js, packages/hippy-vue/src/util/index.js
=> feat(hippy-vue, hippy-react): changeTryConvertNumberCompatibility

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge+Private.h, ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix bugs due to thread competition

packages/hippy-react/src/components/pull-footer.tsx, packages/hippy-react/src/components/pull-header.tsx
add parameter in fucntions expandPullFooter,collapsePullFooter,expandPullFooter and collapsePullFooter
=> fix(hippy-react): fix pullHeader and pullFooter

docs/index.html
=> chore(doc): added gitee mirror redirect prompt to China user

README.md
=> docs:fix syntax error 'a' -> 'an'

packages/hippy-react/src/modules/ui-manager-module.ts
=> fix(hippy-react): continue finding nodeId if stringref's stateNode is a  fiberNode

packages/hippy-react/src/modules/stylesheet.ts
=> fix(hippy-react): fixed hairlineWidth NaN in ios

examples/hippy-vue-demo/scripts/hippy-webpack.dev.js
=> feat(hippy-vue-example): change dev cssloader path

examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/package.json, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js
=> feat(demo): perf demo debug experience

ios/sdk/component/listview/HippyBaseListView.h, ios/sdk/component/listview/HippyBaseListView.m
* fix(ios): fix memory leaks in HippyBaseListViewCell
=> listviewcell implementation (#1)

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix crash caused by a nil pScope

examples/hippy-vue-demo/src/components/demos/demo-shadow.vue, packages/hippy-vue-css-loader/src/css-parser.js
=> feat(hippy-vue): change boxShadowOffset standard format

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java
=> fix android box shadow problem

docs/style/appearance.md, examples/hippy-react-demo/src/components/BoxShadow/index.jsx, examples/hippy-react-demo/src/components/index.js, examples/hippy-react-demo/src/routes.js, examples/hippy-vue-demo/src/components/demos/demo-shadow.vue, packages/hippy-react/src/dom/element-node.ts, packages/hippy-react/src/utils/index.ts, packages/hippy-vue/src/util/__tests__/index.test.js, packages/hippy-vue/src/util/index.js
=> feat(hippy-react): added hippy-react boxShadow attr and demo

examples/hippy-react-demo/src/components/BoxShadow/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-shadow.vue
=> fix(hippy-react,hippy-vue): fixed boxShadow annotation

core/js/global/Network.js, examples/hippy-react-demo/src/modules/NetInfo/README.md, examples/hippy-react-demo/src/modules/NetInfo/index.jsx
=> fix(hippy-core): fixed network header default type

README.md, README.zh_CN.md
=> chore(doc): change README bootstrap process

packages/hippy-react-web/src/components/image.tsx
=> fix(hippy-react-web): fixed image onLoadEnd undefined

docs/_navbar.md, docs/guide/integration.md, docs/style/_sidebar.md
=> chore(doc): change homepage intro

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix gif play error when using gif cache data

ios/sdk/base/HippyBridge.h, ios/sdk/base/HippyBridge.mm, ios/sdk/module/dev/HippyRedBox.h, ios/sdk/module/dev/HippyRedBox.m
=> feat(ios): set a switch for red box show

packages/hippy-vue/src/renderer/native/style/css-selectors-match.js
=> fix(hippy-vue): fix css rulesets concat error

core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix exception rethrow bug

android/sdk/build.gradle
=> refactor(android): sdk gradle adjustment

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): remove an unused gesture

ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): remove check numberOfRows property

android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerViewBase.java
=> fix(android): revert RecyclerViewBase onTouchMove call

packages/hippy-react/src/components/text.tsx
=> feat(hippy-react): forward Text ref

packages/hippy-react-web/src/components/scroll-view.tsx
=> feat(hippy-react-web): added ScrollView scrollEnabled attribute

docs/hippy-react/components.md, examples/hippy-react-demo/src/components/ViewPager/index.jsx
=> chore(doc): change viewpager doc

ios/sdk/component/listview/HippyBaseListView.h, ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): fix header file include error

core/src/base/file.cc, ios/sdk/module/image loader/HippyImageCacheManager.h
=> style(ios): some styles changes

packages/hippy-react/src/components/text.tsx
=> feat(hippy-react): added Text displayName

examples/hippy-react-demo/src/components/Text/index.jsx
=> feat(hippy-react): add text-nested example

docs/README.md, docs/_sidebar.md, docs/hippy-react/introduction.md, docs/hippy-vue/introduction.md, docs/index.html
=> chore(doc): perf homepage

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix crash due to a nil pointer of JSGlobalContextRef

examples/hippy-react-demo/src/externals/TabHost/index.jsx, examples/hippy-react-demo/src/shared/PagerItemView.jsx, packages/hippy-vue/src/renderer/input-node.js
=> feat(hippy-react): added demo key

ios/sdk/component/image/HippyImageView.h, ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix image load error event

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyModuleData.mm
=> feat(ios): hippy now will send ‘destroyInstance’ event to JS

.gitignore, android/sdk/build.gradle, docs/guide/integration.md, docs/hippy-react/components.md, docs/hippy-react/modules.md, docs/hippy-vue/components.md, docs/hippy-vue/external-components.md, docs/style/layout.md
=> chore(doc): add doc info

.gitignore, android/sdk/build.gradle
=> fix(android): can not find cmake path

ios/sdk/component/image/HippyImageView.m
=> feat(ios): optimize image load error message

PUBLISH.zh_CN.md, README.md, README.zh_CN.md
=> chore(doc): updated README

ios/sdk/component/view/HippyView.m
=> fix(ios): fix error on drawing image with backgroundPositionX/Y

android/sdk/build.gradle, examples/android-demo/example/build.gradle
=> fix(android): add debug and release argument for cmake

ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): no more tracking safa area for tableview

docs/index.html
=> chore(docs): perf SEO

docs/guide/dynamic-import.md, examples/hippy-react-demo/src/externals/DyanmicImport/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-dynamicimport.vue
=> chore(doc): add dymamic load compatible info

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): block ui actions when bridge is invalide.

android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
=> refactor(android): image view default source impl

core/js/bridge/android/native2js.js, core/js/bridge/ios/native2js.js
=> refactor(hippy-core): remove react logic

android/sdk/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
=> feat(android): add navigation bar height  to global dimension

android/sdk/build.gradle
=> fix(android): add support-annotations:28.0.0

core/js/global/android/Dimensions.js, docs/hippy-react/modules.md, docs/hippy-react/native-event.md, docs/hippy-vue/native-event.md, examples/hippy-vue-demo/src/components/native-demos/demo-vue-native.vue, packages/hippy-vue/types/native.d.ts
=> feat(hippy-core): add navigatorBarHeight

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix reference cycle in block

docs/_navbar.md
=> chore(doc): add homepage blog link

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, examples/android-demo/example/build.gradle, examples/android-demo/example/src/main/AndroidManifest.xml
=> refactor(android): add package info to global platform params

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix image insets error

ios/sdk/component/listview/HippyBaseListViewCell.h, ios/sdk/component/listview/HippyBaseListViewCell.m, ios/sdk/component/listview/HippyListTableView.h, ios/sdk/component/listview/HippyListTableView.m
=> chore(ios): copyright correction

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyCoreAPI.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/custom/HippyCustomPropsController.java, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/MyAPIProvider.java, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/view/MyCustomViewController.java
=> refactor(android): support handle custom props in hippy for xxx

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
=> feat(android): night mode support

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
=> feat(android): add gaussian blur property to image

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyDeviceBaseInfo.h, ios/sdk/base/HippyDeviceBaseInfo.m, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix device orientation change event bug

android/sdk/src/main/jni/src/jni/jni_utils.cc
=> fix(core): fix debug crash

ios/sdk/component/textinput/HippyTextField.m, ios/sdk/component/textinput/HippyTextView.mm
=> fix(ios): fix text input placeholder error

ios/sdk/component/image/HippyDefaultImageProvider.h, ios/sdk/component/image/HippyDefaultImageProvider.m, ios/sdk/component/image/HippyImageView.h, ios/sdk/component/image/HippyImageView.m, ios/sdk/component/image/HippyImageViewManager.m
=> fix(ios): fix image down sample error

ios/sdk/component/image/HippyDefaultImageProvider.m
=> fix(ios): fix apng image delay time error

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/Animation.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/ContextHolder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListItemView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/modal/HippyModalHostView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/modal/RequestCloseEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/modal/ShowEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextView.java, android/sdk/src/main/res/values/themes.xml
=> refactor(android): some adjustment for modal host view

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): fix viewpager component bug

ios/sdk/base/HippyDeviceBaseInfo.m, ios/sdk/component/modal/HippyModalHostViewController.m, ios/sdk/module/dev/HippyDevLoadingView.m, ios/sdk/module/dev/HippyRedBox.m, ios/sdk/utils/HippyUtils.m
=> fix(ios): fix protential crash when AppDelegate.window called

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix view creation missing if view is created lazily

android/sdk/build.gradle
=> fix(android): support only include armeabi

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyJavaScriptExecutor.h, ios/sdk/base/executors/HippyJSCExecutor.mm
=> style(ios): cpp header files included in full path

core/src/napi/v8/js_native_api_v8.cc, core/src/napi/v8/js_native_api_value_v8.cc
=> fix(core): fix js exception report bug

examples/hippy-react-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.android.js, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-react-demo/scripts/hippy-webpack.web.js, examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js
=> fix(hippy-vue,hippy-react): added example babel plugins

examples/hippy-react-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.android.js, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js
=> fix(hippy-react,hippy-vue): add examples webpack sourcetype

scripts/build-core.js
=> fix(hippy-core): change build-core script

examples/hippy-react-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js
=> fix(hippy-vue,hippy-react): change webpack vendor script

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): fix viewpager bug

android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPager.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/viewpager/ViewPager.java
=> fix viewpager bugs

android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListViewController.java
=> feat(android): listview add props : overScrollEnabled

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
=> fix(android): fix TextNode width when do StaticLayout

ios/sdk/base/HippyBatchedBridge.mm
=> fix(ios): invoke jscexecutor.invalide on js queue

packages/hippy-vue-native-components/src/animation.js
=> fix(hippy-vue): fixed repeatCount error in animationSet

docs/hippy-react/native-event.md, docs/hippy-vue/native-event.md
=> chore(doc): add onSizeChange doc

ios/sdk/component/image/HippyImageView.m
=> fix(ios): implement backgroundSize setter for HippyImageView

ios/sdk/utils/HippyConvert+Transform.m
=> fix(ios): fix support for translateZ

docs/hippy-vue/external-components.md, examples/hippy-vue-demo/src/components/native-demos/animations/vote-down.vue, examples/hippy-vue-demo/src/components/native-demos/demo-animation.vue, packages/hippy-vue-native-components/src/animation.js, packages/hippy-vue/src/runtime/index.js
=> feat(hippy-vue): add animation event & method

core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix DLOG macro

ios/sdk/component/image/HippyImageView.m
=> fix(ios): try catch malloc exception when make image blurred

ios/sdk/base/HippyTouchHandler.m, ios/sdk/component/view/HippyViewEventProtocol.h, ios/sdk/component/view/HippyViewManager.mm, ios/sdk/component/view/UIView+Hippy.mm
=> feat(ios): add onInterceptPullUpEvent propery

examples/hippy-react-demo/README.md
=> docs: fix typo for hippy-react-demo integration script

android/sdk/src/main/jni/include/jni/jni_env.h, android/sdk/src/main/jni/include/loader/adr_loader.h, android/sdk/src/main/jni/src/jni/hippy_buffer.cc, core/include/core/napi/v8/js_native_api_v8.h, core/include/core/scope.h, core/src/base/file.cc, core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix codecc

android/sdk/build.gradle, android/sdk/gradle.properties, android/sdk/maven.gradle
=> fix(android): add d8 setting for qq

examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
=> fix(android): demo add onResume and onStop

packages/hippy-vue-native-components/src/animation.js
=> fix(hippy-vue): add child animation destroy logic

packages/hippy-react/src/dom/element-node.ts
=> refactor(hippy-react): reduce setAttribute complexity

android/sdk/src/main/jni/src/jni/com_tencent_mtt_hippy_bridge_HippyBridgeImpl.cc
=> fix(core): fix scope nullptr bug

android/sdk/src/main/jni/include/inspector/v8_inspector_client_impl.h, android/sdk/src/main/jni/src/inspector/v8_inspector_client_impl.cc
=> feat(core): adapter 89 chrome dev tools

ios/sdk/base/HippyTouchHandler.m
=> fix(ios): fix bug for touch handler

docs/guide/dynamic-import.md
=> fix(docs): fix dynamic import docs

ios/sdk/base/HippyBatchedBridge.mm
- [x ] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline.
=> bugfix(ios): fix index exceed range of array

android/sdk/src/main/jni/src/inspector/v8_inspector_client_impl.cc, android/sdk/src/main/jni/src/jni/com_tencent_mtt_hippy_bridge_HippyBridgeImpl.cc, core/src/modules/contextify_module.cc
=> fix(core): fix dynamic load crash

android/sdk/src/main/jni/src/jni/com_tencent_mtt_hippy_bridge_HippyBridgeImpl.cc
=> fix(core): fix conflict resolve error

ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/module/loader/ios_loader.cc, ios/sdk/module/loader/ios_loader.h
=> fix(ios): improve stability

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix dynamic load for local file

core/include/core/napi/jsc/js_native_api_jsc.h, core/src/napi/jsc/js_native_api_value_jsc.cc
=> fix(core): fix iOS CreateJsError function error

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/UIThreadUtils.java
=> fix(android): call onDestroy in main thread

ios/sdk/base/HippyBridge+Mtt.mm, ios/sdk/base/HippyJavaScriptExecutor.h, ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix dynamic load error

PUBLISH.zh_CN.md
=> chore(docs): change PUBLISH.md

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
=> fix(android): load module error

ios/sdk/module/exception/HippyExceptionModule.m
=> fix(ios): add synthesize for bridge in HippyExceptionModule

examples/hippy-vue-demo/src/app.vue, examples/hippy-vue-demo/src/components/demos/demo-div.vue, examples/hippy-vue-demo/src/components/demos/index.js, examples/hippy-vue-demo/src/components/native-demos/index.js, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json, packages/hippy-vue/package-lock.json, packages/hippy-vue/package.json
=> fix(hippy-vue): update y18n to safe ver

ios/sdk/component/view/HippyView.m, ios/sdk/component/view/UIView+Hippy.mm
=> feat(ios): animating view can trigger touch event

ios/sdk/component/image/HippyImageViewCustomLoader.h, ios/sdk/component/view/HippyBackgroundImageCacheManager.h, ios/sdk/component/view/HippyBackgroundImageCacheManager.m, ios/sdk/component/view/HippyView.m
=> fix(ios): fix backgroundimage update error

docs/guide/dynamic-import.md
=> chore(doc): fix dynamic http support ver

ios/sdk/module/animation/HippyExtAnimation.m
=> fix(ios): no setting CAAnimation.beginTime as far as possible

packages/hippy-vue/src/runtime/native.js
=> fix(hippy-vue): fix measureInWindowByMethod return value

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/TimingAnimation.java
=> feat(android): support color animation

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): optimizing hippy view creation

android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/font/DefaultFontScaleAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/font/HippyFontScaleAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyStyleSpan.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TypeFaceUtil.java
=> feat(android): support create font from custom file path

.eslintrc.js, examples/hippy-react-demo/src/shared/Header.jsx, examples/hippy-vue-demo/src/app.vue, packages/hippy-vue/src/renderer/native/style/parser.js
=> refactor(hippy-vue): rm redundant code

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/virtualNode/HippyVirtualNode.h, ios/sdk/component/view/HippyView+HippyViewAnimation.h, ios/sdk/component/view/HippyView+HippyViewAnimation.m, ios/sdk/component/view/HippyView.h, ios/sdk/component/view/HippyView.m, ios/sdk/component/view/UIView+HippyAnimationProtocol.h, ios/sdk/component/view/UIView+HippyAnimationProtocol.m, ios/sdk/module/animation/HippyExtAnimation.h, ios/sdk/module/animation/HippyExtAnimation.m
=> feat(ios): support background animation

ios/sdk/module/network/HippyNetWork.m, ios/sdk/utils/HippyUtils.h, ios/sdk/utils/HippyUtils.m
=> fix(ios): check response charactset

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/module/animation/CALayer+HippyAnimation.h, ios/sdk/module/animation/CALayer+HippyAnimation.m, ios/sdk/module/animation/HippyExtAnimationModule.m
=> fix(ios): fix animation pause & resume error

android/sdk/src/main/jni/src/bridge/entry.cc
=> fix(core): fix inspector crash

examples/hippy-react-demo/src/components/PullHeader/index.jsx, packages/hippy-react/src/components/list-view.tsx, packages/hippy-react/src/components/pull-header.tsx, packages/hippy-vue-native-components/src/pulls.js
=> feat(hippy-react): perf pullHeader example

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): fix scroll view error when same subview inserted

README.md, README.zh_CN.md, docs/guide/debug.md, docs/hippy-react/components.md, docs/hippy-vue/components.md, packages/hippy-react/src/components/pull-header.tsx, packages/hippy-vue-css-loader/src/index.js, packages/hippy-vue-native-components/src/animation.js, packages/hippy-vue-native-components/src/pulls.js
=> chore(docs): perf document

examples/hippy-react-demo/src/modules/Animation/index.jsx
=> fix(hippy-react): demo rm ios color anim

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix text-image mixed content layout error

core/src/napi/jsc/js_native_api_value_jsc.cc
=> fix(Core):jsc bad access

README.md, README.zh_CN.md
=> chore(docs): add `Stargazers over time` section

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): optimize process when reset scrollview's subview

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
=> fix(android): remove some unused code from HippyBridgeImpl

PUBLISH.zh_CN.md
=> docs(android): update publish document

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix resize mode center error

ios/sdk/utils/HippyConvert.mm
=> fix(ios): fix wrap-reverse layout

android/sdk/src/main/jni/src/jni/jni_register.cc
=> fix(core): fix jni dynamic register crash

ios/sdk/component/image/HippyImageView.m
=> feat(ios): sdk will send error code if image load failure

hippy.podspec
=> fix(ios): add header search path config

examples/ios-demo/HippyDemo/ViewController.m, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge+Private.h, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyRootView.mm, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyLog.h, ios/sdk/utils/HippyLog.mm
=> feat(ios): add hippy log handler

ios/sdk/base/virtualNode/HippyVirtualNode.h, ios/sdk/utils/HippyConvert.mm
=> refactor(ios): refactor codes setted misaligned by clang-format

android/sdk/src/main/jni/src/bridge/entry.cc, core/src/modules/contextify_module.cc, core/src/napi/v8/js_native_api_v8.cc, core/src/scope.cc
=> fix(core): fix log bug

.github/workflows/frontend.yml, docs/hippy-vue/customize.md
=> chore(actions): rm codecov action token

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineHost.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManager.java
=> fix(android): reset another enable buffer setting in HippyEngineManager

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyJSEnginesMapper.mm, ios/sdk/base/HippyPerformanceLogger.m, ios/sdk/base/HippyRootView.mm, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/debug/websocket/HippySRWebSocket.m, ios/sdk/module/animation/HippyExtAnimationGroup.m, ios/sdk/module/animation/HippyExtAnimationModule.m, ios/sdk/module/uimanager/HippyUIManager.mm
=> fefactor(ios): rewrite some logs

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyImageSpan.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/ImageNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
=> feat(android): image span support onLoad event

examples/hippy-react-demo/scripts/hippy-webpack.android.js, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js, examples/hippy-vue-demo/src/components/demos/demo-div.vue, examples/hippy-vue-demo/src/components/demos/demo-img.vue, packages/hippy-vue/src/elements/__tests__/built-in.test.js, packages/hippy-vue/src/elements/built-in.js, packages/hippy-vue/src/renderer/native/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/util/index.js
=> feat(hippy-vue): add local path support for placeholder & bgImg

core/js/global/TimerModule.js
=> fix(core): setTimeout and setInterval of TimerModule support ...args

ios/sdk/base/HippyBridge.mm
=> fix(ios): fix synax error

packages/hippy-react-web/package-lock.json, packages/hippy-react-web/package.json
=> chore(hippy-react-web): update ua-parser-js ver

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): fix viewpageritem frame set error

examples/hippy-react-demo/src/components/ViewPager/index.jsx, examples/hippy-react-demo/src/externals/TabHost/index.jsx, examples/hippy-react-demo/src/utils.js, packages/hippy-react/src/components/view-pager.tsx
=> fix(hippy-react-demo): perf tabhost demo

ios/sdk/module/animation/HippyExtAnimation.m
=> fix(ios): fix animation timing function type error

ios/sdk/base/virtualNode/HippyVirtualList.m
=> fix(ios): list node should set dirty when loads lazily

docs/hippy-vue/components.md
=> chore(docs): update doc

ios/sdk/debug/websocket/HippySRWebSocket.m, ios/sdk/debug/websocket/HippyWebSocketManager.m
=> fix(ios): fix websocket params error and remove assert

examples/hippy-react-demo/src/components/BoxShadow/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-shadow.vue
=> feat(hippy-react,hippy-vue): perf shadow demo

android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/image/HippyImageLoader.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/ChoreographerCompat.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/javascriptmodules/Dimensions.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/clipboard/ClipboardModule.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyCustomViewCreator.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/MatrixUtil.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ViewGroupDrawingOrderHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/UrlUtils.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/common/CommonBackgroundDrawable.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/common/CommonBorder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/IRecycleItemTypeChange.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/NodeHolder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPagerItem.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/event/HippyPageItemExposureEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/event/HippyPageScrollStateChangedEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/event/HippyPageSelectedEvent.java, android/sdk/src/main/java/com/tencent/mtt/supportui/adapters/image/IDrawableTarget.java
=> refactor(android): remove created by some one annotation

android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/compatible/Serializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/exception/DataCloneException.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/reader/SafeDirectReader.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/reader/SafeHeapReader.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/SafeDirectWriter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/SafeHeapWriter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Deserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Serializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/string/DirectStringTable.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/string/InternalizedStringTable.java
=> feat(android): add `@NonNull` annotation to serialization package method

android/sdk/src/main/jni/include/loader/adr_loader.h, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/loader/adr_loader.cc, core/include/core/base/file.h, core/include/core/base/string_view_utils.h, core/src/base/file.cc
=> fix(core): fix unicode_string_view null pointer bug

core/include/core/base/js_value_wrapper.h, core/src/base/js_value_wrapper.cc, core/src/napi/jsc/js_native_api_jsc.cc, core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix code cache bug

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): check if null pointer before setting __hippycurdir__

android/sdk/src/main/jni/include/jni/uri.h, android/sdk/src/main/jni/include/loader/adr_loader.h, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/jni/uri.cc, android/sdk/src/main/jni/src/loader/adr_loader.cc, core/include/core/base/file.h, core/include/core/base/js_value_wrapper.h, core/include/core/base/string_view_utils.h, core/include/core/modules/console_module.h, core/include/core/modules/contextify_module.h, core/include/core/modules/module_register.h, core/include/core/napi/js_native_api_types.h, core/include/core/napi/jsc/js_native_api_jsc.h, core/include/core/napi/v8/js_native_api_v8.h, core/include/core/scope.h, core/src/modules/console_module.cc, core/src/modules/contextify_module.cc, core/src/modules/timer_module.cc, core/src/napi/jsc/js_native_api_jsc.cc, core/src/napi/jsc/js_native_api_value_jsc.cc, core/src/napi/v8/js_native_api_v8.cc, core/src/scope.cc, core/third_party/base/include/base/log_level.h, core/third_party/base/include/base/unicode_string_view.h
=> fix(core): fix codecc warning

packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/index.ts, packages/hippy-react/src/modules/animation.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/native/index.js
=> fix(hippy-vue,hippy-react): add task polyfill for batch render

examples/hippy-react-demo/src/components/ListView/index.jsx
=> fix(hippy-react): fix react demo listview style

ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): hippysubviews should be removed when reuse

packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json, packages/hippy-vue/package-lock.json, packages/hippy-vue/package.json, packages/hippy-vue/src/elements/__tests__/index.test.js, packages/hippy-vue/src/elements/index.js
=> fix(hippy-vue): update package ver to safe ver

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): save scroll's contentoffset for reusing in cell

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java
=> fix(android): support horizontal scrollView offset x reuse

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/module/netinfo/HippyNetInfo.h, ios/sdk/module/netinfo/HippyNetInfo.m, ios/sdk/module/netinfo/HippyNetInfoIntenal.h, ios/sdk/module/netinfo/HippyNetInfoIntenal.m
=> feat(ios): users can get cell type from hippynetinfo module

ios/sdk/module/netinfo/HippyNetInfoIntenal.h, ios/sdk/module/netinfo/HippyNetInfoIntenal.m
=> refactor(ios): modify comment for hippynetinfointenal file

ios/sdk/component/image/HippyImageView.m
=> fix(ios): image processed by operation should set needblur yes

android/sdk/src/main/jni/src/bridge/entry.cc, core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix code cache crash

examples/ios-demo/HippyDemo/ViewController.m, ios/sdk/base/HippyBridge+Mtt.mm, ios/sdk/base/HippyBridgeDelegate.h, ios/sdk/base/HippyJavaScriptExecutor.h, ios/sdk/base/executors/HippyJSCExecutor.mm
=> feat(ios): custom properies can be set before seconary bundle loaded

core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix create ctx value crash

examples/hippy-react-demo/package.json, packages/hippy-debug-server/server/index.js, packages/hippy-react-web/package-lock.json, packages/hippy-react-web/package.json, packages/hippy-react-web/src/components/view-pager.tsx
=> feat(hippy-react-web): update swiper

android/sdk/src/main/jni/src/bridge/java2js.cc, core/src/modules/contextify_module.cc, core/src/napi/v8/js_native_api_v8.cc
=> feat(core): refactor ctx value

packages/hippy-debug-server/index.js
=> docs(hippy-debug-server): fix spelling error

ios/sdk/base/HippyJSEnginesMapper.h
=> refactor(ios): use full path header file

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): fix contentoffset property error

ios/sdk/module/animation/HippyExtAnimationModule.m
=> fix(ios): animation must be removed from view even it is not finished

.github/workflows/build_android_release_image.yml, docker/android-release/Dockerfile
=> chore(docker): add `android-release` docker image and it's build script

.github/workflows/build_android_release_image.yml
=> fix(docker): fix docker image build script error

.github/workflows/tools/v8_build.patch, .github/workflows/update_v8.yml
=> chore(android): add v8 `official-release` build script

.github/workflows/update_v8.yml
=> chore(android): change v8 `official-release` commit message

.gitignore
=> chore(android): remove prebuilt SDK aar in `android-demo`

hippy.podspec
=> chore(ios): modify hippy.podspec file

CHANGELOG.md
=> docs(changelog): change master changelog content

core/src/napi/v8/js_native_api_v8.cc
=> fix(android): fix `v8` crash caused by multiple initialize

android/sdk/build.gradle, android/sdk/gradle.properties
=> refactor(android): set default V8_RELEASE value in gradle

packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/native/index.js
=> refactor(react,vue): rm batch polyfill

hippy.podspec
=> chore(ios): add logs in podspec file

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix rtl language support

ios/sdk/base/HippyBatchedBridge.mm
=> [WIP]feat(ios): add localization infomations in deviceinfo object

ios/sdk/component/footerrefresh/HippyFooterRefresh.m, ios/sdk/component/listview/HippyBaseListView.m, ios/sdk/component/refresh/HippyRefresh.h, ios/sdk/component/refresh/HippyRefresh.m
=> fix(ios): fix hippybaselistview crash when hippyfooterfresh exists

android/sdk/src/main/jni/include/loader/adr_loader.h, android/sdk/src/main/jni/src/bridge/js2java.cc, core/include/core/base/string_view_utils.h, core/include/core/napi/v8/js_native_api_v8.h, core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix v8::maybelocal crash, remove TO_LOCAL_UNCHECKED macro

core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix v8 local string crash

README.md, README.zh_CN.md
=> chore(doc): change chinese readme

examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js
=> fix(hippy-vue): fixed vue-css-loader path option for building demo

ios/sdk/component/view/HippyView.m, ios/sdk/utils/HippyGradientObject.h
=> refactor(ios): use common calayer to replace cagradientlayer

.husky/commit-msg, .husky/post-checkout, .husky/post-commit, .husky/post-merge, .husky/pre-commit, .husky/pre-push, README.zh_CN.md, packages/hippy-react/src/components/pull-footer.tsx, packages/hippy-react/src/components/pull-header.tsx, packages/hippy-react/src/components/refresh-wrapper.tsx
=> fix(commit): fix husky commit issue

.eslintignore, packages/hippy-react/src/components/focusable.tsx
=> fix(react): fixed focusable component child displayName

commitlint.config.js
=> chore(commit): add type-enum & scope limit

android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListViewController.java
=> feat(android): support initialContentOffset props for listView

core/js/bootstrap.js, package.json
=> chore(eslint): change lint path

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/TransformUtil.java
=> fix(android): rotate animation deg value type

.gitattributes, .github/workflows/docs.yml, .github/workflows/frontend.yml, .github/workflows/ios.yml, package-lock.json, package.json
=> chore(ci): perf ci workflow

ios/sdk/base/HippyBridge+Mtt.mm, ios/sdk/base/HippyPerformanceLogger.h
=> feat(ios): add performance log enumation options

ios/sdk/base/executors/HippyJSCExecutor.mm
=> feat(ios): add try catch block for js execution

ios/sdk/component/text/HippyText.mm
=> fix(ios): fix hippytext reuse bug

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java
=> feat(android): support initialContentOffset props for ScrollView

packages/hippy-react/package-lock.json, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-router/package-lock.json, packages/hippy-vue/package-lock.json
=> refactor(react,vue): update package-lock

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): fix scrollview padding error

.gitattributes
=> refactor(core): resetLfs file

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> refactor(android): reload should call destroyBridge first

packages/hippy-react/src/dom/element-node.ts, packages/hippy-vue-css-loader/src/css-parser.js, packages/hippy-vue/src/renderer/__tests__/element-node.test.js, packages/hippy-vue/src/renderer/element-node.js
=> fix(react,vue): fix rgb format for linear-gradient parser

android/sdk/src/main/jni/include/jni/uri.h, android/sdk/src/main/jni/src/jni/uri.cc, android/sdk/src/main/jni/src/loader/adr_loader.cc
=> fix(core): fix uri crash

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/view/HippyViewGroupController.java
=> feat(android): support hpfile use in backgroundImage

ios/sdk/component/view/HippyView.m
=> refactor(ios): refactor hippyview init method

android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/java2js.cc, android/sdk/src/main/jni/src/jni/uri.cc, android/sdk/src/main/jni/src/loader/adr_loader.cc
=> fix(core): fix parse uri crash

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/NetworkModule.java
(cherry picked from commit 8f32a980f7e6d3b9b27d6dd1cf1ab4e1a3352665)
=> feat(android): fix cookie sync, no need to call removeSessionCookie

android/sdk/build.gradle, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/image/HippyDrawable.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/adapters/image/IDrawableTarget.java
=> refactor(android): should take out hippy.jar in release task

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/CSSDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/DomDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/InspectorDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/PageDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/CSSModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/DomModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/InspectEvent.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomDomainData.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/uimanager/UIManagerModule.java
=> feat(android): support ui element module for devtools

android/sdk/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java
=> fix(android): remove hasNavigationBar from DimensionsUtil

ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): fix gradient backgroundcolor update error

android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/image/HippyImageLoader.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
=> refactor(android): use ConcurrentHashMap replace SparseArray

packages/hippy-react/src/dom/element-node.ts
=> fix(react): fixed linearGradient update not work

packages/hippy-react/src/renderer/render.ts, packages/types/hippy.ts
=> feat(hippy-react): add nativeNode attributes info for debugging

PUBLISH.zh_CN.md, examples/android-demo/example/build.gradle, examples/android-demo/settings.gradle
=> docs(publish): add Android publish steps

examples/android-demo/example/build.gradle, examples/android-demo/settings.gradle
=> fix(android): fixed gradle config

ios/sdk/module/animation/HippyExtAnimationModule.h, ios/sdk/module/animation/HippyExtAnimationModule.m, ios/sdk/module/animation/HippyExtAnimationViewParams.h, ios/sdk/module/animation/HippyExtAnimationViewParams.m, ios/sdk/utils/HippyConvert+Transform.h, ios/sdk/utils/HippyConvert+Transform.m
=> fix(ios): fix degree rotation bug

ios/sdk/component/listview/HippyBaseListView.m, ios/sdk/component/listview/HippyListTableView.m
=> fix(ios): set right zPosition for listview cell

.husky/pre-commit
=> build(pre-commit): add markdownlint hook

ios/sdk/component/view/HippyView+HippyViewAnimation.h, ios/sdk/component/view/HippyView+HippyViewAnimation.m, ios/sdk/module/animation/HippyExtAnimation.h, ios/sdk/module/animation/HippyExtAnimation.m, ios/sdk/module/animation/HippyExtAnimationModule.m, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyConvert+Transform.h, ios/sdk/utils/HippyConvert+Transform.m, ios/sdk/utils/HippyConvert.h
=> fix(ios): fix combined animation error

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/PageDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomDomainData.java
=> fix(android): element refresh bug

ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/HippyView.m, ios/sdk/component/view/HippyViewManager.mm
=> feat(ios): add visibility property for view

ios/sdk/component/view/HippyView+HippyViewAnimation.h, ios/sdk/component/view/HippyView+HippyViewAnimation.m, ios/sdk/module/animation/HippyExtAnimation.h, ios/sdk/module/animation/HippyExtAnimation.m, ios/sdk/module/animation/HippyExtAnimationModule.m, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyConvert+Transform.h, ios/sdk/utils/HippyConvert+Transform.m, ios/sdk/utils/HippyConvert.h
This reverts commit 95bc07c987262069fa3da7363f21547798a9326d.
=> Revert "fix(ios): fix combined animation error (#941)"

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderEventHelper.java
=> fix(android): correct recycler list pull header height

package.json
=> chore(mdlint): change mdcheck directory

ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm
=> fix(ios): update visibility available now

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java
=> refactor(android): scroll view page scroll impl

docs/hippy-react/best-practices.md, docs/hippy-react/modules.md, docs/style/appearance.md, docs/style/layout.md, examples/hippy-react-demo/src/components/Text/index.jsx, examples/hippy-react-demo/src/modules/NativeEvent/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-dynamicimport.vue, examples/hippy-vue-demo/src/components/demos/demo-websocket.vue, examples/hippy-vue-demo/src/menu.vue
=> chore(doc): change style intro

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/uimanager/UIManagerModule.java
=> fix(android): use Number do type conversion

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java
=> fix(android): linearGradient needs >= 2 number of colors

packages/hippy-react/src/renderer/host-configs.ts
=> feat(hippy-react): add unhideInstance api in hostconfig

examples/hippy-react-demo/src/components/ListView/index.jsx, packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-react/src/renderer/host-configs.ts
=> feat(hippy-react): compatible for react 17

ios/sdk/component/listview/HippyBaseListView.h, ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): fix a bug that a wrong zposition for section view

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix a potential crash due to null pointer

packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json, packages/hippy-vue/package-lock.json, packages/hippy-vue/package.json
=> fix(hippy-vue): update ava package to safe ver

docs/index.html
=> docs(search): add search icon

core/include/core/napi/js_native_turbo.h, core/src/napi/js_native_turbo.cc
=> fix(core): jsi

package-lock.json, packages/hippy-react-web/package-lock.json, packages/hippy-react/package-lock.json, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-router/package-lock.json, packages/hippy-vue/package-lock.json
=> chore(lockfile): update npm lockfile

docs/hippy-vue/external-components.md
=> docs(hippy-vue): update swiper introduction

core/js/global/android/Turbo.js, core/js/global/ios/Turbo.js, examples/hippy-react-demo/src/externals/Turbo/demoTurbo.js, examples/hippy-vue-demo/src/components/demos/demoTurbo.js, packages/hippy-react/src/adapters/animated.ts, packages/hippy-react/src/components/text-input.tsx, packages/hippy-react/src/components/waterfall-view.tsx, packages/hippy-react/src/dom/view-node.ts, packages/hippy-react/src/modules/websocket.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-vue-css-loader/src/css-parser.js, packages/hippy-vue/src/runtime/backAndroid.js, packages/hippy-vue/src/util/__tests__/index.test.js, packages/hippy-vue/src/util/index.js, packages/hippy-vue/types/native.d.ts, scripts/mock-global.js
=> refactor(eslint): fix eslint issue

docs/index.html
=> chore(homepage): change script executing sequence

ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): fix compile-time error on Xcode 12 and previous versions

.github/workflows/commit.yml, .github/workflows/frontend.yml, commitlint.config.js, package-lock.json, package.json
=> ci(commitlint): forbid Chinese used in commit message

.github/workflows/commit.yml
=> ci(commitlint): remove commitlint push check

commitlint.config.js, docs/android/type-mapping.md
=> ci(commitlint): only use english & emoji

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): crash fixed,improve stability

ios/sdk/component/textinput/HippyTextViewManager.mm
=> fix(ios): ignore multiline property for password type textinput

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/jsi/TurboModuleManager.java, android/sdk/src/main/jni/src/jni/turbo_module_manager.cc
=> fix(core): fix jni crash

packages/hippy-react/src/renderer/host-configs.ts
=> fix(hippy-react): fixed insertBefore moveChild condition

ios/sdk/component/view/HippyShadowView.mm
=> fix(ios): fix layout nan value

commitlint.config.js, packages/hippy-react/src/components/list-view.tsx
=> fix(hippy-react): fixed getting appear event name for anonymous function

core/src/modules/console_module.cc
=> feat(core): modify console module log level

ios/sdk/component/image/HippyImageView.m
=> refactor(ios): refactor image blur ability

android/sdk/build.gradle, android/sdk/gradle.properties
=> chore(android): update build scripts and it's configs

.github/workflows/build_android_release_image.yml, docker/android-release/Dockerfile
=> chore(docker): update `android-release` docker image

android/sdk/src/main/jni/include/bridge/runtime.h, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/js2java.cc, android/sdk/src/main/jni/src/bridge/runtime.cc, android/sdk/src/main/jni/src/jni/turbo_module_manager.cc
=> fix(core): fix debug mode uncaught exception bug

ios/sdk/component/image/HippyAnimatedImageView.m
=> [WIP]fix(ios): fix animated image for iphone13 pro/max

android/sdk/src/main/jni/src/jni/turbo_module_manager.cc
=> fix(core): fix turbo runtime

core/js/entry/android/hippy.js, examples/hippy-vue-demo/src/components/demos/demo-input.vue, examples/hippy-vue-demo/src/main-native.js, packages/hippy-vue/src/renderer/__tests__/element-node.test.js, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/__tests__/index.test.js
=> fix(hippy-vue): remove vue other attributes converted to number

framework/hippy/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, modules/hippy_support/src/main/java/com/tencent/hippy/support/INativeRendererProxy.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
=> fix(android): v3.0 support debug reload

framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/include/core/engine.h, framework/js/core/include/core/napi/js_native_api.h, framework/js/core/include/core/napi/js_native_api_types.h, framework/js/core/include/core/napi/v8/js_native_api_v8.h, framework/js/core/src/engine.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc
=> feat(core): add v8 init param

docs/hippy-vue/native-event.md, packages/hippy-react/src/dom/view-node.ts, packages/hippy-react/src/hippy.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/view-node.js, packages/hippy-vue/src/runtime/index.js
=> feat(react,vue): improve managing node performance

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
(cherry picked from commit 592e9cb35fd272fc4148f3494ad6927f92f3d9d0)
=> feat(android): add v8 init param

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyOnScrollHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java
=> fix(android): scroll view onScroll event

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> fix(ios): make ios project better again

.gitignore, dom/CMakeLists.txt, dom/include/dom/dom_manager.h, dom/include/dom/layout_node.h, dom/include/dom/render_manager.h, dom/include/dom/taitank_layout_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/android/src/main/jni/CMakeLists.txt, framework/js/core/src/modules/ui_manager_module.cc
=> fix(dom): fix compilation problems

packages/hippy-react-web/src/components/image.tsx
=> fix(hippy-react-web): event.path is not supported for safari

dom/src/dom/dom_value.cc
=> feat(dom): change assert to TDF CHECK

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/iOSRenderManager.h, ios/sdk/module/uimanager/iOSRenderManager.mm
=> feat(ios): ios render manager implementation

ios/sdk/base/HippyBridge.mm, ios/sdk/component/listview/HippyBaseListView.m, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyUtils.m
=> refactor(ios): refactor hippy_debug macor usage

android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerViewBase.java
=> fix(android): remove dispatch layout in onLayout for RecyclerViewBase

core/include/core/napi/v8/js_native_api_v8.h
=> fix(core): fix lint warning

framework/js/core/include/core/napi/js_native_api_types.h, framework/js/core/include/core/napi/jsc/js_native_api_jsc.h, framework/js/core/include/core/napi/v8/js_native_api_v8.h, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc
=> feat(core): add ToDomValue and CreateCtxValue function

ios/sdk/component/text/HippyText.mm
=> fix(ios): text should not be available for view cache

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/render_manager.h, dom/include/dom/render_manager_proxy.h, dom/include/dom/taitank_layout_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/render_manager_proxy.cc
=> feat(dom): complete some domNode interfaces

android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java
=> fix(android): resolve #1104 commit crash

.github/workflows/update_v8.yml
=> chore(android): update v8 `official-release` build script

android/sdk/src/main/jni/include/jni/jni_utils.h, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/java2js.cc, android/sdk/src/main/jni/src/bridge/js2java.cc, android/sdk/src/main/jni/src/bridge/serializer.cc, android/sdk/src/main/jni/src/jni/jni_register.cc, android/sdk/src/main/jni/src/jni/jni_utils.cc
=> feat(android): add JNI numeric cast function with boundary check

dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/render_manager.h, dom/include/dom/render_manager_proxy.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/dom_value.cc, dom/src/dom/render_manager_proxy.cc, dom/src/dom/taitank_layout_node.cc
=> fix(dom): clear code warning

android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewController.java
=> refactor(android): if onScroll=true send onScroll event

commitlint.config.js, examples/hippy-react-demo/src/components/ListView/index.jsx, examples/hippy-react-demo/src/components/PullHeader/index.jsx, examples/hippy-react-demo/src/components/RefreshWrapper/index.jsx, examples/hippy-react-demo/src/components/ViewPager/index.jsx, examples/hippy-react-demo/src/shared/PagerItemView.jsx, examples/hippy-vue-demo/src/components/demos/demo-list.vue, packages/hippy-react/src/components/list-view.tsx, packages/hippy-react/src/components/view-pager.tsx, packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/renderer/index.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-react/src/utils/node.ts, packages/hippy-vue/src/elements/index.js, packages/hippy-vue/src/index.js, packages/hippy-vue/src/renderer/comment-node.js, packages/hippy-vue/src/renderer/document-node.js, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/event/dispatcher.js, packages/hippy-vue/src/renderer/native/event/emitter.js, packages/hippy-vue/src/renderer/native/event/event.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/text-node.js, packages/hippy-vue/src/renderer/view-node.js, packages/hippy-vue/src/runtime/modules/class.js, packages/hippy-vue/src/runtime/modules/style.js, packages/hippy-vue/src/runtime/node-ops.js, packages/hippy-vue/src/runtime/patch.js, packages/hippy-vue/src/util/node.js
=> feat(react,vue): perf node traversing process

dom/CMakeLists.txt, framework/js/android/src/main/jni/CMakeLists.txt, layout/CMakeLists.txt
=> feat(dom): change cmake dependence

android/sdk/src/main/jni/src/inspector/v8_channel_impl.cc, android/sdk/src/main/jni/src/inspector/v8_inspector_client_impl.cc, android/sdk/src/main/jni/src/loader/adr_loader.cc
=> feat(android): add `__unused` attribute for unused parameters and boundary checker

ios/sdk/component/image/HippyImageView.m
=> fix(ios): check current image url before display

ios/sdk/component/text/HippyShadowText.h, ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix nested text layout error (#929)

packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/utils/node.ts, packages/hippy-vue/src/renderer/native/event/dispatcher.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/runtime/node-ops.js, packages/hippy-vue/src/util/__tests__/node.test.js, packages/hippy-vue/src/util/node.js, packages/types/global.ts
=> feat(react,vue): add js node cache to improve event performance

examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js
=> build(react,vue): add SourceMapDevToolsPlugin for example

dom/include/dom/diff_utils.h, dom/src/dom/diff_utils.cc, dom/src/dom/dom_manager.cc
=> feat(dom): dom props diff

packages/hippy-react/src/utils/node.ts, packages/hippy-vue/src/util/node.js
=> fix(react,vue): fixed timeRemaining judge

packages/hippy-vue/src/renderer/native/event/__tests__/dispatcher.test.js
=> chore(unitest): add dispatcher.js unit test

dom/include/dom/dom_value.h
=> feat(dom): add function notes

dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc
add click, touch, show interface for domNode
=> feat(dom): add click,touch,show interface

android/sdk/build.gradle, android/sdk/mavencentral.gradle
=> refactor(android): publish for debug

commitlint.config.js, examples/hippy-react-demo/scripts/hippy-webpack.android.js, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js, packages/hippy-react/src/modules/stylesheet.ts, packages/hippy-vue-css-loader/src/css-parser.js
=> build(demo): change devtool to eval-cheap-module-source-map

dom/include/dom/dom_manager.h, dom/include/dom/node_props.h, dom/include/dom/render_manager.h, dom/include/dom/render_manager_proxy.h, dom/src/dom/dom_manager.cc, dom/src/dom/render_manager_proxy.cc
=> feat(dom): optimize some codes

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/layout_node.h, dom/include/dom/taitank_layout_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/layout_node.cc, framework/js/core/src/modules/ui_manager_module.cc
=> feat(dom): add modal adapter

docs/hippy-react/gesture.md, examples/hippy-react-demo/src/components/ListView/index.jsx, examples/hippy-react-demo/src/main.js, examples/hippy-react-demo/src/pages/entry.jsx, packages/hippy-react/src/dom/element-node.ts, packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/utils/index.ts
=> feat(react): support event capture phase

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, modules/hippy_support/src/main/java/com/tencent/hippy/support/INativeRendererProxy.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRendererDelegate.java
=> refactor(android): v3.0 create natvie renderer delegate with runtimeId

android/sdk/src/main/jni/CMakeLists.txt, android/sdk/src/main/jni/include/jni/convert_utils.h, android/sdk/src/main/jni/src/jni/convert_utils.cc, android/sdk/src/main/jni/src/jni/java_turbo_module.cc, core/src/napi/jsc/js_native_api_jsc.cc, core/src/napi/jsc/js_native_turbo_jsc.cc, examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/module/turbo/HippyOCTurboModule.mm
=> fix(core): remove runtime exception

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, ios/sdk/base/HippyBatchedBridge.mm
=> fix(dom): delete SetRootNode

docs/hippy-react/gesture.md, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-react-demo/src/components/ListView/index.jsx, examples/hippy-react-demo/src/components/PullHeader/index.jsx, examples/hippy-react-demo/src/shared/UIStyles/Style1.jsx, examples/hippy-react-demo/src/shared/UIStyles/Style2.jsx, examples/hippy-react-demo/src/shared/UIStyles/Style5.jsx, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/events/event.ts, packages/hippy-react/src/events/index.ts, packages/hippy-react/src/utils/node.ts
=> feat(react): add event instance

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> feat(android): add componentName to EngineContext

packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/events/event.ts, packages/hippy-react/src/renderer/host-configs.ts
=> fix(hippy-react): fixed cached fiberNode event handler problem

PUBLISH.zh_CN.md
=> docs(publish): update android sdk publish step

android/sdk/proguard-rules.pro, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyRootView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/thirdparty/HippyThirdPartyAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/CSSModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/DomModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomDomainData.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/DomNodeRecord.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
refactor(android): support save and restore dom node
refactor(android): support save and restore dom node
refactor(android): support save and restore dom node
refactor(android): keep DomNodeRecord for save dom node
=> feat(android): support save and restore dom node

dom/include/dom/dom_event.h, dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/render_manager.h, dom/include/dom/render_manager_proxy.h, dom/src/dom/dom_event.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/render_manager_proxy.cc, framework/js/core/src/modules/ui_manager_module.cc, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm
=> feat(dom): refactor dom event

dom/src/dom/dom_manager.cc
(cherry picked from commit f68d74d23992ff682bfba9e22a2db2f115ddd232)
=> fix(dom): Modify the dom event module to comply with W3C standards

dom/include/dom/render_manager_proxy.h, dom/src/dom/render_manager_proxy.cc
(cherry picked from commit d695854c8f59f957b0b0eb56b8b77c55c51ef5fb)
=> fix(dom): fix render manager proxy

dom/src/dom/dom_manager.cc
=> fix(dom): delay layout time

packages/hippy-react/src/renderer/host-configs.ts
=> fix(hippy-react): don't update node on event handler changed

dom/include/dom/dom_manager.h, dom/include/dom/render_manager.h, dom/include/dom/render_manager_proxy.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/render_manager_proxy.cc, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm
=> feat(dom): RenderManager add RemoveEventListener

ios/sdk/base/HippyRootShadowView.mm, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyDomNodeUtils.h, ios/sdk/utils/HippyDomNodeUtils.mm
=> feat(ios): non rich text display

examples/hippy-react-demo/src/components/TextInput/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-input.vue, packages/hippy-react-web/src/adapters/transfer.ts, packages/hippy-react/src/dom/element-node.ts, packages/hippy-vue-css-loader/src/css-parser.js
=> feat(react,vue): add caret color parser

packages/hippy-react/src/hippy.ts, packages/hippy-react/src/index.ts, packages/hippy-react/src/native.ts, packages/hippy-react/src/renderer/host-configs.ts
=> feat(hippy-react): compatible for react18

docs/hippy-react/gesture.md, examples/hippy-react-demo/src/components/ListView/index.jsx, packages/hippy-react/src/events/dispatcher.ts
=> feat(hippy-react): change event capture handle

framework/js/core/src/modules/ui_manager_module.cc
=> fix(dom): fix event

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyGlobalConfigs.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java, renderer/native/android/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
=> Fix/some issues from 2.0

ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): check image url length before use it

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): revert scroll animation fix for ios15

ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): fix dispatch crash

ios/sdk/component/view/HippyViewManager.mm, ios/sdk/component/viewPager/HippyViewPager.mm
=> fix(ios): cherry pick some fixes from master

dom/include/dom/deserializer.h, dom/include/dom/dom_argument.h, dom/include/dom/dom_value.h, dom/include/dom/serializer.h, dom/src/dom/deserializer.cc, dom/src/dom/dom_argument.cc, dom/src/dom/dom_value.cc, dom/src/dom/serializer.cc, framework/js/android/src/main/jni/CMakeLists.txt, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/include/core/core.h, renderer/native/android/src/main/java/com/tencent/renderer/NativeRendererDelegate.java
=> feat(dom): render manager and deserializer value

ios/sdk/utils/HippyDomNodeUtils.mm
=> fix(ios): remove deleted enum

framework/js/core/src/modules/ui_manager_module.cc
=> fix(dom): fix js delegate

renderer/native/android/src/main/jni/CMakeLists.txt, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): fix hippy render manager

dom/src/dom/taitank_layout_node.cc
=> fix(dom): refactor file and fix margin top set error

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): parser style to dom value

framework/js/android/src/main/jni/src/jni/convert_utils.cc
=> fix(core): add static cast for nullptr in tuple

framework/js/android/src/main/jni/src/bridge/entry.cc, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): refactor render_manager

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): add hippy_render_manager layout data

dom/src/dom/dom_manager.cc, framework/js/core/src/modules/ui_manager_module.cc
=> fix(core): fix event bug

framework/js/core/src/modules/ui_manager_module.cc
=> feat(core): js delegate addEventListener use capture

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc
=> fix(dom): delay add listener operation

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/debug/devtools/HippyDevManager.h, ios/sdk/debug/devtools/HippyDevManager.m, ios/sdk/debug/devtools/HippyDevWebSocketClient.h, ios/sdk/debug/devtools/HippyDevWebSocketClient.m, ios/sdk/debug/devtools/inspector/domain/HippyDomDomain.m, ios/sdk/debug/devtools/inspector/model/HippyDomModel.h, ios/sdk/debug/devtools/inspector/model/HippyDomModel.m
=> fix(ios): fix chrome elements bug and add websocket close

framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/include/core/scope.h, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java
=> feat(dom): add updateRootSize

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc
=> fix(dom): add child crash

dom/include/dom/dom_listener.h, ios/sdk/base/HippyTouchHandler.mm, ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): fix ios click error

docs/_navbar.md, docs/guide/_sidebar.md, docs/guide/exception.md, docs/hippy-react/components.md, docs/hippy-vue/components.md, docs/hippy-vue/external-components.md, packages/hippy-react/src/components/image.tsx, packages/hippy-react/src/components/text-input.tsx, packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/events/emitter-revoker.ts, packages/hippy-react/src/events/emitter.ts, packages/hippy-react/src/global.ts, packages/hippy-react/src/index.ts, packages/hippy-react/src/modules/network-info.ts, packages/hippy-react/src/modules/websocket.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/utils/node.ts, packages/types/global.ts
=> chore(doc,ts): change some docs introduction and ts syntax

dom/src/dom/taitank_layout_node.cc
=> fix(dom): fix layout padding margin error

framework/js/android/src/main/jni/src/bridge/entry.cc, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): hippy render manager update layout and end batch

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/jni/src/bridge/entry.cc, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/renderer/INativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/INativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderContext.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderException.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRendererManager.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Deserializer.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Serializer.java
refactor(android): improve and perfect native renderer part I
=> refactor(android): improve and perfect native renderer

ios/sdk/base/HippyRootShadowView.mm, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.mm
=> fix(ios): show secondary page

dom/include/dom/layout_node.h, dom/include/dom/taitank_layout_node.h, dom/src/dom/taitank_layout_node.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, layout/engine/HPNode.cpp, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): support layout density

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineHost.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/ContextHolder.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/PixelUtil.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java
=> refactor(android): improve and perfect native renderer II

dom/src/dom/diff_utils.cc
=> fix(dom): diff add undefined type

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): fix event binding and callback function

android/sdk/src/main/jni/CMakeLists.txt
=> fix(android): fix library symbol visibility settings

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc
=> fix(dom): change rendermanager to weakptr

framework/js/core/src/modules/ui_manager_module.cc, framework/js/core/third_party/base/src/base/log_settings.cc
=> fix(core): fix unused warning

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> refactor(ios): change render_manager_proxy name

dom/include/dom/dom_node.h, dom/src/dom/dom_manager.cc
=> fix(dom): update and delete node use old date

packages/hippy-react/src/dom/element-node.ts, packages/hippy-react/src/events/dispatcher.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-react/src/utils/node.ts, packages/hippy-vue/src/renderer/native/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/index.js, packages/types/hippy.ts
=> refactor(react,vue): add ui event binding attribute

.github/workflows/tools/v8_build.patch, .github/workflows/update_v8.yml
=> chore(android): remove clang++ unknown argument `-ffile-compilation-dir`

ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/refreshview/HippyRefreshWrapper.mm, ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.h, ios/sdk/component/waterfalllist/HippyWaterfallView.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyDomNodeUtils.h, ios/sdk/utils/HippyDomNodeUtils.mm
=> fix(ios): make waterfall executable

.github/workflows/tools/v8_build.patch, .github/workflows/update_v8.yml
=> chore(android): sync the android NDK API level to the V8 build config

ios/sdk/base/HippyTouchHandler.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix press event callback

ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.mm
=> fix(ios): make list show full contents

ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix clipboard module error

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/textinput/HippyShadowTextView.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): text layout measure function modify

android/sdk/gradle.properties, core/third_party/base/include/base/logging.h
=> chore(android): update Android NDK version to r23b(23.1.7779620)

ios/sdk/base/HippyBridge.mm
=> fix(ios): fix gain moduleName error for jsi

.github/workflows/tools/v8_build.patch, .github/workflows/update_v8.yml
=> chore(android): modify the `V8` build script to adapt NDK(r23b)

ios/sdk/base/HippyTouchHandler.mm
=> fix(ios): fix touch bug

dom/include/dom/dom_argument.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/layer_optimized_render_manager.h, dom/include/dom/render_manager.h, dom/src/dom/dom_argument.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/layer_optimized_render_manager.cc, framework/js/core/include/core/napi/js_native_api_types.h, framework/js/core/include/core/napi/jsc/js_native_api_jsc.h, framework/js/core/include/core/napi/v8/js_native_api_v8.h, framework/js/core/src/modules/ui_manager_module.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): modify call function use dom_argument as argument

dom/include/dom/dom_listener.h, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge+Private.h, ios/sdk/base/HippyComponentData.mm, ios/sdk/base/HippyModuleData.h, ios/sdk/base/HippyModuleData.mm, ios/sdk/base/HippyModuleMethod.mm, ios/sdk/component/view/HippyViewManager.h, ios/sdk/component/view/HippyViewManager.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm, ios/sdk/utils/OCTypeToDomArgument.h, ios/sdk/utils/OCTypeToDomArgument.mm
=> fix(ios): fix ui callback bug

framework/js/core/src/modules/ui_manager_module.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc
=> fix(core): fix call function bug

dom/src/dom/taitank_layout_node.cc
=> fix(dom): layout check input number

android/sdk/src/main/jni/include/inspector/v8_inspector_client_impl.h
=> feat(android): remove unused formatAccessorsAsProperties()

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix text dirty bug

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix touch event key name

.gitignore
=> feat(android): modify git ignore

framework/js/packages/hippy-react/src/dom/element-node.ts, framework/js/packages/hippy-react/src/renderer/render.ts
=> feat(hippy-react): add bind_event boolean value

modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/ArgumentUtils.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/PixelUtil.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/HippyImageSpan.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/HippyNativeGestureSpan.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextView.java, renderer/native/android/src/main/java/com/tencent/renderer/INativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/INativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/INativeRenderExceptionHandler.java, renderer/native/android/src/main/java/com/tencent/renderer/IUITaskExecutor.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderException.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRendererManager.java, renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/ImageVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextComponent.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNodeManager.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Deserializer.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Serializer.java
refactor(android): v3.0 improve and perfect native renderer series
refactor(android): v3.0 improve and perfect native renderer series
refactor(android): v3.0 improve and perfect native renderer series
refactor(android): v3.0 improve and perfect native renderer series
refactor(android): v3.0 improve and perfect native renderer series
=> refactor(android): v3.0 improve and perfect native renderer series

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix view hierarchy bugs

renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): measure text

ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): fix nodes deletion action

ios/sdk/component/modal/HippyModalHostViewManager.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm
=> fix(ios): fix shadowview set layout frame bug

ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix function params type error

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix animation params parse error

.eslintignore, examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.android.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios.js, packages/hippy-vue/src/renderer/native/style/css-selectors-match.js, scripts/build-debug-server.js
=> fix(build script): fix debug-server build script

packages/hippy-react/src/renderer/host-configs.ts
=> refactor(hippy-react): change commitMutationEffects name

examples/hippy-react-demo/package.json, packages/hippy-debug-server/README.md, packages/hippy-react/package-lock.json
=> refactor(hippy-react): update hippy-react dependencies

examples/hippy-react-demo/package.json, examples/hippy-vue-demo/package.json
=> build(example): add hippy:dev backup script

framework/js/core/src/base/task_runner.cc, framework/js/core/src/engine.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc, framework/js/core/src/task/worker_task_runner.cc
=> feat(core): move DetachThread

dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/core/src/modules/ui_manager_module.cc, ios/sdk/base/HippyComponent.h, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): add ui task listener for set native props bug

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/macro.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/src/modules/ui_manager_module.cc, ios/sdk/base/HippyBatchedBridge.mm
#	dom/include/dom/dom_manager.h
#	framework/js/core/src/modules/ui_manager_module.cc
=> fix(dom): put dom operation to dom task runner;

dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/macro.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/include/core/scope.h, framework/js/core/src/base/task_runner.cc, framework/js/core/src/modules/ui_manager_module.cc, framework/js/core/src/scope.cc, framework/js/core/src/task/worker_task_runner.cc, ios/sdk/module/uimanager/HippyUIManager.mm
=> feat(dom): change DomValue to DomArgument

dom/include/dom/dom_listener.h, ios/sdk/base/HippyComponent.h, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): remove add ui task event

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): get node from dom manager

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): implement event listeners

README.md, README.zh_CN.md, examples/hippy-react-demo/package.json, examples/hippy-vue-demo/package.json, package-lock.json, package.json
=> chore(demo&readme): update demo & readme

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/macro.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/src/modules/ui_manager_module.cc, ios/sdk/base/HippyBatchedBridge.mm
=> fix(dom): delete domManager js runner;

core/include/core/base/string_view_utils.h, core/third_party/base/include/base/logging.h
=> fix(core): fix convert crash

.gitignore
=> chore(gitignore): add some directory to git ignore

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h
=> fix(ios): fix rich text layout error

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): fix hippy render manager complier error

packages/hippy-debug-server/README.md, packages/hippy-debug-server/hippy-debug.js, packages/hippy-debug-server/hippy-dev.js, packages/hippy-debug-server/index.js, packages/hippy-debug-server/package.json, packages/hippy-debug-server/server/webpack.js
=> feat(debug-server): add cli API

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> fix(ios): add turbo demo

packages/hippy-debug-server/server/webpack.js, packages/hippy-debug-server/webpack-dev-server/lib/Server.js
=> fix(debug-server): webpack dev callback

examples/hippy-react-demo/package.json, examples/hippy-vue-demo/package.json
=> fix(react-demo,vue-demo): local-debug script

packages/hippy-debug-server/webpack-dev-server/lib/Server.js
=> fix(debug-server): fix webpack-dev-server compile callback

framework/js/core/include/core/napi/js_native_api_types.h, framework/js/core/include/core/napi/jsc/js_native_api_jsc.h, framework/js/core/include/core/napi/v8/js_native_api_v8.h, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc
=> feat(core): add DeleteProperty func

renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): fix measure text

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): modify width and height unit size

dom/src/dom/dom_argument.cc
=> fix(dom): fix dom argument to object crash

layout/engine/HPNode.cpp
=> fix(layout): fix fractional width compute

ios/sdk/base/HippyComponentData.h, ios/sdk/base/HippyComponentData.mm, ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix render event handler bug

ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): implement startbatch function

examples/hippy-react-demo/.npmrc, examples/hippy-vue-demo/.npmrc
=> chore(example): add npm ignore

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix nil object to domargument error

docs/guide/debug.md
=> docs(debug): add iOS elements debug introduction

dom/include/dom/layer_optimized_render_manager.h, dom/include/dom/render_manager.h, dom/src/dom/dom_manager.cc, dom/src/dom/layer_optimized_render_manager.cc, framework/js/core/src/modules/ui_manager_module.cc, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): implement BeginBatch and EndBatch

renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNodeManager.java
=> fix(android):  v3.0 correct update layout int to float

dom/include/dom/deserializer.h, dom/src/dom/deserializer.cc
=> fix(dom): fix dom argument deserializer error

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderContext.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderException.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextLineHeightSpan.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNodeManager.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Deserializer.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Serializer.java
refactor(android): v3.0 add update node and delete node
=> refactor(android): v3.0 add update node and delete node

android/sdk/proguard-rules.pro, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
1. add two properties for TextNode
2. allow override createLayout method
=> feat(android): add two properties for TextNode

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java
add two properties for TextVirtualNode
=> feat(android): add two properties for TextVirtualNode

docs/_navbar.md, docs/android/_sidebar.md, docs/android/dom-cache.md
=> docs(dom-cache): add dom cache introduction

android/sdk/src/main/java/com/tencent/mtt/hippy/utils/ContextHolder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/PixelUtil.java
fix(android): add setMetrics to PixelUtil
=> fix(android): add setMetrics to PixelUtil

dom/include/dom/dom_node.h, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge.h, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyRootView.h, ios/sdk/base/HippyRootView.mm, ios/sdk/module/dev/HippyDevLoadingView.m, ios/sdk/utils/HippyDomNodeUtils.h, ios/sdk/utils/HippyDomNodeUtils.mm
=> feat(ios): add interface and demo to third party

ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> refactor(ios): refactor event handler

framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> refactor(ios): refactor third party ui interface demo

framework/js/examples/ios-demo/HippyDemo/ViewController.mm
=> refactor(ios): add comment

ios/sdk/component/view/UIView+Hippy.h, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> feat(ios): view can decide that if event can be prevented

dom/src/dom/taitank_layout_node.cc
=> fix(dom): support space evenly

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/layer_optimized_render_manager.cc, framework/js/android/src/main/jni/include/jni/native_render_provider.h, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): refactor dom event related codes

examples/hippy-react-demo/src/externals/DyanmicImport/index.jsx, examples/hippy-vue-demo/package.json, examples/hippy-vue-demo/src/components/demos/demo-dynamicimport.vue
=> chore(example): change dynamic http path

framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/netinfo/NetInfoModule.java
问题：
NetInfoModule#unregisterReceiver是通过handler#post触发的，此时HippyGlobalConfigs#destroyIfNeed可能已经调用，导致mContext.getGlobalConfigs().getContext()为空，mConnectivityReceiver解注册失败。从而产生内存泄漏
修改方案：
由于调用时序的问题不太好处理，这里采用了保守做法。在注册mConnectivityReceiver时，使mConnectivityReceiver持有context的强引用，确保一定可以注销监听
=> fix(android): fix memory leak

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, examples/ios-demo/HippyDemo/DemoConfigs.h, examples/ios-demo/HippyDemo/ViewController.m, ios/sdk/base/HippyRootView.mm
=> feat(ios): jsi switch

ios/sdk/debug/devtools/inspector/domain/HippyDomDomain.m, ios/sdk/debug/devtools/inspector/model/HippyCSSModel.m, ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.h, ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.m, ios/sdk/debug/devtools/inspector/model/HippyDomModel.h, ios/sdk/debug/devtools/inspector/model/HippyDomModel.m
=> fix(ios): fix chrome elements debug DOM protocol and display color

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): fix error logic in HippyRenderManager::HandleListenerOps()

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/debug/devtools/HippyDevManager.h, ios/sdk/debug/devtools/HippyDevManager.mm, ios/sdk/debug/devtools/HippyDevWebSocketClient.h, ios/sdk/debug/devtools/HippyDevWebSocketClient.m, ios/sdk/debug/devtools/inspector/domain/HippyDomDomain.mm, ios/sdk/debug/devtools/inspector/model/HippyCSSModel.mm, ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.h, ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.m, ios/sdk/debug/devtools/inspector/model/HippyDomModel.h, ios/sdk/debug/devtools/inspector/model/HippyDomModel.mm
=> elements bug 修复更新到 3.0 dev分支

ios/sdk/component/listview/HippyBaseListView.mm
=> fix(ios): fix crash when list children nodes size is zero

dom/src/dom/taitank_layout_node.cc, dom/src/dom/yoga_layout_node.cc
=> feat(dom): refactor layout node

dom/src/dom/taitank_layout_node.cc
=> fix(dom): fix complier error

android/sdk/gradle.properties, core/src/modules/contextify_module.cc
(cherry picked from commit 5060c9d7366768a17e4be844acfc7970c18d1552)
=> fix(core): fix LoadUntrustedContent crash

framework/js/android/gradle.properties, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, modules/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/NativeRenderProxy.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/RenderProxy.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderContext.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
=> refactor(android): v3.0 link createDomInstance jni

packages/global.d.ts, packages/hippy-react/src/color/index.ts, packages/hippy-react/src/modules/animation-set.ts, packages/hippy-react/src/modules/animation.ts, packages/hippy-react/src/modules/back-android.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/native/index.js
=> feat(react,vue): perf startBatch

.eslintrc.js, packages/hippy-react-web/src/components/image.tsx, packages/hippy-react-web/src/components/list-view.tsx, packages/hippy-react-web/src/components/navigator.tsx, packages/hippy-react-web/src/components/scroll-view.tsx, packages/hippy-react-web/src/components/text.tsx, packages/hippy-react-web/src/components/view-pager.tsx, packages/hippy-react-web/src/components/view.tsx, packages/hippy-react-web/src/hippy.ts, packages/hippy-react-web/src/modules/animation-set.ts, packages/hippy-react-web/src/modules/animation.ts, packages/hippy-react/src/adapters/animated.ts, packages/hippy-react/src/components/focusable.tsx, packages/hippy-react/src/components/image.tsx, packages/hippy-react/src/components/list-view.tsx, packages/hippy-react/src/components/modal.tsx, packages/hippy-react/src/components/navigator.tsx, packages/hippy-react/src/components/pull-footer.tsx, packages/hippy-react/src/components/pull-header.tsx, packages/hippy-react/src/components/refresh-wrapper.tsx, packages/hippy-react/src/components/text-input.tsx, packages/hippy-react/src/event/event.ts, packages/hippy-react/src/event/listener.ts
=> refactor(hippy-react): fix ts member-accessibility

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/include/bridge/runtime.h, framework/js/android/src/main/jni/include/jni/native_render_provider.h, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, framework/js/core/include/core/scope.h, framework/js/core/src/modules/ui_manager_module.cc, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): refactor init hippy instance

android/sdk/build.gradle, android/sdk/src/main/jni/CMakeLists.txt, android/sdk/src/main/jni/minimum_exports.lst, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/jni/java_turbo_module.cc, core/include/core/base/string_view_utils.h, core/include/core/napi/js_native_api_types.h, core/include/core/napi/v8/js_native_turbo_v8.h, core/include/core/task/common_task.h, core/src/modules/contextify_module.cc, core/src/napi/callback_info.cc, core/src/napi/v8/js_native_api_v8.cc
=> chore(android): optimize build scripts

framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): delete render manager

android/sdk/src/main/jni/src/bridge/js2java.cc
(cherry picked from commit bf089f0e285d22cfa426dce7d9d16726003a23c1)
=> fix(core): fix TDF_BASE_DCHECK crash

.github/workflows/docs.yml, .github/workflows/frontend.yml, .github/workflows/ios.yml
=> ci(workflows): remove push action check

.github/workflows/commit.yml, .github/workflows/frontend.yml, package-lock.json, package.json, packages/hippy-debug-server/utils/exec.js, scripts/build-debug-server.js, scripts/build.js
=> chore(dependency): update marked npm package to safe version

scripts/react-configs.js, scripts/vue-configs.js
=> build(log): remove circular warnings

dom/src/dom/taitank_layout_node.cc
=> fix(dom): fix layout node parser error

hippy.podspec
=> chore(ios): remove hippy_use_frameworks check

framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/base/HippyBridge+LocalFileSource.h, ios/sdk/base/HippyBridge+LocalFileSource.m, ios/sdk/base/HippyBridge+Mtt.mm, ios/sdk/base/executors/HippyJSCExecutor.mm, ios/sdk/component/image/HippyImageView.m
=> feat(ios): add sand box directory property for bridge

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/base/HippyBridge.mm, ios/sdk/base/UIView+RootViewRegister.h, ios/sdk/base/UIView+RootViewRegister.mm
=> feat(ios): support register custom view as root view

framework/js/examples/ios-demo/HippyDemo/ViewController.mm
=> refactor(ios): alternate ios demo

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/HippyBridge+LocalFileSource.mm
=> fix(ios): fix sandbox directory set error

framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h
=> feat(dom): modify event-related logic

examples/hippy-vue-demo/src/components/demos/demo-remote-bundle.vue, framework/js/examples/hippy-vue-demo/src/components/demos/index.js, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/js/examples/ios-demo/HippyDemo/TestModule.m, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge.h, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyBundleURLProvider.h, ios/sdk/base/HippyBundleURLProvider.m, ios/sdk/base/HippyInvalidating.h, ios/sdk/base/HippyRootView.mm, ios/sdk/debug/devtools/HippyDevInfo.h, ios/sdk/debug/devtools/HippyDevInfo.m, ios/sdk/debug/devtools/HippyDevManager.h, ios/sdk/debug/devtools/HippyDevManager.mm, ios/sdk/debug/devtools/HippyDevWebSocketClient.h, ios/sdk/debug/devtools/HippyDevWebSocketClient.m
* feat(ios): websocket close with code and reason
* feat(hippy-vue-demo): add remote bundle entry
* feat(vue-demo): add TestModule.remoteDebug API
* feat(ios): websocket url add hash
* feat(ios): TestModule add remoteDebug
Co-authored-by: chestershen <chestershen@tencent.com>
=> feat(ios): websocket url add hash and close with code and reason 

.gitignore
=> chore(gitignore): remove wrong assets tracking

dom/include/dom/dom_node.h, dom/include/dom/layer_optimized_render_manager.h, dom/include/dom/render_manager.h, dom/src/dom/dom_node.cc, dom/src/dom/layer_optimized_render_manager.cc, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, ios/sdk/module/uimanager/NativeRenderManager.h, ios/sdk/module/uimanager/NativeRenderManager.mm, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(dom): fix CallFunction bug

android/sdk/src/main/jni/src/bridge/entry.cc
=> feat(android): replace unsafe JNI numeric cast

framework/js/android/src/main/jni/include/jni/native_render_provider.h, framework/js/android/src/main/jni/src/jni/native_render_provider.cc, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): callUIFunction takes an extra callback_id

framework/js/android/src/main/jni/CMakeLists.txt, framework/js/android/src/main/jni/include/bridge/bridge.h, framework/js/android/src/main/jni/src/bridge/bridge.cc, framework/js/core/include/core/runtime/v8/bridge.h
=> fix(core): fix inspector bug

dom/include/dom/layout_node.h, dom/include/dom/taitank_layout_node.h, dom/src/dom/taitank_layout_node.cc, ios/sdk/component/text/HippyShadowText.h, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/textinput/HippyShadowTextView.mm, layout/engine/HPNode.cpp, layout/engine/HPNode.h, layout/engine/Hippy.cpp, layout/engine/Hippy.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): refactor layout measure function

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderNode.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListAdapter.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListItemView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewEventHelper.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/UIPromise.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextGestureSpan.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNodeManager.java
=> refactor(android): v3.0 call back id

dom/src/dom/serializer.cc
=> fix(dom): fix serializer two byte string

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): update render manager with full props

ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBundleURLProvider.h, ios/sdk/base/HippyBundleURLProvider.m, ios/sdk/debug/devtools/HippyDevInfo.h, ios/sdk/debug/devtools/HippyDevInfo.m, ios/sdk/debug/devtools/HippyDevWebSocketClient.m, ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.m
* feat(ios): parse websocket url from bundle url
* feat(ios): HippyBundleURLProvider add websocket url
* feat(ios): modify ws url structure
* feat(ios): modify HippyDevInfo file header copyright
* feat(ios): modify HippyCSSPropsDefine file header copyright
Co-authored-by: luomy <ozonelmy@163.com>
=> feat(ios): parse websocket url from bundle url (#1474)

dom/include/dom/layout_node.h, dom/include/dom/taitank_layout_node.h, dom/include/dom/yoga_layout_node.h, dom/src/dom/taitank_layout_node.cc, dom/src/dom/yoga_layout_node.cc
=> feat(dom): refactor layout interface

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/NativeRenderManager.mm, third_party/yoga/lib/ios/libyoga.a
=> feat(ios): support yoga layout

.eslintignore, .eslintrc.js, packages/global.d.ts, packages/hippy-react-web/src/components/image.tsx, packages/hippy-react/src/adapters/animated.ts, packages/hippy-react/src/components/focusable.tsx, packages/hippy-react/src/components/image.tsx, packages/hippy-react/src/components/list-view.tsx, packages/hippy-react/src/components/navigator.tsx, packages/hippy-react/src/global.ts, packages/hippy-react/src/modules/animation.ts, packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-react/src/types/index.ts, packages/hippy-react/src/utils/node.ts
=> refactor(ts): fixed some ts issues

dom/src/dom/serializer.cc, test/.clang-format, test/CMakeLists.txt, test/dom/dom_value_ut.cc, test/main.cc
=> feat(dom): gtest for dom value

docs/hippy-react/modules.md, docs/hippy-vue/external-components.md, examples/hippy-vue-demo/src/components/native-demos/animations/color-change.vue, examples/hippy-vue-demo/src/components/native-demos/animations/cubic-bezier.vue, examples/hippy-vue-demo/src/components/native-demos/animations/loop.vue, examples/hippy-vue-demo/src/components/native-demos/animations/vote-down.vue, packages/hippy-vue-native-components/src/animation.js
=> feat(hippy-vue): support  value for anim repeactCount

dom/include/dom/node_props.h, dom/include/dom/yoga_layout_node.h, dom/src/dom/serializer.cc, dom/src/dom/yoga_layout_node.cc
=> feat(dom): fix yoga layout position

ios/sdk/component/scrollview/HippyScrollView.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.h
=> refactor(ios): refactor hippyuimanager ,remove unused code

ios/sdk/debug/devtools/HippyDevWebSocketClient.m
=> feat(ios): modify websocket url symbol

dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc
=> fix(dom): add getGlobalLayoutInfo method

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/RenderProcessInterceptor.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/Animation.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationNode.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/LinkHelper.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/NativeRenderProxy.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/TransformUtil.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Deserializer.java
refactor(android): v3.0 animation
refactor(android): v3.0 animation
=> refactor(android): v3.0 animation

packages/hippy-react/src/modules/network-info.ts
=> fix(hippy-react): fixed network-info wrong stored listener

.github/CONTRIBUTING.md, README.md, README.zh_CN.md
=> chore(pr): add pr step instroduction

.github/CONTRIBUTING.md
=> chore(pr): change guideline index
