dom/src/dom/deserializer.cc, dom/src/dom/yoga_layout_node.cc, test/CMakeLists.txt, test/dom/deserializer_ut.cc, test/dom/dom_value_ut.cc, test/dom/serializer_ut.cc
=> feat(dom): add unit test

dom/src/dom/deserializer.cc, test/dom/deserializer_ut.cc
=> fix(dom): fix deserialzier read object error

dom/include/dom/diff_utils.h, dom/include/dom/dom_node.h, dom/src/dom/diff_utils.cc, dom/src/dom/dom_manager.cc
=> fix(dom): add delete props when diff node

ios/sdk/component/text/HippyShadowText.mm
=> feat(ios): set default font size to 14

examples/hippy-react-demo/src/externals/Turbo/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-turbo.vue
=> fix(web): fix turbo demo bugs

dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc
=> feat(dom): update dom_node style

core/include/core/napi/jsc/js_native_api_jsc.h, core/src/scope.cc
=> fix(core): fix macro bug

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/HippyComponent.h, ios/sdk/base/HippyRootShadowView.h, ios/sdk/base/HippyRootShadowView.mm, ios/sdk/component/listview/HippyBaseListItemShadowView.h, ios/sdk/component/listview/HippyBaseListItemShadowView.mm, ios/sdk/component/listview/HippyBaseListItemView.mm, ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/refreshview/HippyRefreshWrapper.mm, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/UIView+Hippy.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): some bugs fix

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
Use Context#getApplicationContext to create DefaultSharedPreferencesAdapter
=> fix(android): fix context leaks on EngineInitParams

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=>  feat(dom): adjust the parameter format of callUIFunction

ios/sdk/component/image/HippyImageView.m, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/textinput/HippyShadowTextView.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/debug/devtools/inspector/model/HippyCSSModel.mm, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> [WIP]fix(ios): fix node data race and shadow views dont hold dom node

ios/sdk/base/HippyBundleURLProvider.m, ios/sdk/debug/devtools/HippyDevInfo.m
=> feat(ios): devtools modify debugURL key

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/module/uimanager/NativeRenderManager.mm
=> fix(ios): fix memory leaks

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevRemoteServerData.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/DomDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/CSSModel.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/DomModel.java
support dom pushNodeByPathToFrontend
support dom pushNodesByBackendIdsToFrontend
support css color in rgba
=> fix(android): support elements color/findNode by path

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderContext.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderException.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/ImageVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextImageSpan.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNodeManager.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Deserializer.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Serializer.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/EventUtils.java
refactor(android): v3.0 nest text
refactor(android): v3.0 nest text
=> refactor(android): v3.0 nest text

android/sdk/src/main/jni/CMakeLists.txt
=> feat(android): cmake script adds `V8` library file format check

ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): fix view pager item index error

ios/sdk/utils/HippyLog.mm
=> refactor(ios): ignore debug log in release mode

android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/jni/java_turbo_module.cc, core/include/core/napi/js_native_api_types.h, core/include/core/napi/jsc/js_native_api_jsc.h, core/include/core/napi/v8/js_native_api_v8.h, core/src/modules/contextify_module.cc, core/src/napi/jsc/js_native_api_value_jsc.cc, core/src/napi/v8/js_native_api_v8.cc, examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/executors/HippyJSCExecutor.mm
Please enter the commit message for your changes. Lines starting
=> fix(core): fix ThrowExceptionToJs

android/sdk/src/main/jni/include/jni/convert_utils.h, android/sdk/src/main/jni/include/jni/java_turbo_module.h, android/sdk/src/main/jni/src/jni/convert_utils.cc, android/sdk/src/main/jni/src/jni/java_turbo_module.cc, android/sdk/src/main/jni/src/jni/turbo_module_manager.cc, core/src/napi/v8/js_native_turbo_v8.cc
=> feat(core): refactor jsi

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderNode.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/modal/HippyModalHostManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/modal/HippyModalHostView.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderProvider.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/UIPromise.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNode.java
refactor(android): v3.0 move node
=> refactor(android): v3.0 move node

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/IHippyNativeLogHandler.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/DefaultLogAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/HippyLogAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, android/sdk/src/main/jni/include/bridge/entry.h, android/sdk/src/main/jni/src/bridge/entry.cc, core/third_party/base/include/base/log_level.h, core/third_party/base/src/platform/adr/logging.cc, examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
=> feat(core): add log level for delegate

android/sdk/build.gradle
=> fix(android): fix `armeabi` architecture build script

framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/module/uimanager/HippyUIManager.h, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix data race if multiple hippy instances created

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.mm
=> fix(ios): use weak self for lambda to capture oc object

ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/textinput/HippyShadowTextView.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix memory leaks when deleting nodes

android/sdk/build.gradle, android/sdk/gradle.properties, android/sdk/gradle/wrapper/gradle-wrapper.properties, examples/android-demo/build.gradle, examples/android-demo/example/build.gradle, examples/android-demo/gradle.properties, examples/android-demo/gradle/wrapper/gradle-wrapper.properties
=> feat(android): update AGP version to 7.1.1

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/DomModel.java
=> fix(android): fix leaf node can't show css

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc
=> feat(dom): update render node info

renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): text mark dirty

android/sdk/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java
=> fix(android): use context.getResources() get windowDisplayMetrics

ios/sdk/component/listview/HippyBaseListItemShadowView.mm, ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/HippyUIManager.mm, ios/sdk/utils/HippyDomNodeUtils.h, ios/sdk/utils/HippyDomNodeUtils.mm
=> fix(ios): fix lazy loading view display issues

ios/sdk/component/listview/HippyBaseListItemView.h, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix view render event handler

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/libraryloader/LibraryLoader.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyForegroundColorSpan.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextView.java
=> feat:textnode custom forgroudcolor

ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): need to dirty shadowviews when creating view from shadowview

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc
=> feat(dom): atomic function interface

dom/src/dom/dom_node.cc
=> feat(dom): update style diff

ios/sdk/base/HippyBatchedBridge.mm
=> refactor(ios): show warning only when bridge is valid

ios/sdk/component/listview/HippyBaseListView.mm
=> fix(ios): fix list horizantal scroll bug

android/sdk/src/main/jni/src/bridge/java2js.cc, android/sdk/src/main/jni/src/inspector/v8_inspector_client_impl.cc, android/sdk/src/main/jni/src/jni/convert_utils.cc, core/include/core/base/string_view_utils.h, core/include/core/napi/js_native_api_types.h, core/include/core/napi/jsc/js_native_api_jsc.h, core/include/core/napi/v8/js_native_api_v8.h, core/src/napi/jsc/js_native_api_jsc.cc, core/src/napi/jsc/js_native_api_value_jsc.cc, core/src/napi/v8/js_native_api_v8.cc, core/src/napi/v8/js_native_turbo_v8.cc, core/third_party/base/include/base/logging.h, examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/module/loader/ios_loader.h
=> feat(core): refactor NAPI and rename macros

ios/sdk/debug/devtools/HippyDevManager.m
=> fix(ios): close web socket when dev manager release

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix mixed type text word order bug

docs/hippy-react/animation.md, docs/hippy-react/modules.md, docs/hippy-react/web.md, docs/hippy-vue/introduction.md, docs/style/layout.md, examples/hippy-react-demo/scripts/hippy-webpack.ios-vendor.js, examples/hippy-react-demo/scripts/hippy-webpack.ios.js, examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js
=> docs(md): update document

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/InspectorDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/PageDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java
1、support multi instance to debug elements
2、fix reload empty when sometimes
=> feat(android): support multi instance to debug elements

ios/sdk/module/netinfo/HippyNetInfoIntenal.m
=> fix(ios): fix currentRadioAccessTechnology unavailable in ios14.2

packages/hippy-react/src/components/pull-footer.tsx
=> refactor(hippy-react): change pull-footer default props syntax

PUBLISH.zh_CN.md, README.md, README.zh_CN.md, docs/guide/debug.md, package-lock.json, package.json
=> fix(lerna): change lerna execute path

renderer/native/ios/renderer/HippyUIManager.mm
=> fix(ios): check null before remove shadow view from registry

docs/guide/debug.md
=> docs(debug): change video path to cdn url

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/view/HippyViewGroupController.java, renderer/native/android/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java, renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/DrawableFactory.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/ArrayUtils.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/PropertyUtils.java
=> refactor(android): v3.0 ripple background

ios/sdk/component/image/HippyAnimatedImageView.m
=> fix(ios): fix image tint color bug

dom/src/dom/dom_manager.cc
=> fix(dom): update domNode crash

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/image/HippyImageView+HippyTouchesImplementation.h, ios/sdk/component/image/HippyImageView+HippyTouchesImplementation.mm
=> fix(ios): add image component touches event handler

ios/sdk/component/image/HippyImageView.h, ios/sdk/component/image/HippyImageView.m, ios/sdk/component/image/HippyImageViewManager.m
=> feat(ios): add shape attribute for imageView

docs/guide/debug.md, examples/hippy-react-demo/package.json, examples/hippy-react-demo/scripts/hippy-webpack.dev.js, examples/hippy-vue-demo/package.json, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js
=> feat(devtools): support debug multiple project at the same time

framework/js/core/src/napi/jsc/js_native_turbo_jsc.cc
=> fix(ios): fix jsi crash on some devices

examples/hippy-react-demo/src/pages/gallery.jsx
=> fix(hippy-react-demo): fix backAndroid routes error

framework/js/examples/ios-demo/HippyDemo/ViewController.mm, renderer/native/ios/renderer/HippyUIManager.h, renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm
=> feat(ios): renderer can create views lazily

ios/sdk/base/HippyComponentData.h, ios/sdk/base/HippyComponentData.mm, renderer/native/ios/renderer/HippyUIManager.h, renderer/native/ios/renderer/HippyUIManager.mm
=> fix(ios): fix component function invoked error

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/layer_optimized_render_manager.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/layer_optimized_render_manager.cc, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): enable LayerOptimizedRenderManager

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
=> fix(android): remove final of bundleName

framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationNode.java
=> fix(android): v3.0 iterator remove

docs/guide/debug.md
=> docs(video): remove debug mp4 video

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippypager/HippyPagerAdapter.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippypager/HippyPagerController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippypager/HippyPagerPageChangeListener.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippypager/transform/VerticalPageTransformer.java, renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TypeFaceUtil.java, renderer/native/android/src/main/java/com/tencent/renderer/serialization/Serializer.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/DisplayUtils.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/MapUtils.java
=> refactor(android): v3.0 use androidX viewPager

docs/guide/debug.md
=> docs(debug): perf debug steps introduction

android/sdk/src/main/jni/src/bridge/entry.cc
=> fix(core): fix jni local ref bug

.github/CODEOWNERS, examples/hippy-vue-demo/src/components/native-demos/demo-vue-native.vue
=> chore(codeowner): change code owner

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix image blurry error

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): fix crash caused by multi-thread race

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/scrollview/HippyScrollView.mm, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/HippyViewManager.mm, ios/sdk/component/view/UIView+DirectionalLayout.h, ios/sdk/component/view/UIView+DirectionalLayout.mm, ios/sdk/component/viewPager/HippyViewPager.mm
=> fix(ios): fix RTL layout error

android/sdk/src/main/jni/src/bridge/entry.cc, core/third_party/base/include/base/logging.h, core/third_party/base/src/platform/adr/logging.cc, core/third_party/base/src/platform/ios/logging.cc
(cherry picked from commit c2bc2a4c46df2aae04266e6b885a173d3106c82a)
(cherry picked from commit b0c29b469d0db8374e4af0760a43cbec4dd540f7)
=> fix(core): fix log delegate crash for multi-thread

android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueDeserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Deserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Serializer.java
=> fix(android): fix nested sub-tag serialization issue

ios/sdk/component/waterfalllist/HippyWaterfallView.mm
=> fix(ios): fix list item appear event callback

ios/sdk/component/image/HippyImageViewManager.m
=> refactor(ios): add src:string property for Image component

ios/sdk/component/modal/HippyModalHostView.mm, ios/sdk/component/modal/HippyModalHostViewManager.mm
=> refactor(ios): modal component support more than one subview

dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc
=> feat(dom): update animation

android/sdk/src/main/jni/src/bridge/entry.cc, core/third_party/base/include/base/logging.h, core/third_party/base/src/platform/adr/logging.cc, core/third_party/base/src/platform/ios/logging.cc, ios/sdk/utils/HippyLog.mm
=> refactor(core): refactor log delegate and remove lock for log

renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/NativeRenderManager.mm
=> feat(ios): adjust codes to support LayerOptimizedRenderManager

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImplDisable.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerInterface.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java
=> feat(android): support debug context name display

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridge.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyCallNativeParams.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManager.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/HippyNativeModuleInfo.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/timer/TimerModule.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Deserializer.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Serializer.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/annotation/HippyMethod.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/annotation/HippyNativeModule.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/common/ThreadExecutor.java, modules/serialization/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueDeserializer.java, modules/serialization/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java
=> refactor(android): v3.0 js framework thread and serialization

android/sdk/src/main/jni/src/bridge/entry.cc, core/third_party/base/include/base/logging.h, core/third_party/base/src/platform/adr/logging.cc, core/third_party/base/src/platform/ios/logging.cc
=> refactor(core): refactor log delegate

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix image load progress error

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/listview/HippyCollectionViewFlowLayout.h, ios/sdk/component/listview/HippyCollectionViewFlowLayout.m, ios/sdk/component/scrollview/HippyScrollView.mm, ios/sdk/component/text/HippyShadowText.mm, ios/sdk/component/view/HippyShadowView.h, ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/HippyViewManager.mm, ios/sdk/component/view/UIView+DirectionalLayout.mm, ios/sdk/component/viewPager/HippyViewPager.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.h, ios/sdk/component/waterfalllist/HippyWaterfallView.mm
=> fix(ios): RTL layout fix

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> feat(ios): smart view pager add to hippyDemo

renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc, renderer/native/ios/renderer/HippyUIManager.mm
=> feat(dom): adjust UpdateRenderNode() to use RenderInfo

ios/sdk/component/scrollview/HippyScrollView.mm
=> fix(ios): fix scroll rtl error

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManagerImpl.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/image/ImageLoaderModule.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/framework/ImageRequestListener.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java, renderer/native/android/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextImageSpan.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/ArrayUtils.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/EventUtils.java
=> refactor(android): v3.0 Align with IOS

dom/src/dom/dom_manager.cc, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc, renderer/native/ios/renderer/HippyUIManager.mm
=> feat(dom): use registered DomNodes when updating and deleting them

framework/js/core/src/napi/jsc/js_native_api_jsc.cc, ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix text align error on RTL layout

dom/src/dom/layer_optimized_render_manager.cc
=> feat(dom): convert a DomValue to Double if it's a number

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyCoreAPI.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java
=> feat(android): use androidX recyclerView

examples/android-demo/gradle.properties
=> build(android-demo): set testOnly false

ios/sdk/component/image/HippyAnimatedImageView.m
=> fix(ios): fix image display crash 

ios/sdk/base/executors/HippyJSCExecutor.h, ios/sdk/base/executors/HippyJSCExecutor.mm
=> refactor(ios): remove unused code

framework/js/core/include/core/modules/ui_manager_module.h, framework/js/core/src/modules/ui_manager_module.cc
=> feat(dom): add event listener and remove listener

renderer/native/ios/renderer/HippyUIManager.mm
=> fix(ios): fix string block capture error

framework/js/core/include/core/modules/ui_manager_module.h, framework/js/core/src/modules/ui_manager_module.cc
=> Revert "feat(dom): add event listener and remove listener"

renderer/native/ios/renderer/HippyUIManager.mm
view hierarchy should update by using [UIView didUpdateHippySubviews]
=> fix(ios): fix subviews insertion

ios/sdk/component/view/HippyShadowView.mm, ios/sdk/component/view/UIView+Hippy.mm
subview may not be inserted in index order
=> fix(ios): fix array insertion exceeds range

framework/js/android/src/main/jni/src/bridge/entry.cc
=> fix(dom): fix animation crash

framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/android/src/main/jni/src/bridge/java2js.cc, framework/js/android/src/main/jni/src/bridge/js2java.cc, framework/js/android/src/main/jni/src/jni/convert_utils.cc, framework/js/android/src/main/jni/src/jni/java_turbo_module.cc, framework/js/core/src/runtime/v8/v8_bridge_utils.cc
=> fix(voltron): fix jni import error

dom/include/dom/dom_value.h, dom/src/dom/deserializer.cc, dom/src/dom/diff_utils.cc, dom/src/dom/dom_argument.cc, dom/src/dom/dom_node.cc, dom/src/dom/dom_value.cc, dom/src/dom/layer_optimized_render_manager.cc, dom/src/dom/serializer.cc, dom/src/dom/taitank_layout_node.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/core/src/modules/ui_manager_module.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, ios/sdk/utils/HippyDomNodeUtils.mm, renderer/native/ios/renderer/NativeRenderManager.mm, test/dom/deserializer_ut.cc, test/dom/dom_value_ut.cc
=> feat(dom): refactor dom value

ios/sdk/component/scrollview/HippyScrollView.mm
=> fix(ios): fix scrollview direction change bug

ios/sdk/component/view/HippyShadowView.mm
we should dirty all descendants propagation, not only self
=> fix(ios): fix dirty descendant propagation error

framework/js/android/src/main/jni/src/jni/turbo_module_manager.cc
=> fix(core): fix jsi crash

dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> fix(dom): fix modal crash

modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/RenderExceptionHandler.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/RenderProxy.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/Renderer.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderDelegate.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
=> refactor(android): v3.0 support TDF renderer

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(android): use renderProxy to init

android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/monitor/DefaultEngineMonitorAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/monitor/HippyEngineMonitorAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/PromiseImpl.java
=> feat(android): add call native and promise callback monitor

dom/src/dom/yoga_layout_node.cc, third_party/yoga/include/YGEnums.h
=> fix(dom): fix yoga dom_value

ios/sdk/component/scrollview/HippyScrollView.mm
=> fix(ios): fix scroll content offset caculate error

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/PromiseImpl.java
=> fix(android): should call onInterceptPromiseCallBack first

ios/sdk/base/HippyComponentData.mm, ios/sdk/component/image/HippyImageView.m, ios/sdk/component/listview/HippyBaseListItemView.h, ios/sdk/component/listview/HippyBaseListItemView.mm, ios/sdk/component/navigator/HippyNavigatorHostView.mm, ios/sdk/component/scrollview/HippyScrollView.mm, ios/sdk/component/view/HippyTouchesView.mm, ios/sdk/component/view/HippyViewManager.mm, ios/sdk/component/view/UIView+AppearEvent.h, ios/sdk/component/view/UIView+AppearEvent.m, ios/sdk/component/view/UIView+HippyEvent.h, ios/sdk/component/view/UIView+HippyEvent.mm, ios/sdk/component/viewPager/HippyViewPager.mm, ios/sdk/component/waterfalllist/HippyWaterfallItemView.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.mm
=> feat(ios): mount & unmount event handler

android/sdk/src/main/jni/src/bridge/java2js.cc, core/src/base/task_runner.cc, core/src/napi/v8/js_native_api_v8.cc, core/third_party/base/include/base/log_settings.h
=> feat(core): change log level

android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/java2js.cc, core/src/base/task_runner.cc, core/src/napi/v8/js_native_api_v8.cc, core/third_party/base/include/base/log_level.h, core/third_party/base/include/base/log_settings.h
=> fix(core): fix log macro conflict for iOS

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(android): post to dom thread do save

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImplDisable.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerInterface.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/PageDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java
=> support debugClientId and fix screencast msg

framework/js/core/src/runtime/v8/v8_bridge_utils.cc, renderer/flutter/core/src/render/queue/render_task_runner.cc
=> bugfix(voltron): fix voltron compile error

docs/ios/integration.md
=> docs(ios): add force load configuration for cocoapods installation

ios/sdk/component/listview/HippyBaseListView.mm, ios/sdk/component/listview/HippyBaseListViewManager.mm, ios/sdk/component/waterfalllist/HippyWaterfallView.h, ios/sdk/component/waterfalllist/HippyWaterfallView.mm
=> fix(ios): fix list scroll event throttle bug

examples/hippy-react-demo/src/modules/NetInfo/index.jsx
=> refactor(react-demo): remove fetch param

docs/guide/debug.md, examples/hippy-vue-demo/package.json, examples/hippy-vue-demo/scripts/hippy-webpack.dev.js, packages/hippy-vue-router/src/create-matcher.js, packages/hippy-vue/src/runtime/index.js, scripts/vue-configs.js
=> feat(devtools): support vue-devtools

framework/js/flutter/lib/engine/js_dimension_checker.dart, framework/js/flutter/lib/module/event_dispatcher.dart, renderer/flutter/lib/render/manager.dart, renderer/flutter/lib/render/node.dart, renderer/flutter/lib/serialization/writer/binary_writer.dart, renderer/flutter/lib/util/dimension_util.dart, renderer/flutter/lib/viewmodel/view_model.dart, renderer/flutter/lib/widget/div.dart, renderer/flutter/test/test_serializer.dart
=> fix voltron serializer error

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/root_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/root_node.cc
=> feat(dom): implement RootNode

dom/include/dom/dom_node.h, dom/src/dom/dom_node.cc, dom/src/dom/root_node.cc, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> feat(dom): fix iOS compile error for RootNode

ios/sdk/module/localstorage/HippyAsyncLocalStorage.h, ios/sdk/module/localstorage/HippyAsyncLocalStorage.mm
=> refactor(ios): aynclocalstorage file refactor

renderer/flutter/lib/serialization/primitive_value_serializer.dart, renderer/flutter/lib/serialization/writer/binary_writer.dart, renderer/flutter/test/test_serializer.dart
=> fix(voltron): fix voltron long string encode failed

dom/include/dom/root_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/root_node.cc
=> feat(dom): pass DomManager to RootNode when initializing it

dom/include/dom/dom_node.h, dom/include/dom/root_node.h, dom/src/dom/dom_manager.cc, dom/src/dom/root_node.cc
=> feat(dom): pass DomManager to RootNode in DomManager::SetRenderManager()

ios/sdk/base/HippyComponentData.h, ios/sdk/base/HippyComponentData.mm, renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefreshManager.mm, renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefreshManager.mm, renderer/native/ios/renderer/component/listview/HippyBaseListViewManager.mm, renderer/native/ios/renderer/component/navigator/HippyNavigatorViewManager.mm, renderer/native/ios/renderer/component/refreshview/HippyRefreshWrapperViewManager.mm, renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm, renderer/native/ios/renderer/component/smartViewPager/HippySmartViewPagerViewManager.mm, renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm, renderer/native/ios/renderer/component/view/HippyViewManager.h, renderer/native/ios/renderer/component/viewPager/HippyViewPagerManager.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.mm
=> refactor(ios): component method export

android/sdk/src/main/jni/include/jni/jni_env.h, android/sdk/src/main/jni/src/jni/jni_env.cc, core/include/core/napi/js_native_api.h, core/src/base/task_runner.cc, core/src/napi/jsc/js_native_api_jsc.cc, core/src/napi/v8/js_native_api_v8.cc, core/src/task/worker_task_runner.cc
(cherry picked from commit f4f59bbac8523887a6918c7aee56e3522a16df87)
=> fix(core): fix jni detach crash

dom/src/dom/root_node.cc
=> feat(core): 1. add dom tree event 2. modify dom event name

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java
=> fix(devtools): fix alpha screencast

renderer/native/ios/renderer/component/view/UIView+HippyEvent.mm
=> fix(ios): fix attached to window and did mount event

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, examples/ios-demo/HippyDemo/ViewController.m, ios/sdk/base/HippyBatchedBridge.mm, ios/sdk/base/HippyBridge.h, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyBridgeMethod.h, ios/sdk/base/HippyMethodInterceptorProtocol.h, ios/sdk/base/HippyModuleMethod.h, ios/sdk/base/HippyModuleMethod.mm
=> feat(ios): method invoke interceptor

dom/include/dom/animation_manager.h, dom/include/dom/dom_action_interceptor.h, dom/include/dom/dom_manager.h, dom/include/dom/node_props.h, dom/include/dom/root_node.h, dom/src/dom/animation_manager.cc, dom/src/dom/diff_utils.cc, dom/src/dom/dom_manager.cc, dom/src/dom/root_node.cc, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/android/src/main/jni/include/bridge/entry.h, framework/js/android/src/main/jni/src/bridge/entry.cc, modules/link_supplier/src/main/java/com/tencent/link_supplier/LinkHelper.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> feat(dom): complete animation

renderer/native/ios/renderer/HippyComponentData.mm
=> fix(ios): fix component selector parse error

framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, framework/js/ios/base/HippyBatchedBridge.mm, framework/js/ios/base/HippyBridge.h, framework/js/ios/base/HippyBridge.mm, framework/js/ios/base/HippyBridgeMethod.h, framework/js/ios/base/HippyMethodInterceptorProtocol.h, framework/js/ios/base/HippyModuleMethod.h, framework/js/ios/base/HippyModuleMethod.mm
=> feat(iOS):method invoke interceptor 

dom/src/dom/root_node.cc
=> fix(dom): fix dom event

scripts/build-core.js
=> feat(core): change buildcore output directory for iOS

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java
=> fix(android): add RecyclerView extra class name

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): fix strange shaped text render bug

docs/guide/debug.md
=> chore(devtools): change vue-devtools docs

renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/component/refreshview/HippyRefreshWrapperViewManager.mm
=> fix(ios): fix component method invoke param type check

dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/animation_manager.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, framework/js/core/src/modules/scene_builder.cc, renderer/native/android/src/main/jni/src/render/native_render_manager.cc, renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/component/text/HippyShadowText.mm, renderer/native/ios/renderer/component/view/HippyShadowView.mm
=> feat(dom): refactor post task

dom/src/dom/animation_manager.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, renderer/native/android/src/main/jni/src/render/native_render_manager.cc, renderer/native/ios/renderer/component/view/HippyShadowView.mm
=> feat(dom): refactor code

examples/hippy-vue-demo/src/components/demos/demo-textarea.vue, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/runtime/directives/model.js
=> fix(hippy-vue): fixed vue text update filter

renderer/native/ios/renderer/component/view/HippyShadowView.mm
=> fix(dom): fix post task

dom/include/dom/animation_manager.h, dom/include/dom/dom_manager.h, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h
=> feat(dom): add disable copy and assign constructor

ios/sdk/component/textinput/HippyBaseTextInput.h, ios/sdk/component/textinput/HippyBaseTextInput.m, ios/sdk/component/textinput/HippyTextField.h, ios/sdk/component/textinput/HippyTextField.m, ios/sdk/component/textinput/HippyTextView.h, ios/sdk/component/textinput/HippyTextView.mm, ios/sdk/component/textinput/HippyTextViewManager.mm
=> feat(ios): add textinput keyboard height changed event

ios/sdk/utils/HippyLog.mm
=> fix(ios): remove an unused macro check

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevRemoteServerData.java
=> fix(android): fix remote url debug not contains version

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java, modules/link_supplier/src/main/java/com/tencent/link_supplier/proxy/renderer/NativeRenderProxy.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
=> fix(android): call update root size when reload in debug mode

ios/sdk/debug/devtools/inspector/model/HippyPageModel.m
=> feat(devtools): change the screenshot canvas background to white

packages/hippy-react/src/components/list-view.tsx, packages/hippy-react/src/dom/element-node.ts, packages/hippy-react/src/renderer/host-configs.ts, packages/hippy-react/src/renderer/render.ts, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/index.js
=> feat(react): change updateNode to batch operation & perf event binding

dom/src/dom/deserializer.cc, dom/src/dom/taitank_layout_node.cc, layout/engine/HPNode.cpp
=> feat(dom): fix compile warning

framework/js/android/src/main/jni/src/bridge/bridge.cc, framework/js/android/src/main/jni/src/bridge/entry.cc, framework/js/android/src/main/jni/src/bridge/js2java.cc, framework/js/android/src/main/jni/src/jni/convert_utils.cc, framework/js/android/src/main/jni/src/jni/exception_handler.cc, framework/js/android/src/main/jni/src/loader/adr_loader.cc, framework/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc
=> fix(core): fix jni pending exception crash

framework/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderNode.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippypager/HippyPagerPageChangeListener.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyOnScrollHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyScrollViewEventHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/ViewPagerPageChangeListener.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/EventUtils.java
=> refactor(android): v3.0 scroll view event handle impl

.github/workflows/android_build_tests.yml
=> ci(android): add android build tests on PR stage

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
=> feat(android): support sync restoreInstanceState

dom/include/dom/diff_utils.h, dom/src/dom/diff_utils.cc
=> feat(dom): refactor diff utils

framework/js/examples/ios-demo/HippyDemo/myview/MyViewManager.mm, renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefreshManager.mm, renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefreshManager.mm, renderer/native/ios/renderer/component/listview/HippyBaseListViewManager.mm, renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm, renderer/native/ios/renderer/component/smartViewPager/HippySmartViewPagerViewManager.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.mm
=> fix(ios): fix component method parameter type error

packages/hippy-vue-loader/lib/vue-hot-reload-api/index.js
=> fix(hippy-vue): fix hmr for root App component

.github/workflows/android_build_tests.yml
=> ci(android): change gradlew working directory

docs/guide/debug.md
=> fix(docs): add debug access introduction

.github/labeler.yml, .github/workflows/gh_pr_labeler.yml
=> ci(workflows): add pull request label bot

.github/labeler.yml
=> ci(labeler): update auto label directory

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/jni/include/jni/turbo_module_manager.h, android/sdk/src/main/jni/src/jni/turbo_module_manager.cc
=> fix(core): fix turbomodule crash

docs/en-us/guide/integration.md, docs/guide/debug.md, docs/guide/integration.md
=> chore(docs): modify hippy:dev script

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java
=> fix(android): reset recycle view stick view item type

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/font/DefaultFontScaleAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/font/HippyFontScaleAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
=> feat(android): support host customize default font family

ios/sdk/component/image/HippyImageView.m
=> refactor(ios): set animated image queue concurrent count to maxiumum

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java
=> fix(android): reset pull header position on scroll back

core/include/core/base/string_view_utils.h, core/third_party/base/include/base/logging.h
=> fix(core): fix convert bug

android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/SafeHeapWriter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Deserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Serializer.java
=> fix(android): fix java lint warnings

core/include/core/engine.h, core/src/engine.cc, core/src/modules/contextify_module.cc
(cherry picked from commit 62fc9cfa191e8bb254bbaa147ca8b5996bab57e3)
=> fix(core): fix mutex crash

dom/src/dom/dom_node.cc, layout/engine/HPNode.cpp, layout/engine/HPUtil.cpp, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> fix(layout): fix layout convert error

dom/include/dom/dom_node.h, dom/include/dom/layout_node.h, dom/include/dom/taitank_layout_node.h, dom/include/dom/yoga_layout_node.h, dom/src/dom/dom_node.cc, dom/src/dom/taitank_layout_node.cc, dom/src/dom/yoga_layout_node.cc, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/js/examples/ios-demo/HippyDemo/TestModule.mm, framework/js/examples/ios-demo/HippyDemo/ViewController.mm, framework/js/ios/base/HippyBridge.h, framework/js/ios/base/HippyBridge.mm, renderer/native/ios/renderer/NativeRenderManager.mm, renderer/native/ios/renderer/component/text/HippyShadowText.mm, renderer/native/ios/renderer/component/text/HippyText.mm, renderer/native/ios/renderer/component/view/HippyShadowView.mm
=> fix(ios): fix nested text display issuse

dom/include/dom/dom_listener.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/dom_listener.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/scene_builder.cc, framework/js/core/include/core/napi/js_native_api_types.h, framework/js/core/include/core/napi/jsc/js_native_api_jsc.h, framework/js/core/include/core/napi/v8/js_native_api_v8.h, framework/js/core/include/core/scope.h, framework/js/core/src/modules/scene_builder.cc, framework/js/core/src/napi/jsc/js_native_api_jsc.cc, framework/js/core/src/napi/v8/js_native_api_v8.cc, framework/js/core/src/scope.cc, framework/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> feat(dom): support add multiple events

.github/PULL_REQUEST_TEMPLATE.md
=> docs(PR): change PULL_REQUEST_TEMPLATE.md content

framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineHost.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/adapter/http/HippyHttpRequest.java, framework/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/clipboard/ClipboardModule.java, modules/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/ContextHolder.java, modules/serialization/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/PreloadHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullFooterEventHelper.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java, renderer/native/android/src/main/java/com/tencent/renderer/utils/EventUtils.java
=> Feat/merge from 2.0

dom/include/dom/dom_value.h, dom/src/dom/dom_value.cc
=> feat(dom): add operator<< for dom value

dom/include/dom/layer_optimized_render_manager.h, dom/include/dom/render_manager.h, dom/src/dom/layer_optimized_render_manager.cc, renderer/native/android/src/main/jni/include/render/hippy_render_manager.h, renderer/native/android/src/main/jni/src/render/hippy_render_manager.cc, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm
=> feat(dom): add vsync singal

android/sdk/build.gradle, android/sdk/gradle.properties, android/sdk/src/main/jni/CMakeLists.txt
=> feat(android): use HIP(hippy-infa-packages) to replace local `v8`

core/include/core/base/string_view_utils.h, core/third_party/base/include/base/logging.h
=> fix(core): fix iOS warning

docs/en-us/hippy-react/components.md, docs/en-us/hippy-vue/components.md, docs/hippy-react/components.md, docs/hippy-vue/components.md
=> chore(docs): add keyboardheightchanged event for ios

.github/CODEOWNERS
=> fix(voltron): add code owner

driver/js/android/build.gradle, driver/js/android/src/main/jni/minimum_exports.lst
=> feat(android): optimize sdk build scripts

android/sdk/src/main/jni/CMakeLists.txt
=> feat(android): remove unused cmake variable

package-lock.json, packages/hippy-react-web/package-lock.json, packages/hippy-react/package-lock.json, packages/hippy-react/src/components/focusable.tsx
=> refactor(react): revert package-lock changes

driver/js/examples/ios-demo/HippyDemo/ViewController.mm, renderer/native/ios/renderer/HippyUIManager.h, renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm
=> feat(ios): add interface for setting custom component

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
=> fix(android): call engine context method NullPointerException

driver/js/android/build.gradle
=> fix(android): add dealAfterStripSymbols in driver gradle

ios/sdk/component/image/HippyImageView.h, ios/sdk/component/image/HippyImageView.m
=> fix(ios): reduce GPU usage by reducing off-screen rendering

renderer/native/ios/renderer/component/image/HippyImageView.h, renderer/native/ios/renderer/component/image/HippyImageView.m
* refactor(ios): change method and variable name
* fix(ios): fix corner radius bugs
try to reduce off-screen render by checking radius and 4 corner radius property
use layer.cornerRadius property for rounded corners whenever possible
=> fix(ios): reduce GPU usage by reducing off-screen rendering (#1902)

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageViewController.java
=> fix(native_render): fix the bug that ImageView can't set event callbacks

.github/workflows/frontend_build_tests.yml, .gitignore, packages/hippy-debug-server/package-lock.json, packages/hippy-react-web/package-lock.json, packages/hippy-react/package-lock.json, packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-loader/package-lock.json, packages/hippy-vue-router/package-lock.json, packages/hippy-vue/package-lock.json
This reverts commit 345d0a46214654749a46b405c2ce0a2fb340dca3.
=> Revert "refactor(js): remove package-lock.json"

docs/guide/debug.md
=> chore(docs): change debug docs

.github/workflows/ios_build_tests.yml
=> ci(ios): fix ios build test

dom/include/dom/animation_manager.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/include/dom/root_node.h, dom/src/dom/animation_manager.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/root_node.cc, dom/src/dom/serializer.cc
=> feat(dom): clean up clang warning

android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/java2js.cc
=> fix(android): fix `v8` inspector does not work

ios/sdk/component/view/HippyView.m, ios/sdk/utils/HippyGradientObject.m
context is null if size area is zero
=> fix(ios): fix crash due to null pointer

docs/en-us/guide/integration.md
=> docs(homepage): change integration docs

.github/workflows/hip_archive_artifact.yml, .github/workflows/hip_list_artifacts.yml
=> feat(workflows): add Hippy Infra Packages(HIP) related workflows

ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): adjust text layout

driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, renderer/native/ios/renderer/HippyRenderContext.h, renderer/native/ios/renderer/HippyUIManager.mm, renderer/native/ios/renderer/component/listview/HippyBaseListItemView.mm, renderer/native/ios/renderer/component/listview/HippyBaseListView.mm, renderer/native/ios/renderer/component/listview/HippyBaseListViewCell.h, renderer/native/ios/renderer/component/smartViewPager/HippySmartViewPagerView.mm, renderer/native/ios/renderer/component/view/HippyShadowView.h, renderer/native/ios/renderer/component/view/HippyShadowView.mm, renderer/native/ios/renderer/component/view/UIView+Hippy.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWatefallItemShadowView.h, renderer/native/ios/renderer/component/waterfalllist/HippyWatefallItemShadowView.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallItemViewManager.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.h, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewCell.h, renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewCell.mm
=> feat(ios): apply reuse feature to list and waterfall components

.gitignore, android/sdk/src/main/jni/CMakeLists.txt, build/cmake/InfraPackagesModule.cmake
=> chore(cmake): cmake adds `InfaPackage` module

driver/js/examples/android-demo/build.gradle, gradle.properties
=> refactor(android): update sub project AGP to 7.2.1

driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/examples/ios-demo/HippyDemo/ViewController.mm
=> feat(dom): remove demo for vl

.gitignore
=> chore(gitignore): remove useless tracking

buildconfig/cmake/InfraPackagesModule.cmake
=> feat(cmake): do not overwrite original value

driver/js/core/third_party/base/include/base/log_level.h, driver/js/ios/base/HippyBatchedBridge.mm, driver/js/ios/base/HippyBridge.mm, driver/js/ios/utils/HippyLogging.mm, renderer/native/ios/utils/HippyLog.mm
=> fix(ios): make DomManager.SetRootSize called in dom thread

dom/src/dom/animation/animation_manager.cc
This reverts commit 1eef1014c58ebd4a7a95314a61efeefcfb7117c2.
=> Revert "feat(dom): refactor update animation"

docs/en-us/hippy-vue/external-components.md, docs/hippy-vue/external-components.md, examples/hippy-react-demo/src/modules/Animation/index.jsx, examples/hippy-vue-demo/src/components/native-demos/demo-pull-footer.vue, packages/hippy-vue-native-components/src/animation.js
=> feat(hippy-vue): refactor vue animation events

dom/src/dom/dom_manager.cc, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/ios/base/HippyBridge.mm
=> feat(dom): remove redundant code

android/sdk/src/main/jni/CMakeLists.txt, buildconfig/cmake/InfraPackagesModule.cmake
=> fix(cmake): fix typo problems

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
=> fix(text_input): enable event callbacks of TextInput

dom/CMakeLists.txt, dom/include/dom/animation/animation_manager.h, dom/src/dom/animation/animation.cc, dom/src/dom/animation/cubic_bezier_animation.cc
=> feat(dom): standardize build script and fix lint problem

renderer/native/android/src/main/jni/CMakeLists.txt, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> feat(native_renderer): standardize build script

driver/js/ios/utils/HippyLogging.mm, renderer/native/ios/renderer/component/text/HippyShadowText.mm, renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm
=> fix(ios): ceil width and height that text layout needs

renderer/native/ios/renderer/component/view/HippyView.mm, renderer/native/ios/renderer/component/view/HippyViewManager.mm
=> fix(ios): fix a bug that fetch a wrong frame due to transform

dom/include/dom/deserializer.h, dom/include/dom/dom_manager.h, dom/include/dom/dom_node.h, dom/src/dom/deserializer.cc, dom/src/dom/dom_manager.cc, dom/src/dom/dom_node.cc, dom/src/dom/root_node.cc, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/examples/ios-demo/HippyDemo/ViewController.mm, driver/js/ios/base/HippyBridge.mm, renderer/native/ios/renderer/NativeRenderManager.mm, renderer/native/ios/utils/HippyDomNodeUtils.mm
=> feat(dom): add snapshot

docker/android-release/Dockerfile
=> fix(docker): use 2.7 version of `get-pip.py` instead

renderer/native/ios/renderer/HippyFont.mm, renderer/native/ios/renderer/component/text/HippyShadowText.mm, renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm
=> fix(ios): fix memory leaks due to lack of autoreleasepool

android/sdk/gradle.properties, android/sdk/src/main/jni/CMakeLists.txt, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/bridge/java2js.cc, android/sdk/src/main/jni/src/bridge/js2java.cc, android/sdk/src/main/jni/src/jni/convert_utils.cc, android/sdk/src/main/jni/src/jni/java_turbo_module.cc, core/CMakeLists.txt, core/include/core/napi/v8/js_native_api_v8.h, core/src/napi/v8/js_native_turbo_v8.cc
=> refactor(cmake): refactor build scripts using modernized cmake

driver/js/ios/base/HippyBridge.h, driver/js/ios/base/HippyBridge.mm, renderer/native/ios/renderer/HippyInvalidating.h
=> feat(devtools): fix error invalidate reason

renderer/native/android/src/main/jni/include/render/native_render_manager.h, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> feat(dom): optimize the operation of handling event listeners

android/sdk/src/main/jni/CMakeLists.txt, core/CMakeLists.txt
=> fix(cmake): fix `core.modules` not automatically registered problem

devtools/devtools-backend/CMakeLists.txt, dom/CMakeLists.txt, driver/js/android/gradle.properties, driver/js/android/src/main/jni/CMakeLists.txt, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/android/src/main/jni/src/bridge/java2js.cc, driver/js/core/CMakeLists.txt, layout/CMakeLists.txt, renderer/native/android/src/main/jni/CMakeLists.txt
=> refactor(cmake): optimize build scripts using modernized cmake

driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineHost.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManager.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevFactory.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevRemoteServerData.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerConfig.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerHelper.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImpl.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImplDisable.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerInterface.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java, driver/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/BaseActivity.java, driver/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivityDeprecated.java, driver/js/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/module/TestModule.java
=> feat(devtools): support remote debug

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullFooterRefreshHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullRefreshHelper.java
=> fix(android): pull foot and header can exist at same time

.github/workflows/docs_markdown_lint.yml, .github/workflows/frontend_build_tests.yml, .github/workflows/git_commit_lint.yml, driver/js/scripts/build-example.js, driver/js/scripts/init-example.js
=> ci(js): add node_modules cache

renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm
=> fix(ios): fix scroll parameter of scrollto method

devtools/devtools-backend/CMakeLists.txt, dom/tests/CMakeLists.txt, driver/js/flutter/cmake/framework_core.cmake
=> feat(devtools): add comments for cmake

driver/js/core/src/scope.cc
=> feat(devtools): update context name to frontend

driver/js/core/src/modules/animation_module.cc
=> fix(dom): fix animation cb crash

ios/sdk/component/footerrefresh/HippyFooterRefresh.m, ios/sdk/component/headerrefresh/HippyHeaderRefresh.m
=> fix(ios): fix refresh bug for header refresh and footer refresh

.github/workflows/gh_pr_checks_approval.yml
=> ci(workflows): new for auto checks approval robot

ios/sdk/component/view/HippyView.m
because background image covers bottom border color
=> fix(ios): fix border bottom color display error

ios/sdk/module/network/HippyNetWork.m
=> fix(ios): check cookie availabity before commit

devtools/devtools-backend/src/api/notification/default/default_runtime_notification.cc, driver/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, driver/js/ios/base/executors/HippyJSCExecutor.mm, driver/js/ios/debug/devtools/HippyDevInfo.h, driver/js/ios/debug/devtools/HippyDevInfo.m
=> feat(devtools): add prefix for context name

driver/js/android/src/main/jni/include/jni/convert_utils.h, driver/js/android/src/main/jni/src/jni/convert_utils.cc
=> fix(android): fix occasional crash when jsi convert

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridge.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DebugWebSocketClient.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java, android/sdk/src/main/java/com/tencent/mtt/hippy/websocket/HybiParser.java, android/sdk/src/main/java/com/tencent/mtt/hippy/websocket/WebSocketClient.java
=> Feature/devtools 2.0

ios/sdk/component/listview/HippyBaseListItemView.h, ios/sdk/component/waterfalllist/HippyWaterfallItemView.h
border attribute can be setted for item view
=> feat(ios): make item view be a subclass of hippyview

renderer/native/ios/renderer/component/view/HippyBorderDrawing.m, renderer/native/ios/renderer/component/view/HippyBorderStyle.h, renderer/native/ios/renderer/component/view/HippyView.mm, renderer/native/ios/utils/HippyConvert.mm
border color is only displayed when border style and width setted
=> feat(ios): adjust borderColor display conditions

packages/hippy-react-web/package.json, packages/hippy-react-web/src/components/scroll-view.tsx, packages/hippy-react-web/src/index.ts, packages/hippy-react-web/src/modules/net-info.ts, packages/hippy-react-web/src/native.ts, packages/hippy-react-web/src/utils/index.ts, scripts/build.js, scripts/react-configs.js
=> feat(hippy-react-web): support tree-sharking & fix issues

ios/sdk/module/network/HippyNetWork.m
=> fix(ios): modify cookie setting logic

ios/sdk/debug/devtools/HippyDevManager.m, ios/sdk/debug/devtools/inspector/HippyInspector.h, ios/sdk/debug/devtools/inspector/HippyInspector.m
=> feat(devtools): remove ios inspector instance

driver/js/android/src/main/java/com/tencent/mtt/hippy/adapter/http/DefaultHttpAdapter.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/adapter/http/HippyHttpAdapter.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/adapter/http/HippyHttpRequest.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/NetworkModule.java
=> refactor(android): rebuild NetworkModule and DefaultHttpAdapter

.gitignore
=> fix(android): remove unnecessary dir form git ignore

ios/sdk/component/listview/HippyBaseListView.h
=> refactor(ios): remove unused method statement

.github/workflows/security_codeql_analyses.yml, .github/workflows/security_codeql_analyses_bypass.yml
=> ci(workflows): add `CodeQL` code security scanning tool

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): use smart pointer instead of non-smart pointer

.github/workflows/security_codeql_analyses.yml, .github/workflows/security_codeql_analyses_bypass.yml, android/sdk/build.gradle
=> fix(android): fix the `skipCmakeAndNinja` flag does not take effect

.github/CODEOWNERS
=> ci(codeowners): update codeowners file

.github/CODEOWNERS
=> ci(codeowner): update codeowner file

.github/workflows/security_codeql_analyses.yml
=> fix(workflows): fix CodeQL analysis failure problem

dom/include/dom/scene_builder.h, dom/src/dom/deserializer.cc, dom/src/dom/scene_builder.cc, driver/js/core/include/core/napi/js_native_api_types.h, driver/js/core/include/core/napi/jsc/js_native_api_jsc.h, driver/js/core/include/core/napi/v8/js_native_api_v8.h, driver/js/core/src/modules/scene_builder.cc, driver/js/core/src/napi/jsc/js_native_api_jsc.cc, driver/js/core/src/napi/v8/js_native_api_v8.cc
=> feat(dom): support capture parameter in addEventListener function

.github/workflows/security_codeql_analyses.yml
=> fix(workflows): fix CodeQL not working as expected

.github/workflows/security_codeql_analyses.yml
=> ci(workflows): remove CodeQL paths ignore

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyImageSpan.java, android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyLineHeightSpan.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerViewBase.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/Scroller.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/viewpager/ViewPager.java
=> fix(android): implicit narrowing conversion in compound assignment

ios/sdk/component/image/HippyImageView.m
use strong ptr instead of weak ptr
=> fix(ios): fix potentian crash due to dangling pointer

driver/js/packages/hippy-vue/src/renderer/element-node.js, driver/js/packages/hippy-vue/src/renderer/view-node.js
=> fix(hippy-vue): fix referendeNode not found error

.github/workflows/gh_pr_checks_approval.yml
=> feat(workflows): optimize logic to reduce misjudgment

.github/workflows/gh_pr_checks_approval.yml, .github/workflows/security_codeql_analyses.yml, driver/js/android/build.gradle
=> chore: cp workflows from master

ios/sdk/base/executors/HippyJSCExecutor.mm
=> refactor(ios): add autorelease pool for bundle load scope

.github/workflows/security_codeql_analyses.yml
=> ci(workflows): enable CodeQL analyses on PRs

driver/js/core/src/modules/scene_builder.cc
=> fix(dom): fix addEventListener crash error

android/sdk/src/main/java/com/tencent/mtt/hippy/views/view/HippyViewGroup.java
=> fix(android): reset hippy view group clip children to true

core/src/napi/jsc/js_native_api_value_jsc.cc
=> fix(core): fix CreateJSCString bug

ios/sdk/base/HippyBatchedBridge.mm
=> fix(ios): fix potential crash due to dangling pointer

driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/core/third_party/base/include/base/persistent_object_map.h, renderer/native/android/src/main/jni/include/render/native_render_manager.h, renderer/native/android/src/main/jni/src/render/native_render_jni.cc, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> feat(dom): adjust static render manager map to presistent object map

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/PageModel.java
=> fix(devtools): fix mini scale for screen cast

driver/js/packages/hippy-vue/src/renderer/native/event/dispatcher.js
=> fix(hippy-vue): remove unused code

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/HippyGlobalConfigs.java, android/sdk/src/main/java/com/tencent/mtt/hippy/adapter/http/HippyHttpRequest.java, android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/uimanager/UIManagerModule.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/FocusFinder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/utils/StrictFocusFinder.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecycleViewFocusHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/list/HippyListViewFocusHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollViewFocusHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollViewFocusHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/websocket/WebSocketClient.java
1. list scroll to center of screen
2. view background with gradient
3. FocusFinder for tv
4. GlobalConfig add native map
5. HttpTaskCallback.onTaskFailed add errorCode for web
6. fix WebsocketClient Multi thread
7. tv touch
feat(android): merge TVHippySdk to master
fix getChildAt NPE
feat(android): merge TVHippySdk to master
refactor focus helper
feat(android): merge TVHippySdk to master
HippyRecyclerView focusHelper support vertical and horizontal
feat(android): merge TVHippySdk to master
add HippyRecycleViewFocusHelper license
feat(android): support TV platform
fix(android): revert TV modify about HippyViewController
=> feat(android): merge TVHippySdk to master

.github/workflows/gh_mark_and_close_stalled.yml
=> ci(workflows): update stale actions parameters

packages/hippy-react/src/modules/ui-manager-module.ts
=> fix(react): add ref null judgement for getElementFromFiberRef

.github/workflows/gh_mark_and_close_stalled.yml
=> ci(workflows): change stale startup time

driver/js/ios/module/turbo/HippyOCTurboModule.mm, driver/js/ios/module/turbo/NSObject+HippyTurbo.h, driver/js/ios/module/turbo/NSObject+HippyTurbo.mm
=> feat(ios): remove uncall codes

layout/engine/HPNode.cpp
=> fix(layout): fix layout cache error

driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/android/src/main/jni/src/jni/turbo_module_manager.cc, driver/js/core/include/core/engine.h, driver/js/core/include/core/scope.h, driver/js/core/src/modules/timer_module.cc, driver/js/core/src/runtime/v8/inspector/v8_inspector_client_impl.cc, driver/js/core/src/runtime/v8/v8_bridge_utils.cc, driver/js/core/src/scope.cc, driver/js/ios/base/executors/HippyJSCExecutor.mm, modules/footstone/include/footstone/worker_manager.h, modules/footstone/src/footstone/one_shot_timer.cc, modules/footstone/src/footstone/thread_worker.cc, modules/footstone/src/footstone/worker.cc
This reverts commit 3f840c9c088f00a6ffa8774f19c51700f7274ef4.
=> fix(base): fix timer bug

driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(android): worker manager id should > 0

renderer/native/ios/renderer/NativeRenderContext.h, renderer/native/ios/renderer/NativeRenderUIManager.h, renderer/native/ios/renderer/NativeRenderUIManager.mm, renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm
=> refactor(ios): refactor uimanager method queue notification

docs/en-us/ios/integration.md, docs/ios/integration.md
=> chore(docs): improve podfile configuration

renderer/native/ios/renderer/NativeRenderComponentMap.h, renderer/native/ios/renderer/NativeRenderComponentMap.mm, renderer/native/ios/renderer/NativeRenderUIManager.mm
ComponentMap needs run in main thread if it contains UIView
=> feat(ios): add thread check for component map

dom/include/dom/dom_manager.h, driver/js/android/src/main/jni/include/bridge/entry.h, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/core/include/core/engine.h, driver/js/core/include/core/modules/timer_module.h, driver/js/core/src/engine.cc, driver/js/core/src/modules/timer_module.cc, driver/js/core/src/runtime/v8/inspector/v8_inspector_client_impl.cc, driver/js/core/src/runtime/v8/v8_bridge_utils.cc, driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/ios/base/HippyBatchedBridge.mm, driver/js/ios/base/HippyJSEnginesMapper.mm, modules/android/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java, modules/footstone/include/footstone/base_timer.h, modules/footstone/include/footstone/one_shot_timer.h, modules/footstone/include/footstone/repeating_timer.h, modules/footstone/include/footstone/task_runner.h, modules/footstone/include/footstone/thread_worker.h, modules/footstone/include/footstone/worker.h, modules/footstone/include/footstone/worker_manager.h, modules/footstone/src/base_timer.cc, modules/footstone/src/one_shot_timer.cc, modules/footstone/src/platform/adr/logging.cc, modules/footstone/src/platform/ios/logging.cc, modules/footstone/src/repeating_timer.cc, modules/footstone/src/worker.cc, modules/footstone/src/worker_manager.cc
=> fix(base): fix reload crash

driver/js/core/src/runtime/v8/v8_bridge_utils.cc, modules/footstone/src/task_runner.cc
=> fix(core): fix v8  breakpoint

driver/js/core/src/runtime/v8/v8_bridge_utils.cc
=> fix(core): add global_inspector mutex

buildconfig/cmake/GlobalPackagesModule.cmake
=> chore(cmake): remove non-existing packages

.github/workflows/android_build_tests.yml, .github/workflows/android_build_tests_bypass.yml, .github/workflows/ios_build_tests.yml, .github/workflows/ios_build_tests_bypass.yml
=> ci(workflows): add build tests trigger paths

ios/sdk/component/image/HippyImageViewManager.m, ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): reset properties if value is null

docs/en-us/guide/exception.md, docs/en-us/hippy-vue/components.md, docs/hippy-vue/components.md
=> docs(homepage): update docs

modules/footstone/include/footstone/task_runner.h
=> fix(base): fix std::result_of warning on c++17

package-lock.json, package.json, packages/hippy-react-web/package-lock.json, packages/hippy-react/package-lock.json, packages/hippy-vue-loader/package-lock.json, packages/hippy-vue-router/package-lock.json
=> fix(npm): update lerna to fix vulernable npm package

android/sdk/src/main/java/com/tencent/mtt/hippy/websocket/WebSocketClient.java
=> fix(android): fix websocket frame for ping and close

renderer/native/ios/renderer/component/view/NativeRenderView.mm
=> fix(ios): check weak self status

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/modal/HippyModalHostView.java, renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
=> fix(android): remove on create node call update modal size

ios/sdk/base/HippyBatchedBridge.mm
=> Fix potential deadlock problem caused by CADiaplaylink on iphone13Pro or pro max

driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/examples/ios-demo/HippyDemo/myview/MyViewManager.mm, driver/js/ios/base/HippyBatchedBridge.mm, driver/js/ios/base/HippyBridge.h, driver/js/ios/base/HippyBridge.mm, driver/js/ios/base/HippyRootView.mm, renderer/native/ios/renderer/NativeRenderImpl.h, renderer/native/ios/renderer/NativeRenderImpl.mm, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm, renderer/native/ios/renderer/RenderVsyncManager.mm, renderer/native/ios/renderer/component/viewPager/NativeRenderViewPagerItemManager.h, renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
=> refactor(ios): rename HippyUIManager to NativeRenderImpl

dom/include/dom/root_node.h, dom/include/dom/scene_builder.h, dom/src/dom/animation/animation.cc, dom/src/dom/dom_manager.cc, dom/src/dom/root_node.cc, dom/src/dom/scene_builder.cc, driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, driver/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, driver/js/android/src/main/jni/include/bridge/entry.h, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/core/include/core/runtime/v8/v8_bridge_utils.h, driver/js/core/src/modules/animation_module.cc, driver/js/core/src/modules/scene_builder.cc, driver/js/core/src/modules/ui_manager_module.cc, driver/js/core/src/runtime/v8/v8_bridge_utils.cc, driver/js/core/src/scope.cc, driver/js/examples/ios-demo/HippyDemo/ViewController.mm, driver/js/ios/base/HippyBatchedBridge.mm, driver/js/ios/base/HippyBridge+Private.h, driver/js/ios/base/HippyBridge.h, driver/js/ios/base/HippyBridge.mm, driver/js/ios/base/HippyJSEnginesMapper.h, driver/js/ios/base/HippyJSEnginesMapper.mm, modules/android/link_supplier/src/main/java/com/tencent/link_supplier/LinkHelper.java, modules/android/link_supplier/src/main/java/com/tencent/link_supplier/Linker.java
=> feat(dom): merge js thread and dom thread

buildconfig/cmake/compiler_toolchain.cmake, devtools/devtools-backend/include/api/adapter/data/serializable.h, devtools/devtools-backend/include/tunnel/tcp/frame_codec.h, devtools/devtools-backend/include/tunnel/ws/web_socket_channel.h, dom/include/dom/animation/animation.h, dom/include/dom/animation/cubic_bezier_animation.h, dom/src/dom/animation/animation.cc, dom/src/dom/animation/cubic_bezier_animation.cc, driver/js/core/include/core/runtime/v8/bridge.h, layout/engine/HPStyle.cpp, layout/engine/HPStyle.h, modules/footstone/src/deserializer.cc
change compiler options based on LLVM 12
and fix related code issues
=> feat(android): change compiler options based on LLVM 12

dom/src/dom/dom_argument.cc
=> feat(dom): support std::any_cast in version below ios 11

docs/en-us/style/appearance.md, docs/style/appearance.md, examples/hippy-vue-demo/src/components/demos/demo-p.vue
=> docs(appearance): add fontStyle docs

ios/sdk/base/HippyModuleMethod.mm
=> fix(ios): fix memory leaks for block usage

driver/js/core/include/core/napi/js_native_api_types.h, driver/js/core/include/core/napi/jsc/js_native_api_jsc.h, driver/js/core/include/core/napi/v8/js_native_api_v8.h, driver/js/core/src/napi/jsc/js_native_api_jsc.cc, driver/js/core/src/napi/jsc/js_native_api_value_jsc.cc, driver/js/core/src/napi/v8/js_native_api_v8.cc, driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/ios/base/executors/HippyJSCExecutor.h, driver/js/ios/base/executors/HippyJSCExecutor.mm, driver/js/ios/module/turbo/HippyOCTurboModule.mm, driver/js/ios/utils/NSObject+ToJSCtxValue.h, driver/js/ios/utils/NSObject+ToJSCtxValue.mm
=> refactor(ios): change jscontext invoke style from oc style to c style

driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/core/include/core/runtime/v8/v8_bridge_utils.h, driver/js/core/src/runtime/v8/v8_bridge_utils.cc
=> fix(core): fix destroy callback bug

driver/js/flutter/example/lib/main.dart, driver/js/flutter/example/lib/page_test.dart, driver/js/flutter/lib/adapter/third_party.dart, driver/js/flutter/lib/bridge/voltron_bridge.dart, driver/js/flutter/lib/engine.dart, driver/js/flutter/lib/engine/engine_define.dart, driver/js/flutter/lib/engine/js_engine_context.dart, driver/js/flutter/lib/engine/js_instance_context.dart, driver/js/flutter/lib/engine/voltron_js_engine.dart, driver/js/flutter/lib/inspector.dart, driver/js/flutter/lib/inspector/dev.dart, driver/js/flutter/lib/inspector/dev_server_callback.dart, driver/js/flutter/lib/inspector/dev_server_impl.dart, driver/js/flutter/lib/inspector/dev_server_impl_disable.dart, driver/js/flutter/lib/inspector/dev_server_interface.dart, renderer/flutter/lib/controller/controller.dart, renderer/flutter/lib/controller/list.dart, renderer/flutter/lib/controller/waterfall.dart, renderer/flutter/lib/gesture/scroll.dart, renderer/flutter/lib/style/prop.dart, renderer/flutter/lib/viewmodel/scroller.dart, renderer/flutter/lib/viewmodel/view_model.dart, renderer/flutter/lib/viewmodel/waterfall.dart, renderer/flutter/lib/widget/div.dart, renderer/flutter/lib/widget/root.dart
=> feat(voltron): add DevSupportManager

.github/CODEOWNERS
=> ci(codeowners): add *.cmake codeowners

.github/workflows/3rd_prebuilt_v8.yml
=> ci(workflows): `V8` prebuilt artifacts support iOS platform

android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java
=> fix(android): set default background color to TRANSPARENT

ios/sdk/debug/websocket/HippySRWebSocket.m
=> fix(devtools): disconnect ws when close

.github/workflows/3rd_prebuilt_v8.yml
=> ci(workflows): update v8 prebuilt script to support linux platform

driver/js/core/include/core/napi/js_native_api_types.h, driver/js/core/include/core/napi/jsc/js_native_api_jsc.h, driver/js/core/include/core/napi/v8/js_native_api_v8.h, driver/js/core/src/napi/jsc/js_native_api_jsc.cc, driver/js/core/src/napi/jsc/js_native_api_value_jsc.cc, driver/js/core/src/napi/v8/js_native_api_v8.cc, driver/js/ios/utils/NSObject+ToJSCtxValue.h, driver/js/ios/utils/NSObject+ToJSCtxValue.mm, renderer/native/ios/utils/NativeRenderConvert.mm
=> feat(ios): support bytes buffer transfer

ios/sdk/component/image/HippyImageView.h, ios/sdk/component/image/HippyImageView.m
=> feat(ios): ios image async

ios/sdk/component/listview/HippyBaseListView.m
=> fix(ios): no more ceiling item height

modules/android/jni/CMakeLists.txt, modules/android/jni/src/jni_env.cc, modules/android/jni/src/jni_register.cc, modules/android/jni/src/jni_utils.cc, modules/android/jni/src/scoped_java_ref.cc
=> feat(jni): use the project root as the include headers search path

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/InspectorDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/domain/PageDomain.java, android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/CSSModel.java
=> fix(devtools): fix elements reload and update bug

ios/sdk/component/view/HippyView.h, ios/sdk/component/view/HippyView.m
=> feat(ios): allows the access party to customize filter attributes

.github/workflows/android_build_tests.yml, android/sdk/gradle.properties
=> feat(android): specify the `V8` version used

renderer/native/ios/renderer/component/view/NativeRenderView.h, renderer/native/ios/renderer/component/view/NativeRenderView.mm
=> feat(ios): set magnificationFilter as kCAFilterNearest by default

.github/workflows/3rd_prebuilt_v8.yml, android/sdk/gradle.properties
=> feat(android): modify the V8_COMPONENT to specify the V8 version

ios/sdk/module/animation/HippyExtAnimation.m
=> feat(ios): support skew animation

android/sdk/src/main/jni/include/inspector/v8_inspector_client_impl.h
=> feat(android): remove useless override method

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java
=> fix(android): check collapsable at attribute

driver/js/examples/hippy-vue-demo/src/app.vue, driver/js/packages/hippy-react/src/components/scroll-view.tsx, driver/js/packages/hippy-vue/src/renderer/element-node.js
=> feat(hippy-vue): support breakStrategy

ios/sdk/base/executors/HippyJSCExecutor.mm
a block executed in js thread may cause another block action executed in
js thread synchronously, which will cause a dead lock
=> fix(ios): fix a dead lock

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
=> fix(android): call function callback reuse

docs/en-us/hippy-react/modules.md, docs/en-us/hippy-vue/external-components.md, docs/hippy-react/modules.md, docs/hippy-vue/external-components.md
=> docs(homepage): remove skew intro

ios/sdk/utils/HippyUtils.m
=> feat(ios): add method to get key window in ios13

dom/CMakeLists.txt, dom/include/dom/dom_node.h, dom/include/dom/tools/tools.h, dom/src/dom/dom_node.cc, dom/src/dom/tools/tools.cc, modules/footstone/src/hippy_value.cc
=> feat(dom): add tools for log dominfo

ios/sdk/component/view/HippyShadowView.mm, ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): roottag property should not be updated

renderer/native/ios/renderer/component/scrollview/NativeRenderScrollView.mm
=> fix(ios): try to avoid cases where result is NAN

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/ContentDrawable.java
=> fix(image): fix image border path not reset

ios/sdk/component/waterfalllist/HippyReusableNodeCache.m, ios/sdk/component/waterfalllist/HippyWaterfallView.m
=> fix(ios): fix a potential null pointer when waterfallview cell resuse

dom/src/dom/dom_node.cc
=> fix(dom): fix on layout event execution time

ios/sdk/component/image/HippyImageView.m
=> fix(ios): radius must be smaller than half of component's length

renderer/native/android/src/main/jni/include/render/native_render_manager.h, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> fix(render_manager): fix render manager measure function error

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): nested listview may not get rendered

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java
=> fix(android): listview can not scroll inside other listview

driver/js/android/src/main/jni/src/bridge/java2js.cc, driver/js/core/CMakeLists.txt, driver/js/core/include/core/runtime/v8/inspector/v8_inspector_client_impl.h, driver/js/core/include/core/runtime/v8/interrupt_queue.h, driver/js/core/include/core/runtime/v8/v8_bridge_utils.h, driver/js/core/src/runtime/v8/inspector/v8_inspector_client_impl.cc, driver/js/core/src/runtime/v8/interrupt_queue.cc, driver/js/core/src/runtime/v8/v8_bridge_utils.cc, modules/footstone/src/task_runner.cc
=> feat(core): ability to breakpoint when v8 is running long js code

ios/sdk/component/view/HippyViewManager.mm
=> fix(ios): direction is for shadow view ,not view

renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm
=> fix(ios): fix some properties setting error for view

driver/js/core/include/core/napi/js_native_api_types.h, driver/js/core/include/core/napi/jsc/js_native_api_jsc.h, driver/js/core/include/core/napi/v8/js_native_api_v8.h, driver/js/core/src/napi/jsc/js_native_api_value_jsc.cc, driver/js/core/src/napi/v8/js_native_api_v8.cc, driver/js/ios/utils/NSObject+ToJSCtxValue.mm
=> fix(ios): compatible with x5 & lower version of v8 api

dom/src/dom/dom_node.cc
=> fix(dom): fix problem of early return

driver/js/ios/base/executors/HippyJSExecutor.mm
=> fix(ios): scope shouldn't be null before set name

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java
=> fix(android): horizontal `ScrollView` cannot scroll in other scrollable

.github/license-check.json, .github/workflows/gh_licence_checks.yml, .github/workflows/gh_licence_checks_bypass.yml
=> ci(license): add license checker

README.md, docs/android/integration.md, docs/en-us/android/integration.md
=> docs(homepage,readme): change integration introduction

ios/sdk/base/HippyBatchedBridge.mm
HippyDevLoadingView should not be showed in release environment
=> fix(ios): fix HippyDevLoadingView shows in release environment

.github/workflows/security_codeql_analyses.yml
=> feat(workflows): CodeQL analysis runs at every night

packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/runtime/modules/style.js, packages/hippy-vue/src/util/index.js
=> fix(vue): fix static style not updated in some case

.github/workflows/security_codeql_analyses.yml
=> fix(workflows): CodeQL analysis checkout using LFS

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, examples/ios-demo/HippyDemo.xcodeproj/xcshareddata/xcschemes/HippyDemo.xcscheme
=> chore(ios): modify project macros

layout/engine/HPUtil.cpp, layout/engine/HPUtil.h
=> fix(layout): improve the accuracy of the layout engine

docker/android-release/Dockerfile, docker/linux-release/Dockerfile
=> chore(docker): add `pip3` package installer for Python3

.github/workflows/project_artifact_release.yml
=> feat(workflows): artifact release action always compress symbols

layout/engine/HPUtil.cpp
=> fix(layout): increase delta for double data comparisons

dom/src/dom/dom_node.cc
=> fix(dom): fix the condition for weather the layout change

docs/_navbar.md, docs/en-us/_navbar.md
=> docs(homepage): fix homepage skip url

docs/en-us/guide/dynamic-import.md, docs/en-us/hippy-react/modules.md, docs/en-us/hippy-react/web.md, docs/guide/dynamic-import.md, docs/hippy-react/modules.md, docs/hippy-react/web.md
=> docs(homepage): fix syntax error

ios/sdk/base/HippyBridge+Mtt.mm
=> fix(ios): set thread priority explictly to avoid priority revertion

examples/ios-demo/HippyDemo/turbomodule/TurboBaseModule.mm, ios/sdk/base/HippyBridge+Private.h, ios/sdk/base/HippyBridge.h, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyFont.mm
=> chore(ios): eliminate some warnings

.github/ISSUE_TEMPLATE/crash_report.yml, .github/workflows/gh_issue_crash_report.yml
=> chore(github): added templates for crash report issue and it's bot

examples/hippy-react-demo/src/components/Text/index.jsx, ios/sdk/component/text/HippyShadowText.mm
=> fix(ios): padding not working on text's subview

android/sdk/src/main/jni/CMakeLists.txt
=> fix(android): fix LLVM linker version script not taking effect

core/include/core/base/string_view_utils.h, core/third_party/base/include/base/logging.h
=> feat(android): remove implicit conversion

ios/sdk/component/refresh/HippyRefresh.m
=> fix(ios): fix refresh component bug

renderer/native/ios/renderer/component/textinput/NativeRenderTextField.mm
=> fix(ios): hippy-vue textInput isFocused not working

driver/js/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, driver/js/android/src/main/jni/include/bridge/entry.h, driver/js/android/src/main/jni/src/bridge/entry.cc, driver/js/core/include/core/scope.h, driver/js/core/src/runtime/v8/v8_bridge_utils.cc, driver/js/core/src/scope.cc, driver/js/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, driver/js/examples/ios-demo/HippyDemo/ViewController.mm, driver/js/flutter/core/src/bridge/ios/bridge_impl_ios.h, driver/js/flutter/core/src/bridge/ios/bridge_impl_ios.mm, driver/js/ios/base/HippyRootView.mm, driver/js/ios/module/rootview/HippyRootViewManager.h, driver/js/ios/module/rootview/HippyRootViewManager.mm, renderer/native/ios/renderer/NativeRenderContext.h, renderer/native/ios/renderer/NativeRenderImpl.mm
=> unloadinstance

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextView.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextViewController.java, renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java
=> fix(android): set mGestureEnable to component

.github/workflows/frontend_build_tests.yml, .github/workflows/frontend_build_tests_bypass.yml, docs/README.md, docs/en-us/README.md
=> docs(homepage): update business info

docker/android-release/Dockerfile
=> chore(docker): update NDK and CMake versions

.github/workflows/3rd_prebuilt_v8.yml
=> refactor(workflows): refactor v8 build script

ios/sdk/component/scrollview/HippyScrollView.m
=> fix(ios): fix scroll rtl for content view

renderer/native/ios/renderer/component/scrollview/NativeRenderScrollView.mm
=> fix(ios): fix scroll content view rtl

.github/labeler.yml, .github/workflows/3rd_prebuilt_v8.yml, .github/workflows/hip_archive_artifact.yml, .github/workflows/hip_info_artifacts.yml, .github/workflows/project_artifact_release.yml
=> chore(ci): fix some syntax warnings

docs/en-us/web/custom-component.md, docs/en-us/web/custom-module.md, docs/en-us/web/event.md, docs/en-us/web/integration.md
=> docs(en-us/web): provides English translation for web-related docs

framework/android/src/main/cpp/include/bridge/bridge.h, framework/android/src/main/cpp/include/bridge/entry.h, framework/android/src/main/cpp/include/bridge/java2js.h, framework/android/src/main/cpp/include/bridge/js2java.h, framework/android/src/main/cpp/include/jni/convert_utils.h, framework/android/src/main/cpp/include/jni/exception_handler.h, framework/android/src/main/cpp/include/jni/java_turbo_module.h, framework/android/src/main/cpp/include/jni/turbo_module_manager.h, framework/android/src/main/cpp/include/jni/turbo_module_runtime.h, framework/android/src/main/cpp/include/jni/uri.h, framework/android/src/main/cpp/include/loader/adr_loader.h, framework/android/src/main/cpp/src/bridge/entry.cc, framework/android/src/main/cpp/src/bridge/java2js.cc, framework/android/src/main/cpp/src/bridge/js2java.cc, framework/android/src/main/cpp/src/jni/convert_utils.cc, framework/android/src/main/cpp/src/jni/exception_handler.cc, framework/android/src/main/cpp/src/jni/java_turbo_module.cc, framework/android/src/main/cpp/src/jni/turbo_module_manager.cc, framework/android/src/main/cpp/src/jni/uri.cc, framework/android/src/main/cpp/src/loader/adr_loader.cc
=> feat(framework): adjust the framework module namespace

framework/android/src/main/cpp/src/bridge/entry.cc, modules/android/jni/include/jni/jni_env.h, modules/android/jni/include/jni/jni_register.h, modules/android/jni/include/jni/jni_utils.h, modules/android/jni/include/jni/scoped_java_ref.h, modules/android/jni/src/jni_env.cc, modules/android/jni/src/jni_register.cc, modules/android/jni/src/jni_utils.cc, modules/android/jni/src/scoped_java_ref.cc, renderer/native/android/src/main/jni/src/render/native_render_jni.cc
=> feat(framework): adjust the jni module namespace

core/include/core/engine.h, examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> fix(devtools): remove v8 inspector flag for ios

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, docs/en-us/style/appearance.md, docs/style/appearance.md
=> feat(android): add `visibility` style

framework/android/src/main/cpp/src/bridge/entry.cc, renderer/native/android/src/main/jni/include/render/native_render_jni.h, renderer/native/android/src/main/jni/include/render/native_render_manager.h, renderer/native/android/src/main/jni/src/render/native_render_jni.cc, renderer/native/android/src/main/jni/src/render/native_render_manager.cc
=> feat(native_render): add namespace for native render

docs/en-us/index.html, docs/index.html
=> fix(homepage): fix secure problem for homepage redirect

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/netinfo/NetInfoModule.java
=> fix(android): add try-catch for NetInfoModule

android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/ContentDrawable.java
=> fix(android): gif borderRadius not working and radius scale issue

driver/js/include/driver/base/file.h, driver/js/include/driver/napi/jsc/js_native_api_jsc.h, driver/js/src/base/file.cc, driver/js/src/devtools/devtools_data_source.cc, driver/js/src/modules/animation_module.cc, driver/js/src/modules/console_module.cc, driver/js/src/modules/contextify_module.cc, driver/js/src/modules/scene_builder.cc, driver/js/src/napi/jsc/js_native_api_jsc.cc, driver/js/src/napi/jsc/js_native_api_value_jsc.cc, driver/js/src/napi/v8/js_native_api_v8.cc, driver/js/src/runtime/v8/v8_bridge_utils.cc, driver/js/src/scope.cc, framework/android/src/main/cpp/include/loader/adr_loader.h, framework/android/src/main/cpp/src/jni/convert_utils.cc, framework/android/src/main/cpp/src/jni/java_turbo_module.cc, framework/android/src/main/cpp/src/jni/turbo_module_manager.cc, framework/ios/base/executors/HippyJSExecutor.mm, framework/ios/module/turbo/HippyOCTurboModule.mm, framework/ios/utils/NSObject+ToJSCtxValue.mm, modules/android/jni/src/jni_utils.cc, modules/footstone/include/footstone/string_view_utils.h, modules/footstone/src/deserializer.cc
=> feat(driver): refactor ToConstCharPointer function

dom/include/dom/render_manager.h, dom/src/dom/layer_optimized_render_manager.cc, renderer/flutter/core/src/render/queue/voltron_render_manager.cc, renderer/native/android/src/main/jni/include/render/native_render_manager.h, renderer/native/android/src/main/jni/src/render/native_render_manager.cc, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm
=> feat(render): add render manager name

driver/js/packages/hippy-react/src/index.ts, driver/js/packages/hippy-react/src/modules/animation-set.ts, driver/js/packages/hippy-react/src/modules/animation.ts
=> refactor(hippy-react): remove rn related apis

packages/hippy-react/src/dom/element-node.ts, packages/hippy-vue-css-loader/src/css-parser.js, packages/hippy-vue/src/renderer/element-node.js
=> fix(vue): fix regular expressions catastrophic backtracking

packages/hippy-vue-css-loader/src/css-parser.js
=> fix(vue): revert a catastrophic backtracking fix

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): turbo runtime must release in js thread

android/sdk/src/main/java/com/tencent/mtt/hippy/v8/V8.java, android/sdk/src/main/java/com/tencent/mtt/hippy/v8/memory/V8Memory.java, android/sdk/src/main/jni/include/bridge/runtime.h, android/sdk/src/main/jni/include/performance/memory.h, android/sdk/src/main/jni/src/bridge/entry.cc, android/sdk/src/main/jni/src/performance/memory.cc
=> fix(core): compatible with lower version v8 for memory feature

.github/workflows/android_build_tests.yml, .github/workflows/gh_issue_crash_report.yml, .github/workflows/gh_mark_and_close_stalled.yml, .github/workflows/gh_pr_checks_approval.yml, .github/workflows/security_codeql_analyses.yml
=> ci(workflows): use installation access token provided by the Github App

packages/hippy-react/src/components/list-view.tsx
=> fix(hippy-react): add overflow scroll to fix listview unable to scroll

framework/ios/base/executors/HippyJSExecutor.mm
=> fix(ios): fix vfs callback error

.github/CODEOWNERS
=> ci(codeowner): add code owner for android

.github/workflows/hip_archive_artifact.yml
=> ci(workflows): support writing mode options

.github/workflows/android_build_tests.yml, .github/workflows/docker_build_image.yml, .github/workflows/gh_issue_crash_report.yml, .github/workflows/gh_pr_checks_approval.yml, .github/workflows/gh_pr_labeler.yml, .github/workflows/security_codeql_analyses.yml
=> ci(workflows): adjust workflow configs to run on forks

renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/TextDrawable.java
=> fix(android): text align center

hippy.podspec
=> chore(ios): ios project must exclude inspector files

.eslintrc.js, docs/en-us/guide/debug.md, docs/en-us/hippy-vue/native-event.md, docs/guide/debug.md, packages/hippy-react-web/src/components/web-view.tsx, packages/hippy-react/src/components/image.tsx, packages/hippy-react/src/components/refresh-wrapper.tsx, packages/hippy-react/src/renderer/render.ts, packages/hippy-react/src/utils/index.ts, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/event/emitter.js, packages/hippy-vue/src/renderer/native/style/index.js, packages/hippy-vue/src/runtime/index.js, packages/hippy-vue/src/util/index.js
=> refactor(react,vue): fix lint issue & perf code

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderNode.java
=> fix(android): should set FLAG_UPDATE_TOTAL_PROPS in create node

driver/js/include/driver/napi/js_native_api_types.h, driver/js/include/driver/napi/jsc/js_native_api_jsc.h, driver/js/include/driver/napi/v8/js_native_api_v8.h, driver/js/src/napi/v8/js_native_api_v8.cc, modules/footstone/include/footstone/macros.h
=> fix(driver): fix memory leak

driver/js/include/driver/modules/event_module.h, driver/js/include/driver/napi/js_native_api_types.h, driver/js/include/driver/napi/jsc/js_native_api_jsc.h, driver/js/include/driver/napi/v8/js_native_api_v8.h, driver/js/include/driver/scope.h, driver/js/src/modules/event_module.cc, driver/js/src/napi/jsc/js_native_api_jsc.cc, driver/js/src/napi/v8/js_native_api_v8.cc, driver/js/src/scope.cc
=> feat(driver): rename RegisterDomEvent function name

modules/footstone/include/footstone/driver.h, modules/footstone/src/cv_driver.cc, modules/footstone/src/platform/adr/looper_driver.cc, modules/footstone/src/platform/ios/looper_driver.cc, modules/footstone/src/worker.cc
=> fix(footstone): fix infinite loop bug for iOS looper

modules/footstone/include/footstone/platform/adr/looper_driver.h, modules/footstone/include/footstone/platform/ios/looper_driver.h, modules/footstone/src/platform/adr/looper_driver.cc, modules/footstone/src/platform/ios/looper_driver.cc
=> feat(footstone): refactor driver

ios/sdk/base/HippyTouchHandler.m, ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): fix touch gesture no touch.view

examples/hippy-vue-demo/src/app.vue, examples/hippy-vue-demo/src/components/native-demos/demo-pull-header-footer.vue, examples/hippy-vue-demo/src/components/native-demos/demo-waterfall.vue, examples/hippy-vue-demo/src/main-native.js, packages/hippy-vue-loader/lib/loaders/pitcher.js, packages/hippy-vue/src/index.js, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/native/style/css-selectors-match.js, packages/hippy-vue/src/renderer/native/style/css-selectors.js, packages/hippy-vue/src/renderer/native/style/index.js, packages/hippy-vue/src/util/index.js
=> feat(vue): support scoped & attribute selector

docs/en-us/guide/debug.md, docs/en-us/guide/integration.md, docs/en-us/web/integration.md, docs/guide/debug.md, docs/guide/integration.md, docs/web/integration.md, examples/hippy-react-demo/package.json, examples/hippy-vue-demo/package.json
=> fix(debug-server): fix wepback & node md4 hash not campatible

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
=> fix(android): empty text node height compatibility

ios/sdk/component/listview/HippyBaseListViewCell.m
=> fix(ios): needs to reset showing state when cell prepares for reusing

driver/js/src/napi/jsc/js_native_api_jsc.cc, framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/examples/ios-demo/HippyDemo/TestModule.mm, framework/examples/ios-demo/HippyDemo/ViewController.mm, framework/ios/base/HippyBridge.h, framework/ios/base/HippyBridge.mm, framework/ios/base/HippyBridgeDelegate.h, framework/ios/base/HippyDeviceBaseInfo.mm, framework/ios/base/bundleoperations/HippyBundleDownloadOperation.mm, framework/ios/base/engine_wrapper/HippyContextWrapper.h, framework/ios/base/engine_wrapper/jsc/HippyJSCContextWrapper.h, framework/ios/base/engine_wrapper/jsc/HippyJSCContextWrapper.mm, framework/ios/base/engine_wrapper/v8/HippyV8ContextWrapper.h, framework/ios/base/engine_wrapper/v8/HippyV8ContextWrapper.mm, framework/ios/base/executors/HippyJSExecutor.h, framework/ios/base/executors/HippyJSExecutor.mm, framework/ios/module/turbo/HippyTurboModuleManager.mm, framework/ios/utils/NSObject+CtxValue.h, framework/ios/utils/NSObject+CtxValue.mm, framework/ios/utils/jsc/NSObject+JSValue.h, framework/ios/utils/jsc/NSObject+JSValue.m, framework/ios/utils/v8/NSObject+V8Value.h, framework/ios/utils/v8/NSObject+V8Value.mm
=> feat(ios): reduce data conversion for js engine

framework/android/src/main/cpp/include/bridge/entry.h, framework/android/src/main/cpp/src/bridge/entry.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java, framework/android/src/main/java/com/tencent/mtt/hippy/bridge/libraryloader/LibraryLoader.java, framework/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java, layout/android/java/com/tencent/smtt/flexbox/FlexNode.java
=> feat(android): print log with log level

.github/workflows/3rd_prebuilt_v8.yml
=> fix(workflows): fix workflow file syntax exception

ios/sdk/module/network/HippyNetWork.m
=> fix(ios): fix memory leaks in network module

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java, renderer/native/android/src/main/java/com/tencent/renderer/component/ComponentController.java, renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/BackgroundDrawable.java
=> feat(android): support draw border with dash effect

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java, docs/en-us/hippy-react/components.md, docs/en-us/hippy-vue/external-components.md, docs/hippy-react/components.md, docs/hippy-vue/external-components.md
=> fix(docs, android): `expandPullHeader` method for `ListView`

driver/js/include/driver/napi/js_native_api_types.h, driver/js/include/driver/napi/jsc/js_native_api_jsc.h, driver/js/include/driver/napi/v8/js_native_api_v8.h, driver/js/src/napi/jsc/js_native_api_value_jsc.cc, driver/js/src/napi/v8/js_native_api_v8.cc, framework/ios/utils/NSObject+CtxValue.mm, framework/ios/utils/v8/NSObject+V8Value.mm
=> fix(ios): fix array buffer data owner error

packages/hippy-vue/src/renderer/native/components.js, packages/hippy-vue/src/renderer/native/event/emitter.js, packages/hippy-vue/src/renderer/native/event/event.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/view-node.js, packages/hippy-vue/src/runtime/directives/model.js, packages/hippy-vue/src/runtime/directives/show.js, packages/hippy-vue/src/runtime/index.js, packages/hippy-vue/src/runtime/modules/style.js, packages/hippy-vue/src/runtime/netInfo.js
=> refactor(vue): perf vue code

android/sdk/gradle.properties, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/serialization/delegate/DeserializerDelegate.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/serialization/delegate/SerializerDelegate.java, android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/serialization/delegate/SerializerDelegateHost.java, android/sdk/src/main/java/com/tencent/mtt/hippy/runtime/builtins/JSDataView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/ArrayBufferViewTag.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/ErrorTag.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueDeserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/SerializationTag.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/SharedSerialization.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/compatible/Deserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/compatible/Serializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Deserializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/Serializer.java, android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/recommend/SharedValueConveyor.java, android/sdk/src/main/jni/CMakeLists.txt, core/CMakeLists.txt, core/include/core/inspector/v8_inspector_client_impl.h, core/src/inspector/v8_inspector_client_impl.cc
* feat(android): support v8 version to 10.6.194
* feat(android): update to use C++17 standard
* feat(android): serialization support version 15 data
serialization support version 15 data and
decouples related types and their dependencies.
=> feat(android): support v8 version to 10.6.194

build.gradle, framework/android/build.gradle, framework/examples/android-demo/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, modules/android/hippy_support/build.gradle, modules/android/link_supplier/build.gradle, modules/android/serialization/build.gradle, renderer/native/android/build.gradle
=> refactor(android): update gradle to 7.3.0

android/sdk/build.gradle
=> fix(android): prevent `LIBRARY_VERSION` inlining

ios/sdk/component/scrollview/HippyScrollViewManager.mm
=> fix(ios): scrollview: scrollToWithDuration not trigger OnScroll

android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/ViewPagerPageChangeListener.java
=> fix(android): `onPageScroll` event gives wrong value

hippy.podspec
=> chore(ios): set podspec version to 2.0.0 for master branch

hippy.podspec
=> chore(ios): set podspec version to 3.0.0 for v3.0-dev branch

packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/renderer/native/style/__tests__/index.test.js, packages/hippy-vue/src/renderer/native/style/__tests__/parser.test.js, packages/hippy-vue/src/runtime/native.js, packages/hippy-vue/src/util/node.js
=> feat(vue): add getElemCss scoped judgement

android/sdk/src/main/java/com/tencent/mtt/hippy/views/webview/HippyWebView.java
=> fix(android): WebView backgroundColor not working

ios/sdk/utils/HippyUtils.m
=> fix(ios): add assert for url creation failure

packages/hippy-vue-next/src/util/index.ts, packages/hippy-vue/src/util/node.js
=> chore(eslint): disable no-param-reassign

docs/android/v8-api.md, docs/en-us/android/v8-api.md
(cherry picked from commit 084c1c2671d0d77fd10ddeb63f76eabf8bf6a9bf)
=> docs(homepage): update v8 api documentation

packages/hippy-vue/src/runtime/native.js
=> refactor(vue): change AsyncStorage to global.Hippy.asyncStorage

.editorconfig, driver/js/examples/hippy-react-demo/src/components/Text/index.jsx, renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVirtualNode.java, renderer/native/android/src/main/java/com/tencent/renderer/component/text/VirtualNode.java, renderer/native/ios/renderer/component/textinput/NativeRenderTextViewManager.mm
- add breakStrategy prop for Text and TextInput
- add isFocused method for TextInput
- add ellipsizeMode prop support for Text componment
=> feat(android): add `Text` and `TextInput` features from 2.0

docs/en-us/hippy-react/native-event.md, docs/hippy-react/native-event.md, driver/js/packages/hippy-react/src/event/global-listener.ts, driver/js/packages/hippy-react/src/event/index.ts, driver/js/packages/hippy-react/src/index.ts
=> refactor(react): change HippyEvent name to EventBus

scripts/build-example.js, scripts/debug-example.js, scripts/init-example.js
=> fix(script): fix build script error

framework/ios/base/executors/HippyJSExecutor.mm
=> fix(ios): pending calls should be invoked after scope initialized

driver/js/examples/hippy-react-demo/src/components/PullHeaderFooter/index.jsx, driver/js/examples/hippy-vue-demo/src/components/native-demos/demo-pull-header-footer.vue, renderer/native/ios/renderer/component/headerrefresh/NativeRenderHeaderRefresh.mm, renderer/native/ios/renderer/component/viewPager/NativeRenderViewPager.mm, renderer/native/ios/utils/OCTypeToDomArgument.mm
=> feat(ios): listview stick cell wrong offset while refreshing

driver/js/include/driver/napi/js_native_api_types.h, driver/js/include/driver/napi/js_native_turbo.h, driver/js/src/napi/jsc/js_native_turbo_jsc.cc, driver/js/src/napi/v8/js_native_turbo_v8.cc, framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/examples/ios-demo/HippyDemo/turbomodule/TurboConfig.h, framework/ios/base/bridge/HippyBridge.mm, framework/ios/base/executors/HippyJSExecutor.mm, framework/ios/base/modules/HippyModuleMethod.mm, framework/ios/module/turbo/HippyOCTurboModule+Inner.h, framework/ios/module/turbo/HippyOCTurboModule.mm, framework/ios/module/turbo/HippyTurboModuleManager.h, framework/ios/module/turbo/HippyTurboModuleManager.mm, framework/ios/module/turbo/NSObject+HippyTurbo.mm
=> feat(ios): use napi for turbo module

hippy.podspec, ios/sdk/component/viewPager/HippyViewPager.m
=> fix(ios): no animation for frame reset

framework/android/src/main/cpp/include/bridge/entry.h, framework/android/src/main/cpp/src/bridge/entry.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, modules/vfs/android/src/main/java/com/tencent/vfs/VfsManager.java
=> refactor(android): change onCreateVfs definition

dom/include/dom/dom_node.h, dom/src/dom/animation/animation_manager.cc, dom/src/dom/dom_node.cc
=> fix(animation): fix property diff bug when animation is updating

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): virtual nodes need to be flushed

dom/src/dom/taitank_layout_node.cc
=> fix(dom): set default value to layout node

docs/en-us/guide/debug.md, docs/en-us/guide/integration.md, docs/en-us/web/integration.md, docs/guide/debug.md, docs/guide/integration.md, docs/web/integration.md, examples/hippy-react-demo/package.json, examples/hippy-react-demo/scripts/env-polyfill.js, examples/hippy-react-demo/scripts/hippy-webpack.web-renderer.js, examples/hippy-vue-demo/package.json, examples/hippy-vue-demo/scripts/env-polyfill.js, examples/hippy-vue-next-demo/package.json, examples/hippy-vue-next-demo/scripts/env-polyfill.js, examples/hippy-vue-next-demo/src/main-web.ts
=> refactor(demo): fix demo script not compatible

ios/sdk/component/image/HippyImageView.m
=> fix(ios): fix image view dangling pointer

.github/CODEOWNERS
=> ci(codeowner): add gradle related codeowner

ios/sdk/component/image/HippyImageView.m
=> fix(ios): avoid a thread race for image component

framework/android/src/main/cpp/src/bridge/entry.cc, modules/vfs/android/src/main/cpp/include/vfs/handler/jni_delegate_handler.h, modules/vfs/android/src/main/cpp/src/handler/jni_delegate_handler.cc
=> fix(vfs): fix vfs crash

docs/en-us/hippy-vue/style.md, docs/hippy-vue/style.md, examples/hippy-vue-demo/src/app.vue, examples/hippy-vue-demo/src/components/native-demos/demo-pull-header-footer.vue, examples/hippy-vue-demo/src/components/native-demos/demo-waterfall.vue, examples/hippy-vue-next-demo/src/app.vue, examples/hippy-vue-next-demo/src/components/native-demo/demo-pull-header-footer.vue, examples/hippy-vue-next-demo/src/components/native-demo/demo-swiper.vue, examples/hippy-vue-next-demo/src/components/native-demo/demo-waterfall.vue, packages/hippy-vue-next/src/runtime/element/hippy-element.ts, packages/hippy-vue-next/src/runtime/style/css-selectors.ts, packages/hippy-vue-next/src/util/index.ts, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/style/css-selectors.js, packages/hippy-vue/src/util/node.js
=> feat(vue): fix attribute selector & support deep selector

ios/sdk/module/netinfo/HippyNetInfoIntenal.h, ios/sdk/module/netinfo/HippyNetInfoIntenal.m
=> fix(ios): avoid CTTelephony's occasional  crash

packages/hippy-react/src/components/list-view.tsx
=> perf(react): assign initialListSize if not undefined

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java
=> fix(android): sticky item has incorrect height after refresh

framework/voltron/core/src/bridge/ios/VoltronFlutterBridge.mm, framework/voltron/lib/adapter/http.dart, framework/voltron/lib/channel/platform_manager.dart
=> feat(voltron): perfect voltron user agent

driver/js/src/napi/v8/js_native_api_v8.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyResourceLoader.java, framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java, framework/examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java, modules/vfs/android/src/main/cpp/src/handler/jni_delegate_handler.cc, modules/vfs/android/src/main/java/com/tencent/vfs/ResourceDataHolder.java, modules/vfs/android/src/main/java/com/tencent/vfs/VfsManager.java, modules/vfs/native/src/uri_loader.cc
=> feat(android): vfs support sync http

modules/vfs/android/src/main/cpp/src/handler/jni_delegate_handler.cc, modules/vfs/native/src/uri_loader.cc
=> feat(vfs): add vfs  check

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/clipboard/ClipboardModule.java
=> fix(android): remove redundant getPrimaryClip

framework/ios/base/bundleoperations/HippyBundleOperationQueue.m, hippy.podspec
=> chore(ios): modify podspec file for module

framework/examples/ios-demo/HippyDemo/ViewController.mm
=> feat(ios): add example for removing hippy root view

framework/ios/base/bridge/HippyBridge.mm
=> fix(iOS): retain cycle with vc and bridge

renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/TextDrawable.java
=> fix(android): textAlign should not affect vertically

.editorconfig, android/sdk/src/main/java/androidx/recyclerview/widget/HippyLinearLayoutManager.java, android/sdk/src/main/java/androidx/recyclerview/widget/HippyRecyclerViewBase.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullFooterRefreshHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullRefreshHelper.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java
=> refactor(android): pull header and footer of `ListView`

framework/examples/ios-demo/HippyDemo/ViewController.mm
=> fix(ios): fix fix demo memory leaks issue

examples/ios-demo/HippyDemo/turbomodule/TurboConfig.m, ios/sdk/module/turbo/HippyOCTurboModule.mm
=> fix(iOS): jsi convert Chinese string error

modules/vfs/native/include/vfs/uri_loader.h
=> fix(vfs): fix weak_from_this error

android/sdk/src/main/java/androidx/recyclerview/widget/HippyLinearLayoutManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java
=> fix(android): pull header not showing for horizontal list

core/include/core/base/file.h, core/src/base/file.cc, core/src/modules/contextify_module.cc, core/src/napi/jsc/js_native_api_value_jsc.cc, core/src/scope.cc, examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, ios/sdk/base/HippyBridge.mm, ios/sdk/base/HippyDisplayLink.m, ios/sdk/base/HippyModuleMethod.mm, ios/sdk/component/image/HippyImageView.m, ios/sdk/component/modal/HippyModalHostView.m, ios/sdk/component/view/HippyView.m
=> refactor(ios): adapate cxx20 for ios demo

.github/workflows/project_artifact_compare.yml
=> ci(workflows): add github actions for project artifact compare

framework/examples/ios-demo/HippyDemo/ViewController.mm, framework/ios/base/bridge/HippyBridge.mm, framework/ios/base/bridge/HippyBridgeDelegate.h, framework/ios/base/executors/HippyJSExecutor.mm, renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
=> fix(ios): fix reload crash bug

framework/examples/ios-demo/HippyDemo/ViewController.mm
=> fix(ios): remove test code

docs/en-us/hippy-vue/style.md, docs/hippy-vue/style.md, examples/hippy-vue-demo/src/components/demos/demo-dynamicimport.vue, examples/hippy-vue-demo/src/components/demos/dynamicImport/async-component-local.vue, examples/hippy-vue-next-demo/src/components/demo/demo-dynamicimport.vue, examples/hippy-vue-next-demo/src/components/demo/dynamicImport/async-component-local.vue, packages/hippy-vue-next/__test__/node-ops.test.ts, packages/hippy-vue-next/__test__/runtime/element/hippy-element.test.ts, packages/hippy-vue-next/src/runtime/element/hippy-element.ts, packages/hippy-vue-next/src/runtime/style/css-selectors.ts, packages/hippy-vue/src/renderer/element-node.js, packages/hippy-vue/src/renderer/native/style/css-selectors.js, packages/hippy-vue/src/runtime/__tests__/node-ops.test.js
=> feat(vue): support to merge styles on root element of child component

framework/android/src/main/cpp/src/bridge/entry.cc, modules/vfs/native/include/vfs/uri_loader.h, modules/vfs/native/src/uri_loader.cc
=> feat(vfs): add interceptor for vfs

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> refactor(ios): make project build with library

modules/vfs/native/src/uri_loader.cc
(cherry picked from commit a5447786d51289d874ff56840075b89e6808ea28)
=> fix(vfs): fix interceptor for vfs

ios/sdk/base/executors/HippyJSCExecutor.mm
=> fix(ios): need to callback when url loading error

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/text/HippyTextView.java
=> fix(android): fix setTextColor not working

.github/workflows/project_code_lines.yml
=> ci(workflows): add github actions for project calc code of lines

framework/android/src/main/cpp/src/bridge/entry.cc
=> fix(devtools): add enable_inspector

.github/workflows/android_build_tests.yml, .github/workflows/android_build_tests_bypass.yml, .github/workflows/security_codeql_analyses.yml
=> ci(workflows): fix bugs and add check suite

framework/voltron/core/CMakeLists.txt
=> fix(devtools): voltron compile

packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json
=> fix(vue-css-loader): update loader-utils to safe version

.github/workflows/security_codeql_analyses.yml
=> ci(workflows): CodeQL analyses will check all Android projects

.github/workflows/project_code_lines.yml
=> feat(workflows): add project code line exclude files support

.github/workflows/security_codeql_analyses.yml
=> fix(workflow): fix CodeQL exception when default run

ios/sdk/component/headerrefresh/HippyHeaderRefresh.m
=> fix(iOS): refresh header not rebound automatically 

renderer/native/ios/renderer/component/headerrefresh/NativeRenderHeaderRefresh.mm
=> fix(iOS): refresh header not rebound automatically

.github/workflows/project_artifact_release.yml
=> ci(workflows): add ios artifact release

.github/workflows/android_build_tests.yml, .github/workflows/android_build_tests_bypass.yml
=> ci(workflow): add minimum V8 version test into android build tests

.github/workflows/project_artifact_compare.yml
=> feat(ci): implement iOS project artifact compare

.github/workflows/ios_build_tests.yml, .github/workflows/ios_build_tests_bypass.yml
=> feat(workflows): iOS build tests add different configurations

.github/workflows/voltron_build_tests.yml, .github/workflows/voltron_build_tests_bypass.yml, renderer/voltron/core/include/render/ffi/bridge_manager.h, renderer/voltron/core/include/render/queue/render_queue.h, renderer/voltron/core/include/render/queue/render_task_runner.h, renderer/voltron/core/src/render/ffi/bridge_manager.cc, renderer/voltron/core/src/render/ffi/render_bridge_ffi_impl.cc, renderer/voltron/core/src/render/queue/render_queue.cc, renderer/voltron/core/src/render/queue/render_task_runner.cc, renderer/voltron/core/src/render/queue/voltron_render_manager.cc, renderer/voltron/lib/bridge/render_api.dart, renderer/voltron/lib/bridge/render_bridge.dart, renderer/voltron/lib/bridge/render_bridge_define.dart, renderer/voltron/lib/controller/root_node.dart, renderer/voltron/lib/render/manager.dart, renderer/voltron/lib/render/node.dart, renderer/voltron/lib/render/operator_runner.dart, renderer/voltron/lib/render/text.dart, renderer/voltron/lib/style/virtual_node_manager.dart, renderer/voltron/lib/util.dart, renderer/voltron/lib/util/choreographer_util.dart, renderer/voltron/lib/util/log_util.dart, renderer/voltron/lib/viewmodel/modal.dart, renderer/voltron/lib/widget/modal.dart, renderer/voltron/test/render_node_test.dart, renderer/voltron/test/render_view_model_test.dart, renderer/voltron/test/util/render_op_util.dart
=> feat(voltron): optimize voltron animation

.github/workflows/ios_build_tests.yml, .github/workflows/project_artifact_compare.yml, .github/workflows/project_artifact_release.yml
=> feat(workflows): XCode project adaptation

android/sdk/src/main/jni/src/v8/stack_trace.cc
=> feat(core): adapt to different v8 versions

ios/sdk/HippyLibrary.xcodeproj/project.pbxproj, ios/sdk/HippyLibrary.xcodeproj/xcshareddata/xcschemes/HippyLibrary.xcscheme
rename scheme from 'hippy' to 'SDK',rename target name from 'hippy' to 'StaticLibrary' keep static library product name unchanged
=> refactor(ios): modify project configurations

ios/sdk/component/image/HippyImageView.m
=> fix(ios): avoid a thread race for animated image

renderer/voltron/lib/widget/div.dart
=> feat(voltron): support flutter 3.3

.github/workflows/project_artifact_compare.yml
=> feat(workflows): change `XCode` project scheme name

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/uimanager/UIManagerModule.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java, android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java
=> fix(android): edit `getBoundingClientRect` callback format

ios/sdk/module/uimanager/HippyUIManager.mm
=> fix(ios): edit `getBoundingClientRect` callback format

packages/hippy-react/src/modules/ui-manager-module.ts, packages/hippy-vue-next/src/runtime/native/index.ts, packages/hippy-vue/src/runtime/native.js
=> fix(react,vue): change measureInAppWindow error return value

ios/sdk/component/view/HippyBorderDrawing.h
=> fix(ios): need to extern as C if cpp is defined

.github/workflows/gh_issue_crash_report.yml
=> fix(workflows): fix backtrace parsing incorrect problem in crash report

build.gradle, framework/android/src/main/AndroidManifest.xml, framework/android/src/main/java/com/tencent/mtt/hippy/bridge/libraryloader/LibraryLoader.java, framework/examples/android-demo/src/main/AndroidManifest.xml, modules/android/hippy_support/src/main/AndroidManifest.xml, modules/android/link_supplier/src/main/AndroidManifest.xml, modules/android/serialization/src/main/AndroidManifest.xml, modules/vfs/android/src/main/AndroidManifest.xml, renderer/native/android/src/main/AndroidManifest.xml
=> feat(android): update AGP to 7.3.1

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java
=> fix(android): horizontal scroll view smoothScrollToPage crash

android/sdk/src/main/jni/src/performance/memory.cc
=> feat(core): add performance api for new x5 v8

android/sdk/src/main/jni/src/bridge/entry.cc, core/include/core/base/common.h, core/include/core/napi/v8/js_native_api_v8.h, core/src/napi/v8/js_native_api_v8.cc
=> fix(v8): fix `V8` OOM crash when inspector enable the js debugger

framework/voltron/core/src/bridge/android/bridge_impl.cc
=> fix(voltron): fix voltron page load failed

android/sdk/src/main/java/com/tencent/mtt/hippy/views/webview/HippyWebView.java, docs/en-us/hippy-react/components.md, docs/en-us/hippy-vue/components.md, docs/hippy-react/components.md, docs/hippy-vue/components.md, examples/hippy-react-demo/src/components/WebView/index.jsx, examples/hippy-vue-demo/src/components/demos/demo-iframe.vue, examples/hippy-vue-next-demo/src/components/demo/demo-iframe.vue, ios/sdk/component/webview/HippySimpleWebView.m, packages/hippy-vue-next/src/built-in-component.ts, packages/hippy-vue-next/src/runtime/event/hippy-event.ts, packages/hippy-vue/src/elements/built-in.js
=> feat(ios,android,vue): add load result param for webView's onLoadEnd api

Hippy.xcworkspace/contents.xcworkspacedata, framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/ios/framework.xcodeproj/project.pbxproj, modules/ios/base/base.xcodeproj/project.pbxproj, modules/ios/image/image.xcodeproj/project.pbxproj, modules/vfs/ios/vfs.xcodeproj/project.pbxproj, renderer/native/ios/nativerender.xcodeproj/project.pbxproj
=> refactor(ios): set xcode project compatility vertion to xcode 10.0

.github/workflows/ios_build_tests.yml, .github/workflows/ios_build_tests_bypass.yml
=> feat(workflows): `XCode` project adaptation

Hippy.xcworkspace/contents.xcworkspacedata, framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
=> fix(devtools): move devtools-integration project to xcproject

packages/hippy-vue-next/src/runtime/node/hippy-node.ts, packages/hippy-vue/src/renderer/__tests__/view-node.test.js, packages/hippy-vue/src/renderer/view-node.js
=> perf(vue): ignore to append existed node to improve router performance

.github/workflows/ios_build_tests.yml
=> fix(workflows): fix `iOS` build tests failed with missing dependencies

devtools/devtools-backend/.clang-format, devtools/devtools-backend/include/api/notification/data/devtools_http_request.h, devtools/devtools-backend/include/api/notification/data/devtools_http_response.h, devtools/devtools-backend/include/module/domain/tracing_domain.h, devtools/devtools-backend/src/api/notification/data/devtools_http_request.cc, devtools/devtools-backend/src/api/notification/data/devtools_http_response.cc, devtools/devtools-backend/src/module/domain/dom_domain.cc, devtools/devtools-integration/android/src/main/cpp/include/devtools/devtools_jni.h, devtools/devtools-integration/android/src/main/cpp/src/devtools_jni.cc, devtools/devtools-integration/native/.clang-format, devtools/devtools-integration/native/include/devtools/devtools_data_source.h, devtools/devtools-integration/native/include/devtools/vfs/devtools_handler.h, devtools/devtools-integration/native/src/vfs/devtools_handler.cc, driver/js/include/devtools/hippy_devtools_source.h, driver/js/include/driver/runtime/v8/inspector/v8_inspector_client_impl.h, driver/js/include/driver/runtime/v8/inspector/v8_inspector_context.h, driver/js/src/devtools/adapter/impl/hippy_dom_tree_adapter.cc, driver/js/src/devtools/hippy_devtools_source.cc, driver/js/src/runtime/v8/inspector/v8_inspector_client_impl.cc, framework/android/src/main/cpp/src/bridge/entry.cc, modules/vfs/android/src/main/cpp/src/handler/jni_delegate_handler.cc, modules/vfs/android/src/main/cpp/src/vfs_resource_holder.cc
=> feat(devtools): refactor devtools vfs

packages/hippy-vue-next/src/runtime/render/index.ts, packages/hippy-vue-next/src/util/index.ts
=> refactor(vue-next): remove Date.now in trace log

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPager.java, android/sdk/src/main/java/com/tencent/mtt/supportui/views/viewpager/ViewPager.java
=> fix(android): nested scroll conflict

ava.config.js, packages/hippy-vue-css-loader/src/__tests__/color-parser.test.js, packages/hippy-vue-css-loader/src/color-parser.js, packages/hippy-vue-css-loader/src/css-loader.js, packages/hippy-vue-css-loader/src/css-parser.js, packages/hippy-vue/src/renderer/__tests__/before-render-to-native-hook.test.js, packages/hippy-vue/src/renderer/native/index.js, packages/hippy-vue/src/runtime/index.js, packages/hippy-vue/src/runtime/native.js, packages/hippy-vue/src/util/index.js
- enable css variable defination in vue loader
- add beforeRenderToNative hook
=> feat(vue): add beforeRenderToNative hook to support computed style

devtools/devtools-integration/android/src/main/cpp/CMakeLists.txt, devtools/devtools-integration/android/src/main/cpp/include/devtools/devtools_jni.h, devtools/devtools-integration/android/src/main/cpp/src/devtools_jni.cc, devtools/devtools-integration/android/src/main/java/com/tencent/devtools/DevtoolsManager.java, devtools/devtools-integration/android/src/main/java/com/tencent/devtools/vfs/DevtoolsProcessor.java, devtools/devtools-integration/native/src/devtools_data_source.cc, framework/android/src/main/cpp/include/bridge/entry.h, framework/android/src/main/cpp/src/bridge/entry.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(devtools): fix android devtools jni not found

android/sdk/src/main/jni/src/jni/convert_utils.cc
=> fix(android): fix JSI cause JNI local reference table overflow

android/sdk/src/main/jni/src/bridge/entry.cc, core/include/core/engine.h, core/src/engine.cc, ios/sdk/base/HippyJSEnginesMapper.mm
=> fix(core): fix the problem of multi-threading at startup time

framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj, framework/ios/framework.xcodeproj/project.pbxproj, modules/ios/base/base.xcodeproj/project.pbxproj
=> fix(ios): fix hippy projects

driver/js/include/driver/engine.h, hippy.podspec
=> chore(ios): modify podspec file for cocoapods integration

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
=> feat(connector): remove unused header

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java, android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyVerticalScrollView.java
=> fix(android): nested scroll conflicts with pull refresh

.github/workflows/config/pr-path-labeler.yml, .github/workflows/gh_pr_labeler.yml
=> fix(workflows): add missing repository checkpoint within PR labeler

.github/workflows/gh_pr_labeler.yml
=> feat(workflows): add auto-merge labeler in PR

.github/workflows/project_artifact_release.yml, lerna.json, package-lock.json, package.json, scripts/release-to-latest.js
=> ci(workflows): add js release workflow

driver/js/CMakeLists.txt, framework/android/gradle.properties
=> fix(connector): temporarily compatible with devtools

.github/workflows/gh_pr_review.yml, .github/workflows/gh_pr_review_notification.yml
=> feat(workflows): add PR review notification

.github/CODEOWNERS
=> ci(codeowner): change demo path

android/sdk/src/main/jni/src/bridge/entry.cc
=> fix(core): fix reload bug for inspector

.github/workflows/project_artifact_release.yml
=> ci(workflows): fix js release issue

.github/workflows/project_artifact_release.yml
=> ci(workflows): setup node to npm registry

.github/workflows/gh_action_squash_merge.yml
=> feat(workflows): workflow add `squash-merge` action

.github/workflows/gh_action_squash_merge.yml
=> feat(workflows): use `Hippy Action Bot` as action executor

.github/workflows/config/pr-path-labeler.yml
=> ci(labeler): add new labels

ios/sdk/component/image/HippyImageView.m
=> Revert "fix(ios): animated image is not released when the view is removed"

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java
=> fix(devtools): fix try catch exception when update context

.github/workflows/gh_pr_checks_approval.yml, .github/workflows/gh_pr_guide.yml
=> feat(workflows): optimizing pull request greeting message

.github/workflows/gh_pr_guide.yml
=> fix(workflows): change workflows bot app key and id

.github/workflows/gh_issue_crash_report.yml
=> fix(workflows): fix triage outputs incorrect problem in crash report

.github/workflows/gh_pr_guide.yml
=> fix(workflows): change `pull_request_help_needed` label name

.github/CODEOWNERS
=> ci(codeowner): change codeowner classificatioin

ios/sdk/component/image/HippyImageView.m
=> fix(ios): avoid animated image multi thread operation crash

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DebugWebSocketClient.java
=> fix(devtools): callback fail when debug ws disconnect

framework/examples/ios-demo/HippyDemo/ViewController.mm, framework/ios/base/bridge/HippyBridge.h, framework/ios/base/bridge/HippyBridge.mm, framework/ios/module/imageloader/HippyImageLoaderModule.mm, modules/ios/image/HPDefaultImageProvider.m, modules/ios/image/HPImageProviderProtocol.h, renderer/native/ios/renderer/NativeRenderImpl.h, renderer/native/ios/renderer/NativeRenderImpl.mm, renderer/native/ios/renderer/NativeRenderManager.h, renderer/native/ios/renderer/NativeRenderManager.mm, renderer/native/ios/renderer/component/image/NativeRenderImageViewManager.mm, renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm
=> feat(ios): add multiple image providers

dom/src/dom/root_node.cc
=> feat(fix): fix style update nullptr error

driver/js/include/driver/scope.h, driver/js/src/scope.cc
=> fix(dom): fix event listener deconstructor error

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc, modules/vfs/android/src/main/cpp/include/vfs/handler/asset_handler.h, modules/vfs/android/src/main/cpp/src/handler/asset_handler.cc
=> fix(vfs): fix context error when activity is destroyed

.github/workflows/gh_action_approve_checks.yml, .github/workflows/gh_pr_checks_approval.yml, .github/workflows/gh_pr_review.yml, .github/workflows/gh_pr_review_notification.yml, .github/workflows/reuse_approve_checks_run.yml, .github/workflows/reuse_get_workflow_output.yml
=> refactor(workflows): refactor pull requests checks approval process

.github/CODEOWNERS
=> ci(workflows): add devtools codeowners

framework/voltron/CHANGELOG.md, framework/voltron/android/gradle.properties, framework/voltron/pubspec.yaml
=> feat(voltron): fix android so

framework/android/connector/dom/src/main/java/com/openhippy/connector/DomManager.java, framework/android/connector/driver/js/src/main/java/com/openhippy/connector/JsDriver.java, framework/android/connector/renderer/native/src/main/java/com/openhippy/connector/NativeRenderer.java, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(android): attachToRoot use root view object

devtools/devtools-backend/include/api/devtools_backend_service.h, devtools/devtools-backend/include/api/devtools_define.h, devtools/devtools-backend/include/module/domain/base_domain.h, devtools/devtools-backend/include/tunnel/net_channel.h, devtools/devtools-backend/src/api/devtools_backend_service.cc, devtools/devtools-backend/src/api/notification/default/default_network_notification.cc, devtools/devtools-backend/src/module/domain/network_domain.cc, devtools/devtools-backend/src/module/domain/tdf_inspector_domain.cc, devtools/devtools-backend/src/module/domain/tdf_performance_domain.cc, devtools/devtools-backend/src/module/domain_dispatch.cc, devtools/devtools-backend/src/module/model/css_model.cc, devtools/devtools-backend/src/module/model/dom_model.cc, devtools/devtools-backend/src/module/model/frame_poll_model.cc, devtools/devtools-backend/src/module/model/screen_shot_model.cc, devtools/devtools-backend/src/tunnel/tcp/tcp_channel.cc, devtools/devtools-backend/src/tunnel/tunnel_service.cc, devtools/devtools-backend/src/tunnel/ws/web_socket_channel.cc, devtools/devtools-integration/android/build.gradle, devtools/devtools-integration/android/src/main/cpp/include/devtools/devtools_jni.h, devtools/devtools-integration/android/src/main/cpp/src/devtools_jni.cc, devtools/devtools-integration/android/src/main/java/com/tencent/devtools/DevtoolsManager.java, devtools/devtools-integration/native/include/devtools/devtools_data_source.h, devtools/devtools-integration/native/src/devtools_data_source.cc, devtools/devtools-integration/native/src/devtools_utils.cc, devtools/devtools-integration/native/src/v8/trace_control.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/voltron/core/src/bridge/bridge_ffi_impl.cc, framework/voltron/lib/bridge/voltron_bridge.dart
=> feat(devtools): adapter to connector

devtools/devtools-integration/android/src/main/cpp/src/devtools_jni.cc, devtools/devtools-integration/native/include/devtools/devtools_data_source.h, devtools/devtools-integration/native/include/devtools/devtools_utils.h, devtools/devtools-integration/native/include/devtools/hippy_dom_data.h, devtools/devtools-integration/native/src/adapter/impl/hippy_dom_tree_adapter.cc, devtools/devtools-integration/native/src/adapter/impl/hippy_screen_adapter.cc, devtools/devtools-integration/native/src/devtools_data_source.cc, devtools/devtools-integration/native/src/devtools_utils.cc, framework/ios/base/bridge/HippyBridge.mm, framework/voltron/core/src/bridge/bridge_ffi_impl.cc
=> feat(devtools): bind dom manager not dom id

framework/voltron/example/lib/main.dart, framework/voltron/lib/adapter/resource_loader.dart
=> fix(voltron): fix voltron vfs load utf16 string

.github/CODEOWNERS
=> ci(workflows): welcome new code owner @lavnFan

.github/CODEOWNERS
=> ci(workflows): welcome new code owner @vimerzhao

framework/voltron/CHANGELOG.md, framework/voltron/core/src/bridge/ios/bridge_impl_ios.mm, framework/voltron/example/lib/base_voltron_page.dart, framework/voltron/lib/bridge/voltron_bridge.dart, framework/voltron/lib/devtools/devtools_manager.dart, framework/voltron/lib/engine/js_engine_context.dart, framework/voltron/pubspec.yaml
=> feat(voltron): devtools

.github/CODEOWNERS
=> ci(codeowner): change CODEOWNERS classification

.github/workflows/gh_pr_review_notification.yml
=> fix(workflows): change mentioned user in the PR review notification

.github/workflows/gh_action_merge.yml
=> feat(workflows): users cannot perform merge action on their own PRs

commitlint.config.js
=> chore(commitlint): adjust rules for length of commit message check

.github/workflows/gh_action_approve_checks.yml, .github/workflows/gh_pr_checks_approval.yml, .github/workflows/gh_pr_review_notification.yml
=> fix(workflows): update Github bot app key and id configuration

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java, framework/android/src/main/java/com/tencent/mtt/hippy/adapter/http/DefaultHttpAdapter.java, framework/android/src/main/java/com/tencent/mtt/hippy/adapter/http/HippyHttpRequest.java
=> feat(android): support 302 redirect for default http adapter

driver/js/src/runtime/v8/v8_bridge_utils.cc
=> fix(driver): fix debug error when exiting and re-entering

dom/include/dom/dom_manager.h, dom/src/dom/dom_manager.cc, driver/js/include/driver/engine.h, driver/js/src/engine.cc, driver/js/src/runtime/v8/v8_bridge_utils.cc, framework/android/connector/dom/src/main/cpp/src/dom_jni.cc, framework/ios/base/executors/HippyJSEnginesMapper.mm, framework/voltron/core/src/bridge/ios/VoltronJSEnginesMapper.mm, framework/voltron/core/src/bridge/ios/bridge_impl_ios.mm
=> fix(driver): fix the problem of multi-threading at startup time

core/third_party/base/include/base/log_level.h, core/third_party/base/include/base/log_settings.h, core/third_party/base/include/base/macros.h, core/third_party/base/src/base/log_settings.cc, core/third_party/base/src/base/log_settings_state.cc, core/third_party/base/src/platform/ios/logging.cc, ios/sdk/HippyLibrary.xcodeproj/project.pbxproj
=> refactor(ios): perfect copyright notice

framework/voltron/CHANGELOG.md, framework/voltron/pubspec.yaml, renderer/voltron/CHANGELOG.md, renderer/voltron/lib/style/image_virtual_node.dart, renderer/voltron/lib/util/image_util.dart, renderer/voltron/lib/viewmodel/image.dart, renderer/voltron/lib/viewmodel/view_model.dart, renderer/voltron/pubspec.yaml
=> fix(voltron): catch voltron image base64 decode error

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(android): debug reload not destroy dom manager

packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json
=> chore(bump): update loader-utils to 1.4.2

framework/voltron/CHANGELOG.md, framework/voltron/example/lib/view/qr_view.dart, framework/voltron/lib/module/storage.dart, framework/voltron/pubspec.yaml, renderer/voltron/CHANGELOG.md, renderer/voltron/lib/common/voltron_array.dart, renderer/voltron/lib/common/voltron_map.dart, renderer/voltron/lib/controller/image.dart, renderer/voltron/lib/controller/list.dart, renderer/voltron/lib/controller/list_item.dart, renderer/voltron/lib/controller/modal.dart, renderer/voltron/lib/controller/refresh.dart, renderer/voltron/lib/controller/scroller.dart, renderer/voltron/lib/controller/text_input.dart, renderer/voltron/lib/controller/view_pager.dart, renderer/voltron/lib/controller/waterfall.dart, renderer/voltron/lib/controller/web_view.dart, renderer/voltron/lib/gesture/scroll.dart, renderer/voltron/lib/render/render_context.dart, renderer/voltron/lib/style/prop.dart, renderer/voltron/lib/viewmodel/modal.dart, renderer/voltron/lib/viewmodel/scroller.dart, renderer/voltron/lib/viewmodel/view_pager.dart, renderer/voltron/lib/viewmodel/web_view.dart, renderer/voltron/lib/widget/scroller.dart, renderer/voltron/lib/widget/web_view.dart, renderer/voltron/pubspec.yaml
=> feat(voltron): fix voltron events binding

packages/hippy-vue-css-loader/package-lock.json, packages/hippy-vue-css-loader/package.json
=> chore(bump): update loader-utils to 2.0.4 to fix json5 issue

.github/workflows/gh_pr_review_notification.yml
=> feat(workflows): PR review notification add mention user

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
=> fix(android): remove web url judge in fetchResourceWithUri

renderer/native/ios/renderer/component/scrollview/NativeRenderScrollView.h, renderer/native/ios/renderer/component/scrollview/NativeRenderScrollView.mm
=> feat(ios): add method to create custom scrollview

.github/CODEOWNERS
=> chore(codeowner): change settings.gradle codeowner

.github/workflows/gh_pr_review_notification.yml
=> feat(workflows): PR review notification filter draft PR

.github/workflows/gh_pr_auto_updater.yml, .github/workflows/gh_pr_review_notification.yml
=> chore: cherry-pick from v3.0-dev

framework/voltron/CHANGELOG.md, framework/voltron/pubspec.yaml, renderer/voltron/CHANGELOG.md, renderer/voltron/pubspec.yaml
=> feat(voltron): update voltron render version

.github/workflows/gh_action_merge.yml, .github/workflows/reuse_classify_commits.yml
=> feat(workflows): only uses non-merge commits as valid commits

.github/workflows/gh_pr_auto_merger.yml
=> feat(workflows): add pull requests auto merger

.github/workflows/gh_pr_auto_merger.yml, .github/workflows/gh_pr_review_notification.yml
=> cp: from master to v3.0-dev

.github/workflows/gh_pr_auto_merger.yml
=> fix(workflows): change auto_merger comment message

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/CSSModel.java
=> fix(devtools): remove regular expression injection

.github/workflows/gh_pr_auto_updater.yml
=> feat(workflows): use classic PAT instead of Github App Token

.github/workflows/gh_runners_monitor.yml
=> feat(workflows): add self-hosted runners monitor

.github/workflows/gh_pr_auto_updater.yml, .github/workflows/gh_runners_monitor.yml
=> chore: cherry-pick from master

.github/workflows/gh_action_merge.yml
skip privilege escalation when
invoked by a user with admin role
or contains only one normal commit.
=> feat(workflows): skip privilege escalation when conditions are met

.github/CODEOWNERS
=> chore(codeowner): add C++ codeowner

driver/js/src/runtime/v8/v8_bridge_utils.cc, renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java, renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java
=> fix(devtools): reuse inspector client in the same engine

.github/workflows/ios_build_tests.yml, .github/workflows/ios_build_tests_bypass.yml
=> perf(workflows): parallelize sdk and demo build script to improve perf

Hippy.podspec, HippySDK.xcworkspace/contents.xcworkspacedata, framework/ios/Framework.xcodeproj/project.pbxproj, renderer/native/ios/NativeRenderer.xcodeproj/project.pbxproj, xcodeinitscript.sh
=> refactor(ios): remove enable_bitcode confiuration for devtools cmakefile

framework/voltron/lib/engine/voltron_js_engine.dart
=> fix(voltron): fix voltron crash on retry dev mode

framework/ios/Framework.xcodeproj/project.pbxproj
=> feat(ios): add devtools targets to hippysdk workspace

.github/workflows/security_codeql_analyses.yml
=> refactor(workflows): refactor CodeQL analyses script to save resources

.github/workflows/gh_pr_checks_approval.yml, .github/workflows/ios_build_tests.yml, .github/workflows/ios_build_tests_bypass.yml, .github/workflows/voltron_build_tests_bypass.yml
=> feat(workflows): increase workflows robustness

devtools/devtools-integration/native/src/adapter/impl/hippy_screen_adapter.cc, devtools/devtools-integration/native/src/devtools_data_source.cc, framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
=> fix(devtools): fix crash when open devtools frontend and reload

.github/workflows/gh_runners_monitor.yml
=> feat(workflows): optimize self-hosted runner alarm strategy

.github/workflows/3rd_prebuilt_v8.yml, .github/workflows/android_build_tests.yml, .github/workflows/android_build_tests_bypass.yml, .github/workflows/docker_build_image.yml, .github/workflows/gh_issue_crash_report.yml, .github/workflows/voltron_build_tests.yml, .github/workflows/voltron_build_tests_bypass.yml
=> feat(workflows): limit workflow concurrency to save resources

.github/workflows/gh_pr_merge_guard.yml
=> fix(workflows): fix merge guard not running after updating branch

buildconfig/cmake/InfraPackagesModule.cmake
=> chore(cmake): set `CMP0135` policy to new behavior explicitly

.github/CODEOWNERS
=> chore(codeowner): add web-renderer codeowner

build.gradle, buildconfig/cmake/GlobalPackagesModule.cmake, buildconfig/cmake/InfraPackagesModule.cmake, devtools/devtools-integration/android/src/main/cpp/CMakeLists.txt, devtools/devtools-integration/native/CMakeLists.txt, driver/js/CMakeLists.txt, framework/android/build.gradle, framework/android/connector/dom/src/main/cpp/CMakeLists.txt, framework/android/connector/driver/js/gradle.properties, framework/android/connector/driver/js/src/main/cpp/CMakeLists.txt, framework/android/connector/renderer/native/src/main/cpp/CMakeLists.txt, framework/android/gradle.properties, framework/android/src/main/cpp/CMakeLists.txt, framework/voltron/core/CMakeLists.txt, gradle.properties, settings.gradle
=> feat(android): decouple connector and its associated modules
