Tencent/Hippy

.github/workflows/gh_webhook_retrier.yml

feat(workflows): add webhook retrier

---

README.md

docs(ios): update readme files

---

framework/ios/Framework.xcodeproj/project.pbxproj
framework/ios/base/executors/HippyJSEnginesMapper.mm
framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): change engine dealloc thread from main thread to js thread

---

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/NativeGestureDispatcher.java

fix(android): long click conflict with touch

---

framework/voltron/CHANGELOG.md
framework/voltron/lib/engine/voltron_js_engine.dart
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/core/src/render/queue/render_task_runner.cc
renderer/voltron/lib/util/log_util.dart
renderer/voltron/lib/util/screen_util.dart
renderer/voltron/lib/widget/root.dart
renderer/voltron/pubspec.yaml

fix(voltron): fix cache engine mode ui size error

---

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/NativeGestureDispatcher.java

Revert "fix(android): long click conflict with touch"

---

.github/workflows/gh_pr_merge_guard.yml

fix(workflows): fix unexpected passing when synchronize action occurs

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullRefreshHelper.java

fix(android): pull header/footer collapse animation

---

renderer/native/ios/renderer/component/image/NativeRenderAnimatedImageView.m

fix(iOS): gif is play fast at high fresh rate device

---

examples/hippy-vue-next-demo/src/components/demo/demo-dynamicimport.vue
examples/hippy-vue-next-demo/src/components/native-demo/demo-nested-scroll.vue
examples/hippy-vue-next-demo/src/components/native-demo/demo-pull-header-footer.vue
examples/hippy-vue-next-demo/src/components/native-demo/demo-vue-native.vue
lint-staged.config.js
package.json

chore(lint): perf some js lint issues

---

.github/workflows/gh_pr_checks_approval.yml

fix(workflows): fix the tips content incompletely generated problem

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java

fix(android): `initialContentOffset` takes effect too late

---

.github/workflows/gh_pr_auto_merger.yml

fix(workflows): each head SHA will only trigger one merge action

---

.github/workflows/project_dependency_review.yml

chore(workflows): add project dependency review

---

hippy.podspec
ios/sdk/HippyLibrary.xcodeproj/project.pbxproj
ios/sdk/base/HippyJavaScriptExecutor.h
ios/sdk/base/HippyRootShadowView.mm
ios/sdk/component/text/HippyShadowText.mm
ios/sdk/component/textinput/HippyShadowTextView.mm
ios/sdk/component/view/HippyShadowView+MTTLayout.h
ios/sdk/component/view/HippyShadowView.h
ios/sdk/component/view/HippyShadowView.mm
ios/sdk/layout/x5LayoutUtil.h
ios/sdk/module/loader/ios_loader.h
ios/sdk/module/turbo/HippyOCTurboModule+Inner.h

fix(ios): podspec lint error & enable Module import

---

android/sdk/src/main/jni/src/bridge/entry.cc

feat(core): remove default HeapLimitSlowGrowthStrategy

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullFooterRefreshHelper.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullHeaderRefreshHelper.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/PullRefreshHelper.java

fix(android): send scroll event when pulling header/footer

---

ios/sdk/base/HippyRootView.mm
ios/sdk/component/modal/HippyModalHostView.h
ios/sdk/component/modal/HippyModalHostView.m
ios/sdk/component/modal/HippyModalHostViewController.h
ios/sdk/component/modal/HippyModalHostViewController.m
ios/sdk/module/uimanager/HippyUIManager.h
ios/sdk/module/uimanager/HippyUIManager.mm

feat(ios): add onsizechanged event

---

docs/en-us/hippy-react/native-event.md
docs/en-us/hippy-vue/native-event.md
docs/hippy-react/native-event.md
docs/hippy-vue/native-event.md

chore(docs): update onSizeChanged event document

---

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManager.java
android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
android/sdk/src/main/java/com/tencent/mtt/hippy/HippyNormalEngineManager.java
android/sdk/src/main/java/com/tencent/mtt/hippy/HippySingleThreadEngineManager.java
android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridge.java
android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManager.java
android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevRemoteServerData.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerHelper.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImpl.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerImplDisable.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerInterface.java
android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevSupportManager.java
examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
packages/hippy-react/src/renderer/render.ts
packages/hippy-vue-next/src/runtime/element/hippy-element.ts
packages/hippy-vue/src/renderer/native/__tests__/index.test.js
packages/hippy-vue/src/renderer/native/index.js

feat(android): add prod remotedebug & local bundle instead of remote server

---

scripts/react-configs.js
scripts/vue-next-configs.js
scripts/web-renderer-configs.js

build(ts): add customized ts include path

---

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java

fix(android): drawPath CRASH_java.lang.NullPointerException

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java

fix(android): textInput may throw IllegalStateException

---

android/sdk/src/main/jni/src/loader/adr_loader.cc
core/src/engine.cc
core/src/modules/contextify_module.cc

fix(core): fix deadlock in debug mode

---

driver/js/src/napi/v8/js_native_api_v8.cc
driver/js/src/runtime/v8/v8_bridge_utils.cc
framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(driver): fix reuse bug for debug mode

---

README.md

docs(README): update ios app building steps

---

android/sdk/src/test/java/com/tencent/mtt/hippy/utils/UrlUtilsTest.java

fix(android): fix unit test case

---

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java

fix(android): remove use of mDebugInitJSFrameworkCallback

---

ios/sdk/component/image/HippyImageView.m

fix(ios): avoid multi-threading problem of imageview

---

framework/examples/ios-demo/podfile
hippy.podspec

chore(ios): rename hippy.podspec as lowercase

---

docs/en-us/hippy-vue/vue3.md
docs/hippy-vue/vue3.md
examples/hippy-vue-next-demo/src/components/native-demo/demo-dialog.vue

chore(example,doc): add dialog attention for vue3.0

---

core/include/core/engine.h
core/src/engine.cc
core/src/scope.cc

fix(core): avoid crash caused by lock in the destructor

---

android/sdk/src/main/jni/src/jni/uri.cc
core/include/core/base/string_view_utils.h
core/src/napi/jsc/js_native_api_value_jsc.cc
core/src/napi/v8/js_native_api_v8.cc
core/third_party/base/include/base/unicode_string_view.h
core/third_party/base/src/base/unicode_string_view.cc

fix(base): fix unknown word misspelling

---

android/sdk/src/main/jni/src/bridge/entry.cc
android/sdk/src/main/jni/src/bridge/java2js.cc
android/sdk/src/main/jni/src/loader/adr_loader.cc
android/sdk/src/main/jni/src/performance/memory.cc
android/sdk/src/main/jni/src/v8/heap_limit.cc
android/sdk/src/main/jni/src/v8/request_interrupt.cc
android/sdk/src/main/jni/src/v8/stack_trace.cc
core/src/engine.cc
core/src/napi/jsc/js_native_api_value_jsc.cc

feat(core): formatting and replacing concrete types with auto

---

android/sdk/src/main/jni/src/jni/uri.cc
core/include/core/base/string_view_utils.h
core/src/napi/jsc/js_native_api_value_jsc.cc
core/src/napi/v8/js_native_api_v8.cc
core/third_party/base/include/base/unicode_string_view.h
core/third_party/base/src/base/unicode_string_view.cc

fix(base): fix capitalization error

---

driver/js/packages/hippy-vue/src/elements/built-in.js
driver/js/packages/hippy-vue/src/renderer/__tests__/document-node.test.js
driver/js/packages/hippy-vue/src/renderer/element-node.js
driver/js/packages/hippy-vue/src/util/event.js

fix(vue3): fix listViewItem disappear event not triggered

---

renderer/native/android/src/test/java/com/tencent/renderer/utils/ChoreographerUtilsTest.java

fix(android): solve ChoreographerUtilsTest problem

---

docs/en-us/hippy-vue/vue3.md
docs/hippy-vue/vue3.md

docs(vue3): fix dialog introduction error

---

dom/include/dom/dom_node.h
dom/src/dom/animation/animation_manager.cc
dom/src/dom/dom_node.cc
dom/src/dom/root_node.cc

feat(dom): add willchange attribute to dom node

---

packages/hippy-vue-next/src/runtime/event/hippy-event-dispatcher.ts
packages/hippy-vue-next/src/runtime/event/hippy-event.ts
packages/hippy-vue/src/renderer/native/event/dispatcher.js

feat(vue): add native event parameters

---

ios/sdk/HippyLibrary.xcodeproj/project.pbxproj
ios/sdk/component/viewPager/HippyViewPager.h
ios/sdk/component/viewPager/HippyViewPagerManager.m

refactor(ios): remove unused code of viewPager

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPager.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPagerController.java

feat(android): support set custom ViewPagerPageChangeListener

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPager.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/HippyViewPagerController.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/ViewPagerPageChangeListener.java

fix(android): add buildViewPager

---

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/PromiseImpl.java

fix(android): promise leak after engine destroy

---

renderer/native/ios/renderer/component/view/UIView+DomEvent.m

fix(ios): fix event property bug

---

ios/sdk/module/uimanager/HippyUIManager.mm

refactor(ios): modify the usage mode

---

core/src/vm/v8/v8_vm.cc

fix(core): fix debugmode crash

---

ios/sdk/component/image/HippyImageView.m

fix(ios): fixed the issue that pictures would not be displayed

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/ImageNode.java
android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/DiffUtils.java
android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/common/HippyNestedScrollHelper.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/BackgroundDrawable.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/ContentDrawable.java

- View: linearGradient, nestedScrollPriority, backgroundImage
- Image: source, defaultSource, verticalAlign
- Text: verticalAlign

fix(android): fix default value for several properties

---

framework/voltron/CHANGELOG.md
framework/voltron/core/src/bridge/bridge_ffi_impl.cc
framework/voltron/lib/adapter/resource_loader.dart
framework/voltron/lib/bridge/bridge_define.dart
framework/voltron/lib/bridge/voltron_api.dart
framework/voltron/lib/engine/voltron_js_engine.dart
framework/voltron/lib/voltron/loader.dart
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/lib/bridge/render_api.dart
renderer/voltron/lib/engine/loader.dart
renderer/voltron/lib/render/render_context.dart
renderer/voltron/lib/widget/root.dart
renderer/voltron/pubspec.yaml
renderer/voltron/test/render_node_test.dart
renderer/voltron/test/render_view_model_test.dart

feat(voltron): support multi flutter engine

---

packages/hippy-react/src/dom/element-node.ts

feat(react): support fontWeight in number

---

driver/js/src/runtime/v8/v8_bridge_utils.cc
framework/ios/base/executors/HippyJSExecutor.mm

fix(driver): fix hippy vue bug

---

ios/sdk/component/textinput/HippyTextField.m
ios/sdk/component/textinput/HippyTextView.mm

fix(ios): maxlength property not working in hippy-vue

---

ios/sdk/component/waterfalllist/HippyWaterfallView.m
ios/sdk/component/waterfalllist/HippyWaterfallViewDatasource.h
ios/sdk/component/waterfalllist/HippyWaterfallViewDatasource.m

fix(ios): fix banner view bug in watefall view

---

driver/js/src/runtime/v8/v8_bridge_utils.cc
framework/voltron/core/src/bridge/android/bridge_impl.cc
framework/voltron/core/src/bridge/android/js2dart.cc
framework/voltron/core/src/bridge/android/js2dart.h
framework/voltron/core/src/bridge/ios/VoltronJSCExecutor.mm
framework/voltron/core/src/bridge/ios/bridge_impl_ios.mm

fix(voltron): fix voltron build error

---

driver/js/include/driver/napi/jsc/jsc_ctx.h
driver/js/src/napi/jsc/jsc_ctx.cc

feat(driver): remove global_external_data

---

modules/footstone/src/platform/adr/looper_driver.cc
modules/footstone/src/platform/ios/looper_driver.cc

fix(footstone): fix looper driver bug

---

driver/js/include/driver/engine.h
driver/js/src/engine.cc

feat(driver): remove redundant code

---

examples/hippy-react-demo/scripts/env-polyfill.js
examples/hippy-vue-demo/scripts/env-polyfill.js
examples/hippy-vue-next-demo/scripts/env-polyfill.js

fix(demo): fix cross-env script error

---

examples/hippy-vue-demo/scripts/hippy-webpack.android-vendor.js
examples/hippy-vue-demo/scripts/hippy-webpack.android.js
examples/hippy-vue-demo/scripts/hippy-webpack.dev.js
examples/hippy-vue-demo/scripts/hippy-webpack.ios-vendor.js
examples/hippy-vue-demo/scripts/hippy-webpack.ios.js
examples/hippy-vue-demo/scripts/hippy-webpack.web-renderer.dev.js
examples/hippy-vue-demo/scripts/hippy-webpack.web-renderer.js

refactor(demo): change vue-loader dependency judgement

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(driver): fix iOS release context crash

---

renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm

fix(ios): fix vue demo bug

---

android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/model/DomModel.java
android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java
android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/uimanager/UIManagerModule.java

feat(android): add getNodeForLocation for utils mode

---

examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
ios/sdk/base/HippyFont.mm
ios/sdk/base/executors/HippyJSCExecutor.mm
ios/sdk/component/image/HippyAnimatedImageView.m
ios/sdk/component/listview/HippyBaseListView.m
ios/sdk/debug/devtools/HippyDevWebSocketClient.m
ios/sdk/layout/MTTFlexLine.cpp
ios/sdk/layout/MTTNode.cpp
ios/sdk/utils/HippyLog.mm

eliminate some warnings

---

docs/android/v8-api.md

fix(readme): fix readme of requestInterrupt method

---

docs/en-us/android/v8-api.md

fix(readme): fix English README of requestInterrupt method

---

renderer/tdf/android/src/main/java/com/tencent/renderer/tdf/embed/TDFEmbeddedViewFactoryImpl.java
renderer/tdf/android/src/main/java/com/tencent/renderer/tdf/embed/TDFEmbeddedViewUtil.java
renderer/tdf/android/src/main/java/com/tencent/renderer/tdf/embed/TDFEmbeddedViewWrapper.java
renderer/tdf/common/include/renderer/tdf/viewnode/embedded_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/image_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/list_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/modal_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/scroll_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/text_input_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/text_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/view_pager_node.h
renderer/tdf/common/src/renderer/tdf/viewnode/embedded_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/image_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/list_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/modal_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/node_attributes_parser.cc
renderer/tdf/common/src/renderer/tdf/viewnode/scroll_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/text_input_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/text_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/view_pager_node.cc

Fix TDFRender ViewNode styles and props

---

.github/workflows/3rd_prebuilt_v8.yml

fix(workflows): using stdlibc++ on the windows platform

---

dom/include/dom/root_node.h
dom/src/dom/root_node.cc

fix(dom): mark dirty when text child node changes

---

.github/workflows/3rd_prebuilt_v8.yml

feat(workflows): install ninja via chocolatey pkg

---

.github/workflows/gh_pr_checks_approval.yml
memory.sh

fix(workflow): fix workflow yml file syntax error

---

android/sdk/src/main/jni/src/bridge/entry.cc
core/include/core/napi/v8/v8_ctx.h
core/src/napi/v8/v8_ctx.cc

fix(core): fix uncaughtException bug

---

driver/js/include/driver/napi/js_try_catch.h
driver/js/include/driver/napi/jsc/jsc_ctx.h
driver/js/include/driver/napi/jsc/jsc_try_catch.h
driver/js/include/driver/napi/v8/v8_ctx.h
driver/js/include/driver/napi/v8/v8_try_catch.h
driver/js/include/driver/vm/v8/v8_vm.h
driver/js/src/engine.cc
driver/js/src/modules/contextify_module.cc
driver/js/src/napi/jsc/jsc_ctx.cc
driver/js/src/napi/jsc/jsc_try_catch.cc
driver/js/src/napi/v8/v8_ctx.cc
driver/js/src/napi/v8/v8_try_catch.cc
driver/js/src/runtime/v8/v8_bridge_utils.cc
driver/js/src/vm/js_vm.cc
driver/js/src/vm/v8/v8_vm.cc
framework/ios/base/executors/HippyJSExecutor.mm

feat(driver): refactor vm and fix engine erase crash

---

framework/voltron/CHANGELOG.md
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/pubspec.yaml

feat(voltron): update voltron to 0.0.19

---

driver/js/packages/hippy-vue-native-components/src/animation.js

fix(vue): make sure start animation after node created

---

.github/workflows/3rd_prebuilt_v8.yml

feat(workflows): differentiate between release and debug build type

---

framework/examples/ios-demo/HippyDemo/ViewController.mm
framework/ios/base/bridge/HippyConvenientBridge.h
framework/ios/base/bridge/HippyConvenientBridge.mm

feat(ios): add load debug bundle interface

---

driver/js/include/driver/vm/jsc/jsc_vm.h
driver/js/src/napi/jsc/jsc_ctx.cc

fix(driver): fix iOS reload crash

---

driver/js/include/driver/napi/jsc/jsc_ctx.h
driver/js/include/driver/scope.h
driver/js/src/napi/jsc/jsc_ctx.cc

fix(driver): fix hippy-vue animation bug

---

dom/include/dom/animation/animation_manager.h
dom/src/dom/animation/animation_manager.cc

feat(animation): remove eventListener when animationManager is destroyed

---

dom/include/dom/animation/animation_manager.h
dom/include/dom/root_node.h
dom/src/dom/animation/animation_manager.cc
dom/src/dom/root_node.cc
framework/android/connector/dom/src/main/cpp/include/connector/dom_jni.h
framework/android/connector/dom/src/main/cpp/src/dom_jni.cc
framework/android/connector/dom/src/main/java/com/openhippy/connector/DomManager.java
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
framework/ios/base/bridge/HippyConvenientBridge.mm

feat(animation): add releaseRootResources for rootNode

---

.github/workflows/3rd_prebuilt_v8.yml

feat(workflows): enable iterator debugging on windows platform

---

dom/src/dom/animation/animation_manager.cc
framework/examples/ios-demo/HippyDemo/ViewController.mm
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bridge/HippyConvenientBridge.mm
framework/ios/base/executors/HippyJSExecutor.mm
renderer/native/ios/renderer/NativeRenderImpl.mm

fix(ios): fix animation modules memory leaks

---

framework/examples/ios-demo/HippyDemo/ViewController.mm
framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): remove error codes

---

framework/examples/ios-demo/HippyDemo/TestModule.mm
framework/ios/base/executors/HippyJSExecutor.mm
framework/ios/debug/devtools/HippyDevInfo.h
framework/ios/debug/devtools/HippyDevInfo.m

fix(devtools): fix ios devtools show

---

dom/src/dom/root_node.cc

fix(dom): fix MarkLayoutNodeDirty bug

---

framework/examples/ios-demo/HippyDemo/TestModule.mm
framework/examples/ios-demo/HippyDemo/ViewController.mm
framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bridge/HippyConvenientBridge.h
framework/ios/base/bridge/HippyConvenientBridge.mm
framework/ios/module/dev/HippyRedBox.mm

fix(ios): devtools debug fix

---

framework/ios/base/HippyPerformanceLogger.h
framework/ios/base/HippyPerformanceLogger.m
framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bridge/HippyConvenientBridge.h
framework/ios/base/bridge/HippyConvenientBridge.mm
framework/ios/utils/NSObject+CtxValue.h
framework/ios/utils/NSObject+CtxValue.mm
renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/NativeRenderRootView.m
renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/textinput/NativeRenderObjectTextView.mm

feat(ios): optimize performance ,memory usage and interface

---

examples/hippy-vue-demo/src/components/native-demos/animations/loop.vue
packages/hippy-vue/src/renderer/element-node.js
packages/hippy-vue/src/runtime/modules/style.js

fix(vue): fix vue style diff error

---

packages/hippy-react-web/src/components/text.tsx
scripts/react-web-configs.js

fix(@hippy/react-web): fixed style when numberofLines > 1

---

ios/sdk/base/executors/HippyJSCExecutor.mm

feat(ios): add log when load bundles

---

ios/sdk/base/executors/HippyJSCExecutor.mm
ios/sdk/module/animation/HippyExtAnimationModule.m

fix(ios): fix lock when lock dealloced

---

packages/hippy-vue/src/runtime/modules/style.js

fix(vue): fix vNode element empty error

---

core/src/napi/jsc/jsc_ctx.cc
ios/sdk/base/executors/HippyJSCExecutor.mm

refactor(ios): use utf16 creation method instead of utf8 creation method

---

.github/CODEOWNERS
.github/workflows/ios_build_tests.yml
.github/workflows/ios_build_tests_bypass.yml
framework/examples/ios-demo/project.yml
hippy.podspec

chore(ios): update xcode project configuration

---

.gitignore
framework/examples/ios-demo/podfile
framework/ios/base/enginewrapper/v8/HippyV8ContextWrapper.mm
framework/ios/utils/v8/NSObject+V8Value.h
framework/ios/utils/v8/NSObject+V8Value.mm
hippy.podspec
xcodeinitscript.sh

feat(ios): support v8 for ios

---

framework/voltron/core/src/bridge/bridge_ffi_impl.cc
framework/voltron/lib/bridge/voltron_bridge.dart
renderer/voltron/analysis_options.yaml
renderer/voltron/core/src/render/bridge/render_bridge_ffi_impl.cc

fix(voltron): fix voltron debug mode crash

---

framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bridge/HippyConvenientBridge.h
framework/ios/base/bridge/HippyConvenientBridge.mm

feat(ios): add snap shot data interface

---

framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/module/loader/HippyFileHandler.mm

fix(ios): move hippy default file scheme handler to hippyfilehandler

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
android/sdk/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java

fix(android): text default color

---

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/TimingAnimation.java

fix(android): color value in animation lose precision

---

android/sdk/src/main/jni/src/bridge/entry.cc
core/include/core/task/worker_task_runner.h

fix(core): fix promise crash

---

dom/include/dom/dom_manager.h
dom/src/dom/animation/animation.cc
dom/src/dom/dom_manager.cc

fix(dom): fix delay bug for animation

---

.github/CODEOWNERS

chore(codeowner): change codeowner

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(driver): fix createObject bug

---

dom/src/dom/diff_utils.cc
renderer/native/android/src/main/cpp/src/renderer/native_render_manager.cc

fix(android): diff_utils remove insert nullptr

---

ios/sdk/module/animation/HippyExtAnimationModule.m
ios/sdk/module/animation/HippyExtAnimationViewParams.m

fix(ios): animation module multi-thread crash

---

ios/sdk/component/text/HippyShadowText.mm

refactor(ios): optimize performance of text with vertialAlign

---

ios/sdk/component/text/HippyShadowText.mm

fix(ios): strange shaped character rendering bug

---

driver/js/packages/hippy-vue/src/renderer/element-node.js
driver/js/packages/hippy-vue/src/runtime/modules/style.js

fix(vue): support static style diff in updateNode

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java

fix(android): memory leak of `RecyclerViewEventHelper`

---

framework/examples/ios-demo/HippyDemo/TestModule.mm
framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/modules/HippyModuleMethod.mm
framework/ios/module/localstorage/HippyAsyncLocalStorage.mm
framework/ios/utils/jsc/NSObject+JSValue.m
modules/ios/base/HPLog.h
renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/NativeRenderObjectRootView.mm
renderer/native/ios/renderer/component/text/NativeRenderObjectText.h
renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/text/NativeRenderText.mm
renderer/native/ios/renderer/component/view/NativeRenderObjectView.h
renderer/native/ios/renderer/component/view/NativeRenderObjectView.mm
renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm

feat(ios): reset hippy log and text system

---

renderer/tdf/android/build.gradle
renderer/tdf/android/src/main/java/com/tencent/renderer/TDFRenderer.java
renderer/tdf/android/src/main/java/com/tencent/renderer/tdf/embed/TDFEmbeddedViewFactoryImpl.java
renderer/tdf/common/include/renderer/tdf/tdf_render_manager.h
renderer/tdf/common/include/renderer/tdf/viewnode/embedded_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/list_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/node_attributes_parser.h
renderer/tdf/common/include/renderer/tdf/viewnode/root_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/text_input_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/text_view_node.h
renderer/tdf/common/include/renderer/tdf/viewnode/view_node.h
renderer/tdf/common/src/renderer/tdf/tdf_render_manager.cc
renderer/tdf/common/src/renderer/tdf/viewnode/embedded_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/image_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/list_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/node_attributes_parser.cc
renderer/tdf/common/src/renderer/tdf/viewnode/root_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/scroll_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/text_input_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/text_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/view_node.cc

fix(renderer): fix tdf renderer bug

---

framework/android/connector/renderer/native/src/main/java/com/openhippy/connector/NativeRenderConnector.java
framework/android/connector/renderer/native/src/main/java/com/openhippy/connector/NativeRenderer.java
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
renderer/native/android/src/main/java/com/tencent/renderer/RenderProxy.java

fix(android): suport find view by id for engine context

---

framework/android/connector/dom/src/main/cpp/src/dom_jni.cc

fix(connector): domManager calls terminate when it is destroyed

---

framework/android/connector/renderer/tdf/gradle.properties
framework/examples/android-demo/build.gradle
renderer/tdf/android/build.gradle
renderer/tdf/android/src/main/java/com/tencent/renderer/TDFRenderer.java

fix(renderer): update tdfcore

---

.github/CODEOWNERS
.github/workflows/project_artifact_compare.yml
_Pods.xcodeproj

build(ios): fix artifact build

---

.github/workflows/project_artifact_compare.yml

build(ios): update artifact build script

---

dom/src/dom/animation/cubic_bezier_animation.cc

fix(animation): add protection logic

---

framework/android/connector/dom/src/main/cpp/include/connector/dom_jni.h
framework/android/connector/dom/src/main/cpp/src/dom_jni.cc
framework/android/connector/dom/src/main/java/com/openhippy/connector/DomManager.java
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java

fix(layout): fix missing scale factor value

---

driver/js/packages/hippy-vue-next-style-parser/package-lock.json
driver/js/packages/hippy-vue-next/package-lock.json

chore(vue3): add pacakge-lock.json

---

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java

feat(java): add default method for moduleListener interface

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java

fix(android): add Nullable for destroyModule

---

driver/js/include/driver/scope.h
driver/js/src/modules/timer_module.cc
driver/js/src/modules/ui_manager_module.cc
driver/js/src/scope.cc

fix(driver): fix calluifunction holder bug

---

android/sdk/src/main/jni/src/bridge/entry.cc
core/include/core/task/worker_task_runner.h
core/src/task/worker_task_runner.cc

fix(core): fix multithreading bug

---

ios/sdk/layout/MTTNode.cpp
ios/sdk/layout/MTTNode.h
ios/sdk/layout/MTTUtil.cpp
ios/sdk/layout/MTTUtil.h

fix(ios, layout): fix rounding error using double instead of float

---

android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
android/sdk/src/main/jni/include/bridge/entry.h
android/sdk/src/main/jni/include/loader/adr_loader.h
android/sdk/src/main/jni/src/bridge/entry.cc
android/sdk/src/main/jni/src/loader/adr_loader.cc
examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java

fix(core): fix snapshot bug when using dynamicLoad

---

examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java

fix(Android): demo uses NoSnapshot by default

---

docs/_navbar.md
docs/android/_sidebar.md
docs/android/snapshot.md
docs/en-us/_navbar.md
docs/en-us/android/_sidebar.md
docs/en-us/android/snapshot.md

feat(core): add readme for snapshot

---

renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/textinput/NativeRenderObjectTextView.mm

fix(ios): text need to do layout after marking dirty

---

driver/js/include/driver/js_driver_utils.h
driver/js/src/js_driver_utils.cc
framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
framework/voltron/core/src/bridge/android/bridge_impl.cc

fix(driver): fix reload crash

---

driver/js/src/js_driver_utils.cc

fix(driver): fix group bug

---

framework/android/src/main/java/com/tencent/mtt/hippy/adapter/http/DefaultHttpAdapter.java

fix(android): cookies must be set for each request

---

framework/android/src/main/cpp/src/entry.cc
framework/ios/base/bridge/HippyConvenientBridge.mm
modules/vfs/native/include/vfs/uri_loader.h
modules/vfs/native/src/uri_loader.cc

refactor(vfs): add Terminate for vfs

---

driver/js/src/js_driver_utils.cc
driver/js/src/vm/v8/inspector/v8_inspector_client_impl.cc
driver/js/src/vm/v8/v8_vm.cc
modules/footstone/src/task_runner.cc

fix(driver): fix finish crash

---

ios/sdk/component/image/HippyImageView.m
ios/sdk/component/image/HippyImageViewCustomLoader.h

feat(ios): support skipping inner decoding when use custom image loader

---

renderer/native/ios/renderer/component/textinput/NativeRenderTextView.mm

sync from 2.x_1

---

framework/voltron/example/pubspec.yaml

chore(build): fix voltron test check error

---

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(driver): fix scope bug

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java

fix(android): add get engine id for native renderer

---

driver/js/src/modules/performance/performance_mark_module.cc
driver/js/src/modules/performance/performance_module.cc
driver/js/src/performance/performance.cc

fix(performance): fix performance bug

---

framework/examples/ios-demo/HippyDemo/ViewController.mm

fix(ios): repath vue2 demo folder

---

renderer/native/ios/renderer/NativeRenderImpl.mm

fix(ios): padding result needs to set to render object

---

renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm

fix(ios): fix initial contentoffset bug for listview

---

.github/CODEOWNERS

chore(build): change code owner

---

driver/js/packages/hippy-vue-next/src/runtime/node/hippy-node.ts
driver/js/packages/hippy-vue/src/renderer/native/index.js

fix(vue): not to move node when refNode is same as newNode

---

docs/_navbar.md
driver/js/examples/hippy-vue-next-demo/src/components/demo/demo-iframe.vue

Feature/dev doc 3.0

---

devtools/devtools-backend/src/module/model/dom_model.cc
devtools/devtools-integration/native/include/devtools/devtools_utils.h
devtools/devtools-integration/native/src/adapter/impl/hippy_dom_tree_adapter.cc
devtools/devtools-integration/native/src/devtools_utils.cc
driver/js/src/scope.cc
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java
renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm
renderer/voltron/lib/controller/controller.dart
renderer/voltron/lib/util/devtools_util.dart

feat(devtools): obtain location for screen

---

dom/src/dom/diff_utils.cc
dom/src/dom/taitank_layout_node.cc

fix(layout): get default correct value when delete some properties

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/waterfalllist/HippyWaterfallLayoutManager.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/BaseLayoutManager.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/recyclerview/RecyclerAdapter.java

fix(android): waterfall scrolling error with small content height

---

framework/voltron/CHANGELOG.md
framework/voltron/core/src/bridge/ios/bridge_impl_ios.mm
framework/voltron/example/lib/view/qr_view.dart
framework/voltron/example/pubspec.yaml
framework/voltron/pubspec.yaml
modules/vfs/voltron/CHANGELOG.md
modules/vfs/voltron/lib/vfs_wrapper.dart
modules/vfs/voltron/pubspec.yaml
modules/voltron/ffi/CHANGELOG.md
modules/voltron/ffi/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/lib/controller/web_view.dart
renderer/voltron/lib/style/flex_value.dart
renderer/voltron/lib/style/text_virtual_node.dart
renderer/voltron/lib/style/update.dart
renderer/voltron/lib/viewmodel/web_view.dart
renderer/voltron/lib/widget/web_view.dart
renderer/voltron/pubspec.yaml

feat(voltron): update base flutter version to 3.3.8

---

examples/ios-demo/HippyDemo/AppDelegate.m
ios/sdk/base/HippyBridge.mm
ios/sdk/base/HippyKeyCommands.h
ios/sdk/base/HippyKeyCommands.m
ios/sdk/module/dev/HippyDevMenu.h
ios/sdk/module/dev/HippyDevMenu.mm
ios/sdk/utils/HippyUtils.h
ios/sdk/utils/HippyUtils.m

fix(ios): key commands for dev menu not working

---

.github/CODEOWNERS
ios/sdk/component/scrollview/HippyScrollView.m
ios/sdk/component/view/HippyView.m

refactor(ios): remove deprecated LayoutGuide and update CodeOwner file

---

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/WebSocketModule.java

fix(android): memory leak in `WebSocketModule`

---

ios/sdk/utils/HippyGradientObject.m

thanks to Yao Jiaqi for the feedback

fix(ios): fix potential bug and analyzer issues in HippyGradientObject

---

renderer/tdf/common/CMakeLists.txt
renderer/tdf/common/include/renderer/tdf/devtools/devtools_util.h
renderer/tdf/common/include/renderer/tdf/viewnode/view_node.h
renderer/tdf/common/src/renderer/tdf/devtools/devtools_util.cc
renderer/tdf/common/src/renderer/tdf/viewnode/view_node.cc

feat(devtools): add tdfcore renderer elements debug

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java

fix(android): check imageAdapter result before use

---

dom/include/dom/dom_node.h
renderer/tdf/common/include/renderer/tdf/tdf_render_manager.h
renderer/tdf/common/include/renderer/tdf/viewnode/view_node.h
renderer/tdf/common/src/renderer/tdf/tdf_render_manager.cc
renderer/tdf/common/src/renderer/tdf/viewnode/text_view_node.cc
renderer/tdf/common/src/renderer/tdf/viewnode/view_node.cc

TDFRender bug fix

---

docs/ios/integration.md
framework/ios/base/bridge/HippyBridge.h

docs(ios): update ios integration document

---

docs/ios/event.md

docs(ios): modify ios event document for hippy3.0

---

renderer/native/android/src/main/cpp/src/renderer/native_render_manager.cc

fix(dom): fix delete parent node cause child node nullptr

---

core/third_party/base/include/base/unicode_string_view.h
core/third_party/base/src/base/unicode_string_view.cc

fix(core): fix std hash for xcode15

---

dom/src/dom/animation/animation_manager.cc

fix(dom): fix simultaneous delete and update animation casue nullptr

---

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java

fix(android): animationModule memory leak

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyImageSpan.java
android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyStyleSpan.java
android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
android/sdk/src/main/java/com/tencent/smtt/flexbox/FlexNode.java
android/sdk/src/main/java/com/tencent/smtt/flexbox/FlexNodeStyle.java

fix(android): textNode memory leak

---

renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/component/view/NativeRenderObjectView.mm
renderer/native/ios/utils/NativeRenderUtils.m

fix(ios): fix layout issues

---

framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/executors/HippyJSExecutor.h
framework/ios/base/executors/HippyJSExecutor.mm

refactor(ios): refactor meta source from utf8 to utf16

---

renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/view/NativeRenderObjectView.h
renderer/native/ios/renderer/component/view/NativeRenderObjectView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
renderer/native/ios/utils/NativeRenderUtils.h
renderer/native/ios/utils/NativeRenderUtils.m

fix(ios): child component nested in text should not dirty propagation

---

renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm

fix(ios): change the unit from double to int

---

packages/hippy-react-web/src/components/text.tsx

feat(@hippy/react-web): remove font default style for Text

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java
renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java

fix(android): not support recycle image holder temporary

---

docs/feature/feature3.0/layout.md

docs(doc): add hippy 3.0 layout doc

---

framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): use auto release pool for cpp thread

---

framework/voltron/CHANGELOG.md
framework/voltron/example/lib/base_voltron_page.dart
framework/voltron/example/pubspec.yaml
framework/voltron/lib/adapter/exception.dart
framework/voltron/lib/bridge/voltron_bridge.dart
framework/voltron/lib/engine/js_engine_context.dart
framework/voltron/lib/engine/js_init_params.dart
framework/voltron/lib/inspector/dev.dart
framework/voltron/lib/inspector/dev_server_impl.dart
framework/voltron/lib/inspector/dev_server_impl_disable.dart
framework/voltron/lib/inspector/dev_server_interface.dart
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/lib/common/error.dart
renderer/voltron/pubspec.yaml

feat(voltron): add voltron js error dialog for demo

---

.github/workflows/3rd_prebuilt_v8.yml

chore(build): add v8 windows release build action

---

framework/examples/ios-demo/project.yml

chore(ios): modify ios app bundle identify

---

dom/include/dom/layer_optimized_render_manager.h
dom/src/dom/layer_optimized_render_manager.cc
renderer/voltron/lib/widget/root.dart

fix(dom): fix bug for layer optimize

---

framework/ios/base/bundleoperations/HippyBundleLoadOperation.mm

fix(ios): allocation method should call super

---

driver/js/src/napi/v8/v8_ctx.cc
framework/examples/android-demo/src/main/java/com/openhippy/example/ExampleAPIProvider.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/HippyEngineWrapper.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/turbo/DemoTurboModule.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/turbo/TurboArray.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/turbo/TurboConfig.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/turbo/TurboMap.kt

fix(android,doc): fix turbo object reference and update doc, example

---

docs/development/native-integration.md
settings.gradle

docs(android): update code path in integration doc

---

ios/sdk/base/executors/HippyJSCExecutor.mm

refactor(ios): remove unnessessary codes

---

framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bundleoperations/HippyBundleExecutionOperation.h
framework/ios/base/bundleoperations/HippyBundleExecutionOperation.m
framework/ios/base/bundleoperations/HippyBundleLoadOperation.h
framework/ios/base/bundleoperations/HippyBundleLoadOperation.mm
framework/ios/module/imageloader/HippyImageLoaderModule.mm
framework/ios/module/loader/HippyBridge+VFSLoader.h
framework/ios/module/loader/HippyBridge+VFSLoader.mm
framework/ios/module/loader/HippyFileHandler.h
framework/ios/module/loader/HippyFileHandler.mm
framework/ios/module/network/HippyNetWork.mm
modules/vfs/ios/VFSUriHandler.h
modules/vfs/ios/VFSUriHandler.mm
modules/vfs/ios/VFSUriLoader.h
modules/vfs/ios/VFSUriLoader.mm
renderer/native/ios/renderer/component/image/NativeRenderImageView.m
renderer/native/ios/renderer/component/image/NativeRenderImageViewManager.mm
renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm

feat(ios): add ios bundle load operation queue

---

docs/api/hippy-react/modules.md
docs/api/hippy-vue/vue-native.md
framework/examples/android-demo/src/main/java/com/openhippy/example/PageConfiguration.kt

docs(android): update doc and example for `BackAndroid`

---

.github/workflows/project_artifact_compare.yml
.github/workflows/project_artifact_release.yml

chore(action): add github release and compare action

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): add semaphore to make sure scope is created

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java

feat(android): image add param to `onError`

---

core/src/napi/jsc/jsc_ctx.cc

fix(jsc): fix jsc crash on ios12

---

driver/js/include/driver/vm/js_vm.h
hippy.podspec

refactor(core): reduce header file dependencies

---

.github/workflows/pod_spec_lint.yml
.github/workflows/pod_spec_lint_bypass.yml

chore(ios): add pod spec lint workflow file

---

.github/workflows/pod_spec_lint.yml
.github/workflows/pod_spec_lint_bypass.yml
driver/js/include/driver/vm/js_vm.h

fix(ios): remove the semicolon after namespace syntax

---

.github/workflows/voltron_build_tests.yml
framework/voltron/core/src/bridge/ios/VoltronJSCExecutor.mm

feat(voltron): update voltron workflow

---

ios/sdk/component/listview/HippyBaseListView.m

fix(ios): fix initialContentOffset bug for listview

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java

fix(android): initialContentOffset not working

---

.github/workflows/frontend_build_tests.yml
driver/js/packages/hippy-vue/src/runtime/node-ops.js

fix(vue): fix rootview conditional statement

---

framework/voltron/core/src/bridge/android/bridge_impl.cc

fix(voltron): fix voltron android scope not erase when destroy

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
renderer/native/android/src/main/java/com/tencent/renderer/node/ListItemRenderNode.java

may crash in vue2 when recreating view with same id

fix(android): sticky header not deleted from ControllerManager

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java

fix(android): event to lower case

---

driver/js/src/scope.cc
renderer/native/android/src/main/cpp/src/renderer/native_render_manager.cc

feat(dom): fix empty dom event function crash

---

devtools/devtools-integration/native/src/devtools_utils.cc

fix(devtools): fix location double for all

---

modules/footstone/src/deserializer.cc
renderer/voltron/lib/util/devtools_util.dart

fix(voltron): fix crash when dom value type error

---

dom/src/dom/root_node.cc

fix(dom): fix vue diff style alogrithm

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/StyleNode.java

fix(android): correct default value type for `StyleNode`

---

android/sdk/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/animation/AnimationModule.java

fix(android): animation may cause `IllegalStateException` after destroy

---

renderer/native/ios/renderer/component/view/NativeRenderView.m

fix(ios): fix gradient color drawing bug

---

dom/include/dom/root_node.h
dom/src/dom/root_node.cc
framework/ios/base/bridge/HippyConvenientBridge.mm

feat(ios): add 'SetRootOrigin' function for root node

---

driver/js/include/driver/performance/performance_entry.h
driver/js/include/driver/performance/performance_navigation_timing.h
driver/js/include/driver/performance/performance_resource_timing.h
driver/js/src/modules/performance/performance_entry_module.cc
driver/js/src/modules/performance/performance_frame_timing_module.cc
driver/js/src/modules/performance/performance_mark_module.cc
driver/js/src/modules/performance/performance_measure_module.cc
driver/js/src/modules/performance/performance_module.cc
driver/js/src/modules/performance/performance_navigation_timing_module.cc
driver/js/src/modules/performance/performance_paint_timing_module.cc
driver/js/src/modules/performance/performance_resource_timing_module.cc
driver/js/src/performance/performance.cc
driver/js/src/performance/performance_mark.cc
driver/js/src/performance/performance_measure.cc

fix(perf): fix performance api crash and params

---

docs/hippy-react/components.md
packages/hippy-react/src/components/text.tsx

feat(hippy-react): Text component add forbidUnicodeToChar

---

driver/js/src/modules/event_module.cc

fix(dom): fix event empty pointer

---

driver/js/include/driver/modules/event_module.h
driver/js/include/driver/scope.h
driver/js/src/modules/event_module.cc
driver/js/src/scope.cc

fix(dom): fix modifying event by multi hippy engine

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(jsc): temporarily used for testing jsc crash

---

renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/component/view/UIView+DomEvent.m

refactor(ios): update update node logic

---

framework/voltron/CHANGELOG.md
framework/voltron/android/build.gradle
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/pubspec.yaml

feat(voltron): publish voltron 0.0.31

---

renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/component/view/UIView+DomEvent.m

refactor(ios): need to check diff and delete props for updating view

---

dom/src/dom/root_node.cc

fix(dom): filter nodes with same style

---

dom/src/dom/dom_node.cc

fix(dom): fix dom ext style diff error

---

driver/js/include/driver/vm/v8/memory_module.h
driver/js/src/modules/performance/performance_module.cc
driver/js/src/vm/v8/memory_module.cc

fix(perf): add v8 memory interface for js

---

android/sdk/src/main/java/com/tencent/mtt/supportui/views/asyncimage/AsyncImageView.java

fix(android): prevent unnecessary requestLayout

---

docs/en-us/hippy-react/native-event.md
docs/en-us/hippy-vue/native-event.md
docs/hippy-react/native-event.md
docs/hippy-vue/native-event.md
ios/sdk/base/HippyBatchedBridge.mm
ios/sdk/base/HippyBridge+Private.h
ios/sdk/base/HippyBridge.h
ios/sdk/base/HippyBridge.mm
ios/sdk/base/HippyRootView.mm

feat(ios): add NightMode change event

---

renderer/native/ios/renderer/component/view/NativeRenderTouchesView.m
renderer/native/ios/renderer/component/view/NativeRenderView.h
renderer/native/ios/renderer/component/view/NativeRenderView.m
renderer/native/ios/renderer/component/view/NativeRenderViewManager.mm
renderer/native/ios/renderer/component/view/UIEvent+TouchResponder.h
renderer/native/ios/renderer/component/view/UIEvent+TouchResponder.m
renderer/native/ios/renderer/component/view/UIView+DomEvent.h
renderer/native/ios/renderer/component/view/UIView+DomEvent.m
renderer/native/ios/renderer/component/view/UIView+NativeRender.mm

fix(ios): support intercept touche event

---

renderer/native/ios/renderer/NativeRenderImpl.mm

fix(ios): fix crash caused by null pointer

---

renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/component/image/NativeRenderImageView+NativeRenderTouchesImplementation.mm
renderer/native/ios/renderer/component/view/NativeRenderTouchesProtocol.h
renderer/native/ios/renderer/component/view/NativeRenderTouchesView.m
renderer/native/ios/renderer/component/view/NativeRenderViewEventType.h
renderer/native/ios/renderer/component/view/NativeRenderViewEventType.mm
renderer/native/ios/renderer/component/view/UIView+DomEvent.mm

fix(ios): fix ios event capture and bubbling process

---

dom/src/dom/taitank_layout_node.cc

feat(dom): remove DCHECK for taitank node

---

driver/js/include/driver/performance/performance_navigation_timing.h

fix(perf): fix performance api nav start time bug

---

dom/include/dom/dom_manager.h
dom/src/dom/dom_manager.cc
dom/src/dom/root_node.cc
dom/src/dom/scene_builder.cc
driver/js/include/driver/performance/performance_navigation_timing.h
driver/js/src/modules/performance/performance_navigation_timing_module.cc
driver/js/src/scope.cc

fix(perf): support dom time for performance api

---

framework/examples/ios-demo/HippyDemo/HippyConvenientBridge.mm
framework/ios/base/bridge/HippyBridge.h
renderer/native/ios/renderer/NativeRenderImpl.h
renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/NativeRenderManager.h
renderer/native/ios/renderer/NativeRenderManager.mm

refactor(ios): optimize NativeRenderManager structure

---

renderer/native/ios/renderer/NativeRenderManager.h
renderer/native/ios/renderer/NativeRenderManager.mm

refactor(ios): add interface for nativerendermanager

---

renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/RenderVsyncManager.h
renderer/native/ios/renderer/RenderVsyncManager.m

fix(perf): support fps calculation for js

---

framework/android/connector/driver/js/src/main/cpp/src/java2js.cc

fix(dom): fix call function crash

---

driver/js/include/driver/scope.h
driver/js/src/engine.cc
driver/js/src/modules/animation_module.cc

fix(jsc): fix JSCCtxValue crash after destroy engine

---

dom/CMakeLists.txt

feat(layout): update layout engine version to 1.0.5

---

driver/js/include/driver/vm/jsc/jsc_vm.h
driver/js/src/napi/jsc/jsc_ctx.cc
driver/js/src/vm/jsc/jsc_vm.cc

fix(jsc): fix gc finalize private data invalid crash

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/view/HippyViewGroup.java

fix(android): check overflow visible before setClipChildren

---

driver/js/src/modules/performance/performance_module.cc
driver/js/src/performance/performance_entry.cc
driver/js/src/scope.cc
framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/executors/HippyJSExecutor.mm

fix(perf): fix performance api for ios params

---

ios/sdk/module/animation2/HippyNextAnimationModule.m

fix(ios): animation module multi-instance support

---

ios/sdk/module/animation2/HippyNextAnimationModule.m
ios/sdk/module/animation2/pop/HPOPAnimator.h
ios/sdk/module/animation2/pop/HPOPAnimator.mm

fix(ios): animation module multi-instance support 2

---

.github/CODEOWNERS

chore(workflow): change code owner

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java

fix(android): support focusTextInput event without params

---

dom/include/dom/layout_node.h
dom/include/dom/taitank_layout_node.h
dom/include/dom/yoga_layout_node.h
dom/src/dom/dom_node.cc

fix(layout): fix layout changed error

---

.github/CODEOWNERS

chore(workflow): update code owner

---

framework/examples/ios-demo/HippyDemo/HippyConvenientBridge.mm
framework/examples/ios-demo/HippyDemo/RenderPage/NativeRenderViewController.mm
framework/ios/base/HippyDeviceBaseInfo.mm
renderer/native/ios/renderer/NativeRenderComponentMap.mm
renderer/native/ios/renderer/NativeRenderImpl.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListItemViewManager.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewDataSource.mm
renderer/native/ios/renderer/component/listview/NativeRenderObjectBaseListItem.h
renderer/native/ios/renderer/component/listview/NativeRenderObjectBaseListItem.mm
renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/textinput/NativeRenderObjectTextView.mm
renderer/native/ios/renderer/component/view/NativeRenderObjectView.h
renderer/native/ios/renderer/component/view/NativeRenderObjectView.mm
renderer/native/ios/renderer/component/view/NativeRenderTouchesView.m
renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfall.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfall.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfallItem.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfallItem.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallItemViewManager.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewDataSource.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewDataSource.mm

fix(ios): performance improve

---

packages/hippy-react/src/modules/animation-set.ts

fix(js): remove virtual for animation

---

dom/src/dom/dom_manager.cc

fix(perf): fix performance api dom time bug

---

renderer/native/ios/renderer/NativeRenderImpl.mm

fix(ios): NativeRenderView leak

---

renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm

fix(ios): determines if node is null

---

packages/global.d.ts
packages/hippy-react-web/src/components/list-view.tsx
packages/hippy-react-web/src/components/text-input.tsx
packages/hippy-react-web/src/modules/stylesheet.ts
packages/hippy-react/src/components/list-view.tsx
packages/hippy-react/src/components/text.tsx
packages/hippy-react/src/components/view.tsx
packages/hippy-react/src/modules/stylesheet.ts
packages/hippy-react/src/types/index.ts

fix(hippy-react-web): HippyTypes.Style for web

---

driver/js/include/driver/scope.h
framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(perf): fix resource entry nullptr crash

---

dom/include/dom/dom_node.h
dom/include/dom/layer_optimized_render_manager.h
dom/src/dom/layer_optimized_render_manager.cc

fix(core): fix performance for node eliminated

---

dom/src/dom/dom_node.cc
dom/src/dom/root_node.cc

fix(core): fix performance for dom node

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java

feat(android): optimize addUpdateNodeIfNeeded time cost

---

modules/android/serialization/src/main/java/com/tencent/mtt/hippy/serialization/string/InternalizedStringTable.java

fix(android): fix serialization hash function

---

dom/src/dom/dom_node.cc

feat(dom): fix trigger error on layout event

---

dom/include/dom/animation/animation_manager.h
dom/include/dom/dom_manager.h
dom/include/dom/root_node.h
dom/src/dom/animation/animation_manager.cc
dom/src/dom/dom_manager.cc
dom/src/dom/root_node.cc

fix(ios): fix create node crash in main thread when releasing vc

---

renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java

fix(android): support webp

---

dom/src/dom/dom_node.cc

fix(dom): fix layout event trigger condition

---

renderer/native/android/src/main/java/com/tencent/renderer/node/VirtualNodeManager.java

fix(android): delete virtual node exception

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/RenderManager.java
renderer/native/android/src/main/java/com/tencent/renderer/node/RenderNode.java

fix(android): move node incorrect in `ViewPager`

---

renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java

fix(android): remove extra logs

---

framework/voltron/CHANGELOG.md
framework/voltron/pubspec.yaml
renderer/voltron/CHANGELOG.md
renderer/voltron/lib/render/manager.dart
renderer/voltron/lib/viewmodel/modal.dart
renderer/voltron/pubspec.yaml

feat(voltron): update voltron to 0.0.34

---

examples/hippy-react-demo/package.json
examples/hippy-vue-demo/package.json
examples/hippy-vue-next-demo/package.json

chore(demo): change demo latest version

---

modules/android/pool/src/main/java/com/openhippy/pool/ImageRecycleObject.java
renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java

fix(android): isScraped not check image type

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/viewpager/ViewPagerPageChangeListener.java
renderer/native/android/src/main/java/com/tencent/renderer/utils/EventUtils.java

fix(android): sendComponentEvent with view==null crash

---

core/include/core/modules/module_register.h
core/src/modules/console_module.cc
core/src/modules/contextify_module.cc
core/src/modules/timer_module.cc
core/src/scope.cc

fix(core): fix global strip when ld in app

---

renderer/native/ios/renderer/component/view/NativeRenderObjectView.mm

fix(ios): fix missing updateLayout operation

---

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(dom): get scope return nullptr

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java

fix(android): add bridge destroy state

---

driver/js/src/js_driver_utils.cc

fix(v8): fix v8 code cache for hippy3.0

---

framework/android/connector/dom/src/main/cpp/src/dom_jni.cc
framework/android/connector/dom/src/main/java/com/openhippy/connector/DomManager.java
modules/footstone/include/footstone/worker.h
modules/footstone/src/worker.cc

feat(dom): set dom thread priority

---

modules/vfs/ios/VFSUriLoader.mm

fix(vfs): fix VFSUriLoader crash

---

modules/footstone/src/task_runner.cc

fix(core): crash protect for worker on ios

---

driver/js/packages/hippy-vue/src/renderer/element-node.js
driver/js/packages/hippy-vue/src/renderer/native/index.js

feat(vue): not update node when add/remove listener

---

driver/js/packages/hippy-vue/src/renderer/native/index.js

feat(vue): remove updateEvent params

---

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(driver): fix destroy driver before scope initialization

---

android/sdk/src/main/jni/src/bridge/entry.cc
core/include/core/base/file.h
core/src/base/file.cc

fix(v8): v8 code cache file broken protect

---

core/src/modules/console_module.cc

fix(core): fix console module log encode

---

README.md

feat(doc): update main branch homepage url

---

dom/src/dom/dom_node.cc

fix(dom): handle event by platform

---

renderer/native/ios/renderer/component/modal/NativeRenderModalHostViewManager.mm

fix(ios): fix modal view layout issue

---

dom/src/dom/root_node.cc
driver/js/src/modules/scene_builder_module.cc
driver/js/src/napi/jsc/jsc_ctx.cc
framework/ios/base/bridge/HippyBridge.mm
modules/footstone/include/footstone/logging.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm

fix(ios): remove highly frequent logs

---

framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.mm
framework/examples/ios-demo/podfile
framework/ios/base/bridge/HippyBridge.mm
renderer/native/ios/renderer/HippyRootView.h
renderer/native/ios/renderer/HippyRootView.mm

fix(ios): relayout dom when rootView frame change

---

framework/examples/ios-demo/HippyDemo/TestModule.mm
framework/examples/ios-demo/podfile
hippy.podspec

fix(ios): podspec use_framework support bug

---

framework/ios/base/bundleoperations/HippyBundleOperationQueue.m
renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): fix uimanager and bundle operation queue's crash

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java

fix(android): update props reuse null view object

---

driver/js/packages/hippy-vue/src/renderer/native/index.js

fix(vue): fix not update style diff crash

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/HippyRootView.java
renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java

fix(android): send onSizeChanged message to js

---

framework/examples/android-demo/src/main/java/com/openhippy/example/ExampleAPIProvider.kt
framework/examples/android-demo/src/main/java/com/openhippy/example/ExampleCustomPropsController.kt
renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java

fix(android): should create view if has custom props

---

dom/src/dom/root_node.cc
driver/js/src/modules/scene_builder_module.cc
modules/footstone/include/footstone/logging.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm

fix(android): fix compile issue in AS release mode

---

renderer/native/ios/renderer/component/webview/NativeRenderSimpleWebView.h
renderer/native/ios/renderer/component/webview/NativeRenderSimpleWebView.m
renderer/native/ios/renderer/component/webview/NativeRenderSimpleWebViewManager.mm

fix(ios): add user agent and method support

---

renderer/native/ios/renderer/component/textinput/NativeRenderTextField.m

fix(ios): reload textfield to take effect after altering returnKeyType

---

framework/ios/module/dev/HippyRedBox.mm
renderer/native/ios/renderer/component/refreshview/NativeRenderRefreshWrapperViewManager.mm
renderer/native/ios/renderer/component/textinput/NativeRenderTextViewManager.mm
renderer/native/ios/renderer/component/view/HippyViewManager.h
renderer/native/ios/renderer/component/view/HippyViewManager.mm

fix(ios): add type exist check and fix bugs

---

renderer/native/ios/renderer/component/textinput/NativeRenderTextField.m

fix(ios): reaload textfield after changing keyboardType

---

docs/api/hippy-react/components.md

fix(doc): remove unused animated property definition from docs

---

renderer/native/ios/renderer/component/textinput/NativeRenderTextField.m
renderer/native/ios/renderer/component/textinput/NativeRenderTextView.mm
renderer/native/ios/renderer/component/textinput/NativeRenderTextViewManager.mm

fix(ios): add caretColor property support

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java

fix(android): support host override notifyInitialListReady

---

framework/examples/ios-demo/HippyDemo/Info.plist
renderer/native/ios/renderer/component/modal/HippyModalHostView.m
renderer/native/ios/renderer/component/modal/HippyModalTransitioningDelegate.m

fix(ios): make use of darkStatusBarText property in modal controller

---

renderer/native/ios/renderer/component/image/HippyImageView.m

fix(ios): fix image animation stop issue after setting tintColor

---

renderer/native/ios/renderer/HippyUIManager+Private.h
renderer/native/ios/renderer/HippyUIManager.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm

refactor(ios): refactor uimanger's code and structure

---

framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.mm
framework/ios/base/bridge/HippyBridge.mm
modules/footstone/include/footstone/logging.h
modules/ios/base/HippyLog.mm

fix(ios): set logging delegate

---

framework/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/NetworkModule.java

fix(android): use promise.reject when fetch res failed

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java

fix(android): fix premature text truncation

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java

fix(android): fix `overScrollEnabled` can't cancel the system effect

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
renderer/native/android/src/main/java/com/tencent/renderer/node/RenderNode.java
renderer/native/android/src/main/java/com/tencent/renderer/node/VirtualNodeManager.java

feat(android): support padding for `TextInput`

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java

fix(android): dimensions api compatibility with lower version

---

docs/api/hippy-react/components.md
docs/api/hippy-vue/components.md
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java

feat(android,doc): `returnKeyType`,`keyboardType` not change singleLine

---

packages/hippy-react/src/components/scroll-view.tsx
packages/hippy-react/src/components/web-view.tsx
packages/hippy-react/src/modules/animation.ts

fix(hippy-react): fix declaration for animation and scroll-view

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java

fix(android): crash when rotating screen in dev mode

---

framework/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/image/ImageLoaderModule.java

BREAKING CHANGE:: failure parameter on Android used to be a String, now is an object

fix(android)!: change Image getSize failure parameter type

---

framework/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/HippyNativeModuleInfo.java

fix(android): compatible with the HippyModulePromise type

---

dom/src/dom/deserializer_unittests.cc
dom/src/dom/dom_argument.cc
dom/src/dom/dom_manager.cc
dom/src/dom/serializer_unittests.cc
modules/footstone/include/footstone/serializer.h
renderer/native/android/src/main/cpp/src/renderer/native_render_manager.cc

fix(dom): fix dom memory leak

---

renderer/native/ios/renderer/component/webview/NativeRenderSimpleWebView.m

fix(ios): add local html, request body support to WebView

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(core): JSCCtx CreateObject crash protect

---

renderer/native/ios/renderer/HippyRootView.mm

fix(ios): Fine-tune callback timing to stay compatible with hippy2

---

docs/hippy-vue/external-components.md
docs/hippy-vue/vue3.md

feat(vue): update vue3 & vue animation doc

---

framework/android/proguard-rules.pro

fix(android): update proguard-rules

---

renderer/native/ios/renderer/HippyRootView.h
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.h
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewManager.mm
renderer/native/ios/renderer/component/listview/NativeRenderListTableView.h
renderer/native/ios/renderer/component/scrollview/HippyScrollView.h
renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.h
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm

fix(ios): final onScroll may be dropped for listview, scrollview and waterfall

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/dom/node/NodeProps.java
renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/TextDrawable.java
renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextDecorationSpan.java
renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextImageSpan.java
renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextLineMetricsHelper.java
renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextShadowSpan.java
renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextVerticalAlignSpan.java
renderer/native/android/src/main/java/com/tencent/renderer/node/ImageVirtualNode.java
renderer/native/android/src/main/java/com/tencent/renderer/node/TextVirtualNode.java
renderer/native/android/src/main/java/com/tencent/renderer/node/VirtualNode.java

* support `textDecorationColor` and `textDecorationStyle` props
* improve `verticalAlign` with line-breaking

feat(android): support text decoration features

---

renderer/native/ios/renderer/HippyUIManager.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/modal/HippyModalHostView.m

fix(ios): fix modal view display issue in landscape mode

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/DomManager.java

fix(android): too many dispatch-tasks in background may cause anr

---

docs/api/hippy-react/components.md
docs/api/hippy-vue/components.md
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java

feat(android): deprecate `underlineColorAndroid` prop

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm

fix(ios): fix weak ref issue in closure

---

modules/ios/base/HippyLog.mm

fix(ios): prevent crash even logger cbset multiple times

---

renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm

fix(ios): optimize cell creation time of listview and waterfall

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngine.java

fix(android): remove debugBundleName final constraint

---

renderer/native/android/src/main/java/com/tencent/renderer/node/RenderNode.java

fix(android): component may not update with lazy node

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java

fix(android): fix `ListView` may throw `ClassCastException`

---

framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
renderer/native/ios/renderer/HippyRootView.h
renderer/native/ios/renderer/HippyRootView.mm

refactor(ios): optimized the startup process and compatibility

---

renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewManager.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewManager.mm

fix(ios): scrollToIndex not working for horizontal list

---

packages/global.d.ts

fix(hippy-react): fix TransformsStyle declaration

---

renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm

fix(ios): dead loops generated by nested text layouts

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm

fix(ios): sticky list cell not showing after reloading

---

framework/android/build.gradle
renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java
renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/ContentDrawable.java
renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/NinePatchHelper.java
renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageComponentController.java
renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java

feat(android): capInsets and tintColor support for each image types

---

packages/global.d.ts

fix(hippy-react): fix GenericStyleProp recursive problem

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/LayoutHelper.java

fix(android): prevent layout helper queue hold too many objects

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/RecyclerViewEventHelper.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListItemView.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/list/HippyListView.java
renderer/native/android/src/main/java/com/tencent/renderer/node/ListItemRenderNode.java

feat(android): support appear events for ListView

---

renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm

fix(ios): add protection to prevent crashes caused by negative sizes

---

dom/src/dom/dom_node.cc

fix(dom): convert layout result nan to 0

---

docs/guide/integration.md

chore(doc): add copy instruction for android

---

dom/src/dom/dom_node.cc

fix(dom): layout width and height result great than 0

---

devtools/devtools-integration/native/include/devtools/devtools_utils.h
devtools/devtools-integration/native/src/devtools_utils.cc
renderer/native/android/src/main/cpp/src/renderer/native_render_jni.cc

fix(devtools): fix dom box size return (0,0,0,0)

---

renderer/native/ios/renderer/component/view/HippyViewManager.mm

fix(ios): fixed an error when getBoundingClientRect's options was NSNull

---

renderer/native/ios/renderer/HippyFont.mm

feat(ios): improve text layout performance

---

framework/ios/base/HippyDisplayLink.m

fix(ios): fix HippyDisplayLink leak

---

renderer/native/ios/renderer/HippyComponent.h
renderer/native/ios/renderer/HippyComponentMap.h
renderer/native/ios/renderer/HippyComponentMap.mm
renderer/native/ios/renderer/HippyUIManager.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListView.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewDataSource.mm
renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewManager.mm
renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.mm
renderer/native/ios/renderer/component/text/NativeRenderObjectText.mm
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/UIView+DirectionalLayout.mm
renderer/native/ios/renderer/component/view/UIView+Hippy.mm
renderer/native/ios/renderer/component/waterfalllist/HippyShadowListView.h
renderer/native/ios/renderer/component/waterfalllist/HippyShadowListView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewDataSource.h
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewDataSource.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallViewManager.mm

fix(ios): refactor & fix listview and waterfall's data loading procedure

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): crash of NSError out param inside autorelease pool

---

renderer/native/ios/renderer/component/textinput/NativeRenderTextField.m

fix(ios): onChange event not triggered when typing Chinese Pinyin

---

renderer/native/ios/renderer/HippyFont.mm

fix(ios): return weight of zero for invalid font

---

docs/android/custom-component.md

chore(docs): android custom native view how to layout spec

---

renderer/native/ios/renderer/HippyComponentMap.h
renderer/native/ios/renderer/HippyComponentMap.mm
renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): optimize performance of getting components from viewRegistry

---

packages/hippy-vue-next/src/runtime/websocket/websocket.ts

fix(vue-next): remove unnecessary websocket binding judge

---

examples/ios-demo/HippyDemo/ViewController.m

chore(ios): demo log format

---

renderer/native/ios/renderer/HippyFont.mm
renderer/native/ios/renderer/NativeRenderManager.mm
renderer/native/ios/renderer/component/text/HippyShadowText.h
renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/text/HippyText.h
renderer/native/ios/renderer/component/text/HippyText.mm
renderer/native/ios/renderer/component/text/HippyTextManager.h
renderer/native/ios/renderer/component/text/HippyTextManager.mm
renderer/native/ios/renderer/component/textinput/NativeRenderTextView.mm
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/view/HippyViewManager.mm
renderer/native/ios/utils/HippyConvert+NativeRender.h
renderer/native/ios/utils/HippyConvert+NativeRender.m

fix(ios): revert rename hippy prefix for compatibility

---

examples/hippy-vue-next-demo/scripts/hippy-webpack.android-vendor.js
examples/hippy-vue-next-demo/scripts/hippy-webpack.android.js
examples/hippy-vue-next-demo/scripts/hippy-webpack.ios-vendor.js
examples/hippy-vue-next-demo/scripts/hippy-webpack.ios.js

fix(vue-next): remove vue prod devtools global sign for ios&android

---

android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/libraryloader/LibraryLoader.java
android/sdk/src/main/java/com/tencent/mtt/hippy/utils/BuglyUtils.java
examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
layout/android/java/com/tencent/smtt/flexbox/FlexNode.java

feat(android): add bugly app id register

---

framework/examples/ios-demo/HippyDemo/Info.plist

chore(ios): fix demo build problem

---

android/sdk/build.gradle
android/sdk/gradle.properties
android/sdk/src/main/java/com/tencent/mtt/hippy/utils/BuglyUtils.java

feat(android): add ENABLE_BUGLY_REPORT config

---

renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm

fix(ios): showsXXXScrollIndicator property of scrollview not working

---

framework/ios/module/dev/HippyRedBox.h
renderer/native/ios/renderer/HippyComponent.h
renderer/native/ios/renderer/HippyRootView.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/modal/HippyModalHostViewManager.h
renderer/native/ios/renderer/component/modal/HippyModalHostViewManager.mm
renderer/native/ios/renderer/component/modal/HippyModalTransitioningDelegate.h
renderer/native/ios/renderer/component/modal/HippyModalTransitioningDelegate.m
renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm
renderer/native/ios/renderer/component/view/HippyShadowView+Internal.h
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/HippyViewManager.mm
renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
renderer/native/ios/utils/NativeRenderGradientObject.m

refactor(ios): eliminate code warnings and resolve architectural issues

---

renderer/native/ios/renderer/HippyComponentMap.h
renderer/native/ios/renderer/HippyComponentMap.mm
renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): optimize perf of ComponentMap and support multi-rootView

---

framework/examples/ios-demo/HippyDemo/Info.plist

chore(ios): update demo info.plist file

---

framework/voltron/CHANGELOG.md
framework/voltron/lib/inspector/dev_remote_server_data.dart
framework/voltron/pubspec.yaml
framework/voltron/test/flutter_render_test.dart

fix(voltron): resolve remoteServerUrl parse version id failed

---

modules/vfs/android/src/main/cpp/src/handler/jni_delegate_handler.cc

fix(vfs): OnJniDelegateInvokeSync call after OnDestroyVfs

---

dom/src/dom/taitank_layout_node.cc

fix(layout): fix layout border default css direction

---

modules/footstone/include/footstone/deserializer.h
modules/footstone/src/deserializer.cc
renderer/native/android/src/main/cpp/src/renderer/native_render_jni.cc

fix(dom): add log for deserializer crash

---

modules/footstone/include/footstone/deserializer.h
modules/footstone/src/deserializer.cc

fix(dom): add deserializer log

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/common/LogAdapter.java
renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderDelegate.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
renderer/native/android/src/main/java/com/tencent/renderer/RenderLogHandler.java

feat(android): support output render log to host

---

modules/footstone/include/footstone/deserializer.h
modules/footstone/src/deserializer.cc

fix(dom): remove some redunant log

---

docs/development/native-integration.md

docs(ios): update iOS integration guide

---

modules/ios/base/HippyUtils.h

chore(ios): fix typos and update code comment

---

ios/sdk/component/image/HippyImageView.m

fix(ios): images with non-encoded urls are not displayed

---

ios/sdk/base/HippyBridge.mm

fix(ios): a rare multithreaded race crash when getting  imageProviders

---

android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyNativeGestureSpan.java
android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/NativeGestureDispatcher.java
android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/NativeGestureProcessor.java

feat(android): add raw point for touch event dispatch

---

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/NativeGestureDispatcher.java

fix(android): change raw name to window

---

driver/js/packages/hippy-vue-next/src/patch-prop.ts

fix(vue-next): compatible vue patchProp parameter type change

---

android/sdk/src/main/java/com/tencent/mtt/hippy/views/scroll/HippyHorizontalScrollView.java

fix(android): remove override getOverScrollMode

---

android/sdk/src/main/jni/include/loader/adr_loader.h
android/sdk/src/main/jni/src/loader/adr_loader.cc

fix(core): fix ADRLoader multithread bug

---

ios/sdk/component/text/HippyTextManager.mm

Remove the unncessary message from log

fix(ios): remove the invalid log message

---

docs/api/hippy-vue/style.md
driver/js/packages/hippy-vue/src/renderer/element-node.ts

feat(vue): vue component support beforeLoadStyle disabled

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java

fix(android): should hide soft input even input not focus

---

ios/sdk/module/animation2/HippyNextAnimationModule.m

fix(ios): animation state of some scenes might be out of sync

---

ios/sdk/module/animation2/pop/HPOPBasicAnimationInternal.h

fix(ios): add a null protection to animator

---

android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ScrollViewRenderNode.java

fix(android): add ScrollViewRenderNode

---

renderer/native/ios/renderer/HippyComponentData.h
renderer/native/ios/renderer/HippyComponentData.mm
renderer/native/ios/renderer/HippyRootView.mm
renderer/native/ios/renderer/HippyRootViewDelegate.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListItemView.m
renderer/native/ios/renderer/component/listview/HippyNextBaseListView.h
renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListViewCell.h
renderer/native/ios/renderer/component/listview/HippyNextBaseListViewDataSource.mm
renderer/native/ios/renderer/component/listview/HippyNextListTableView.h
renderer/native/ios/renderer/component/refresh/HippyRefresh.h
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.h
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.mm
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.h
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewDataSource.h
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewDataSource.mm

fix(ios): increase code robustness and compatibility

---

devtools/devtools-backend/include/api/adapter/devtools_screen_adapter.h
devtools/devtools-backend/include/api/adapter/devtools_tracing_adapter.h
devtools/devtools-backend/include/tunnel/net_channel.h
dom/include/dom/layout_node.h
modules/footstone/include/footstone/logging.h

build(ios): fix std::function build error on Xcode15.3

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerView.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java

feat(android): add enableScrollDirectionFix for recycler view

---

modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/LogUtils.java
renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java

fix(android): concat log msg only in debug mode

---

driver/js/src/napi/jsc/jsc_ctx.cc
framework/ios/base/bridge/HippyBridge.mm
modules/ios/base/HippyLog.mm
renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm

feat(ios): print hippy core module logs

---

renderer/native/ios/renderer/component/image/HippyImageViewManager.mm

fix(ios): implementation issue with defaultSource prop of Image

---

packages/hippy-vue-next/__test__/runtime/element/hippy-element.test.ts
packages/hippy-vue-next/src/runtime/component/index.ts

feat(vue-next): compatible vue2 component tag name format

---

packages/hippy-vue-next/src/runtime/text/hippy-text.ts

feat(vue): fix vue2 HippyText setText

---

renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): thread race of componentDataByName in UIManager

---

.github/CODEOWNERS
framework/examples/ios-demo/podfile
hippy.podspec
renderer/native/ios/renderer/HippyUIManager+Private.h
renderer/native/ios/renderer/HippyUIManager.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm
tests/ios/HippyUIManagerTest.mm

test(ios): add unit test infrastructure for ios project

---

docs/api/hippy-react/components.md
docs/development/3.0-upgrade-guidelines.md
docs/development/native-integration.md

docs(ios): add iOS 3.0 upgrade guide

---

docs/development/react-vue-3.0-upgrade-guidelines.md

feat(doc): fix docs markdown lint

---

docs/development/ios-3.0-upgrade-guidelines.md

docs(ios): update upgrade guidelines of iOS

---

ios/sdk/module/animation/HippyExtAnimationModule.m

fix(ios): avoid deadlock in special scenarios in animation module

---

docs/development/react-vue-3.0-upgrade-guidelines.md
driver/js/packages/hippy-vue-next-compiler-ssr/package.json
driver/js/packages/hippy-vue-next-server-renderer/package.json
driver/js/packages/hippy-vue-next/package.json
driver/js/packages/hippy-vue/package.json

chore(release): modify npm publish config

---

.github/workflows/project_artifact_snapshot.yml

chore(action): add project_artifact_snapshot.yml

---

.github/workflows/project_artifact_snapshot.yml

fix(action): change project_artifact_snapshot name

---

docs/development/android-3.0-integration-guidelines.md

docs(android): update android snapshot 3.2.0 version

---

renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): tiny issue of  TransactionListener in UIManager

---

docs/en-us/guide/jsi.md
docs/guide/jsi.md
examples/hippy-react-demo/src/main.js
examples/ios-demo/HippyDemo/TestModule.m
ios/sdk/base/HippyBatchedBridge.mm
ios/sdk/base/HippyBridge.h
ios/sdk/base/HippyBridge.mm

fix(ios): turbo module not get called on destroyInstance event

---

docs/README.md

feat(doc): add README.md doc

---

driver/js/packages/hippy-vue/src/util/index.ts

feat(vue): fix vue replace &nbsp

---

modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java
modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/PixelUtil.java

fix(android): support use custom DisplayMetrics

---

ios/sdk/component/view/HippyView.m

perf(ios): draw backgroundImage asynchronously for performance

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java

fix(android): getScreenShot bitmap width or height < 0

---

ios/sdk/component/view/HippyView.m
ios/sdk/debug/devtools/inspector/model/HippyPageModel.m

fix(ios): avoid zero size crash when using UIGraphics api in debug mode

---

.github/workflows/3rd_prebuilt_v8.yml

feat(action): update v8 compiler action

---

dom/src/dom/taitank_layout_node.cc
framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.mm
framework/ios/base/HippyKeyCommands.h
framework/ios/base/HippyKeyCommands.m
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/bridge/HippyBridgeDelegate.h
framework/ios/module/dev/HippyDevMenu.h
framework/ios/module/dev/HippyDevMenu.mm
modules/footstone/include/footstone/logging.h
modules/ios/base/HippyUtils.h
modules/ios/base/HippyUtils.m
renderer/native/ios/renderer/HippyComponent.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/UIView+Hippy.mm
renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm
renderer/native/ios/renderer/component/waterfalllist/HippyShadowListView.mm

Sync some bug fixes and optimizations

---

ios/sdk/component/viewPager/HippyViewPager.m

feat(ios): pageIndex of ViewPager auto update after data changes

---

.husky/post-checkout
.husky/post-commit
.husky/post-merge
.husky/pre-push

chore(build): update husky commit hook command

---

framework/ios/module/turbo/HippyOCTurboModule.mm

fix(ios): null exception when converting JSI object to dictionary

---

ios/sdk/component/viewPager/HippyViewPager.m

fix(ios): auto-update of page index may lag by one frame in view pager

---

framework/ios/base/bridge/HippyBridge.mm
tests/ios/HippyBridgeTest.mm

refactor(ios): non-standard url support of bundle loading

---

driver/js/include/driver/js_driver_utils.h
driver/js/src/js_driver_utils.cc
framework/android/connector/driver/js/src/main/cpp/include/connector/js_driver_jni.h
framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
framework/android/connector/driver/js/src/main/java/com/openhippy/connector/JsDriver.java
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridge.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManager.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java

fix(devtool): fix muli devtool instance crash on android

---

.github/workflows/ios_build_tests.yml
renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): multi-threading issue in createView

---

driver/js/packages/hippy-vue-next/src/runtime/element/hippy-element.ts

feat(vue-next): modify comment

---

driver/js/src/vm/v8/v8_vm.cc

feat(v8): add version log for v8

---

ios/sdk/module/turbo/HippyTurboModuleManager.mm

fix(ios): make getTurboModule return null when module not exist

---

ios/sdk/component/viewPager/HippyViewPager.m

fix(ios): add protection for targetContentOffset outliers in ViewPager

---

dom/src/dom/animation/animation_manager.cc

fix(ios): animation nullptr crash

---

renderer/native/android/src/main/java/com/tencent/renderer/node/RenderNode.java

fix(android): should updateExtra after create host view

---

dom/src/dom/animation/animation_manager.cc
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/modules/HippyModuleMethod.mm
renderer/native/ios/renderer/HippyComponentData.mm
renderer/native/ios/renderer/HippyComponentMap.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListItemViewManager.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListViewManager.mm
renderer/native/ios/renderer/component/modal/HippyModalHostViewManager.mm
renderer/native/ios/renderer/component/text/HippyTextManager.mm
renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm
renderer/native/ios/renderer/component/view/HippyViewManager.h
renderer/native/ios/renderer/component/view/HippyViewManager.mm
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallItemViewManager.m
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.m

sync from main

---

ios/sdk/base/HippyTouchHandler.m

fix(ios): resolve exception where touchView may be nil

---

framework/ios/base/bridge/HippyBridge.mm

fix(ios): resolve null pointer crash when loadBundleURL

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(ios): resolve non-standard object type when creating js object

---

driver/js/src/napi/jsc/jsc_ctx.cc
framework/ios/base/bridge/HippyBridge.mm

sync changes

---

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc

fix(perf): fix OnResourceLoadEnd crash

---

.github/CODEOWNERS
.husky/post-checkout
.husky/post-commit
.husky/post-merge
.husky/pre-push
docs/en-us/guide/jsi.md
docs/guide/jsi.md
examples/hippy-react-demo/src/main.js
examples/ios-demo/HippyDemo/TestModule.m
ios/sdk/base/HippyBatchedBridge.mm
ios/sdk/base/HippyBridge.h
ios/sdk/base/HippyBridge.mm
ios/sdk/base/HippyDeviceBaseInfo.m
ios/sdk/base/HippyTouchHandler.m
ios/sdk/component/image/HippyDefaultImageProvider.m
ios/sdk/component/view/HippyBackgroundImageCacheManager.m
ios/sdk/component/view/HippyShadowView.mm
ios/sdk/component/view/HippyView.m
ios/sdk/component/view/HippyViewManager.mm
ios/sdk/component/viewPager/HippyViewPager.m
ios/sdk/component/waterfalllist/HippyCollectionViewWaterfallLayout.m
ios/sdk/debug/devtools/inspector/model/HippyPageModel.m
ios/sdk/layout/x5LayoutUtil.m
ios/sdk/module/turbo/HippyTurboModuleManager.mm

sync changes from master

---

hippy.podspec

build(ios): resolve module build issue

---

android/sdk/src/main/jni/src/jni/convert_utils.cc

fix(android): resolve local ref overflow

---

driver/js/src/scope.cc

fix(core): fix android scope crash

---

PrivacyInfo.xcprivacy

chore(ios): add PrivacyInfo config for iOS

---

renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm

fix(ios): add CSS name matching semantics to fontFamily of TextInput

---

docs/development/_sidebar.md
docs/development/react-vue-3.0-integration-guidelines.md
docs/development/react-vue-3.0-upgrade-guidelines.md

feat(doc): update js doc

---

ios/sdk/component/textinput/HippyTextView.mm

fix(ios): responsible region issue of multi-line TextInput

---

framework/ios/base/bridge/HippyBridgeDelegate.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/touch_handler/HippyTouchHandler.h
renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

refactor(ios): add gesture event delegate for hippyBridge

---

docs/development/react-vue-3.0-upgrade-guidelines.md

feat(doc): update js doc for 3.3

---

framework/ios/base/bridge/HippyBridge+PerformanceAPI.h
framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm
framework/ios/base/bridge/HippyBridge.mm
renderer/native/ios/renderer/HippyRootView.mm
renderer/native/ios/renderer/component/view/HippyViewManager.mm
renderer/native/ios/renderer/component/view/UIView+MountEvent.m

fix(ios): performance api of FP not working

---

driver/js/examples/hippy-react-demo/src/components/Text/index.jsx
driver/js/examples/hippy-vue-demo/src/components/demos/demo-p.vue
driver/js/packages/hippy-react/src/dom/element-node.ts
driver/js/packages/hippy-react/src/renderer/render.ts
driver/js/packages/hippy-react/src/utils/index.ts
driver/js/packages/hippy-react/src/utils/node.ts
driver/js/packages/hippy-vue/src/native/index.ts
driver/js/packages/hippy-vue/src/renderer/element-node.ts
driver/js/packages/hippy-vue/src/util/node.ts

feat(react): add font style inherit

---

driver/js/packages/hippy-vue/src/native/index.ts

feat(vue): fix default native style is empty

---

driver/js/examples/hippy-react-demo/src/components/TextInput/index.jsx
driver/js/examples/hippy-vue-demo/src/components/demos/demo-textarea.vue
renderer/native/ios/renderer/component/textinput/HippyShadowTextView.h
renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm
renderer/native/ios/renderer/component/textinput/HippyTextField.h
renderer/native/ios/renderer/component/textinput/HippyTextField.m
renderer/native/ios/renderer/component/textinput/HippyTextView.h
renderer/native/ios/renderer/component/textinput/HippyTextView.mm
renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm

feat(ios): add paragraph styles support for TextInput

---

ios/sdk/module/animation2/pop/HPOPAnimator.mm

fix(ios): resolve a multithreading issue in Animator

---

examples/hippy-react-demo/src/components/TextInput/index.jsx
examples/hippy-vue-demo/src/components/demos/demo-textarea.vue
ios/sdk/component/textinput/HippyShadowTextView.h
ios/sdk/component/textinput/HippyShadowTextView.mm
ios/sdk/component/textinput/HippyTextField.h
ios/sdk/component/textinput/HippyTextField.m
ios/sdk/component/textinput/HippyTextView.h
ios/sdk/component/textinput/HippyTextView.mm
ios/sdk/component/textinput/HippyTextViewManager.mm
ios/sdk/module/animation2/pop/HPOPAnimator.mm

sync changes to 2.17.x

---

docs/development/react-vue-3.0-upgrade-guidelines.md

chore(doc): update hippy 3.3.0 doc

---

renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefresh.m
renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefresh.m
renderer/native/ios/renderer/component/refresh/HippyRefresh.h
renderer/native/ios/renderer/component/refresh/HippyRefresh.m
renderer/native/ios/renderer/component/textinput/HippyTextField.h
renderer/native/ios/renderer/component/textinput/HippyTextField.m
renderer/native/ios/renderer/component/textinput/HippyTextView.h
renderer/native/ios/renderer/component/textinput/HippyTextView.mm

Sync Changes to v3.3.x

---

docs/development/react-vue-3.0-upgrade-guidelines.md

fix(doc): fix markdown lint

---

android/sdk/src/main/jni/src/jni/turbo_module_manager.cc

fix(core): GetTurboModule crash protect

---

ios/sdk/module/animation2/HippyNextAnimationModule.m

fix(ios): add a null protection to animation target (new anim module)

---

driver/js/examples/hippy-vue-demo/src/components/native-demos/demo-waterfall.vue
driver/js/examples/hippy-vue-next-demo/src/components/native-demo/demo-waterfall.vue
driver/js/packages/hippy-react/src/components/waterfall-view.tsx

feat(js): fix waterfall for iOS and ohos

---

ios/sdk/base/executors/HippyJSCExecutor.mm
ios/sdk/module/animation2/pop/HPOPAnimator.mm

chore(ios): code quality improve

---

driver/js/packages/hippy-vue-next/src/runtime/element/hippy-element.ts

fix(devtools): fix vue3 devtools element

---

driver/js/examples/hippy-react-demo/package.json
driver/js/examples/hippy-vue-demo/package.json
driver/js/examples/hippy-vue-next-demo/package.json

feat(demo): update demo dependency

---

modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/DimensionsUtil.java
modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/PixelUtil.java

fix(android): add custom display metrics

---

framework/android/src/main/java/com/tencent/mtt/hippy/bridge/jsi/TurboModuleManager.java
framework/android/src/main/java/com/tencent/mtt/hippy/common/ThreadExecutor.java

fix(android): use weak reference replace strong

---

driver/js/src/scope.cc
framework/ios/debug/websocket/HippySRWebSocket.m
framework/ios/utils/NSObject+CtxValue.mm

chore(ios): eliminate code warnings

---

renderer/native/ios/renderer/HippyComponent.h
renderer/native/ios/renderer/HippyRootShadowView.mm
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
renderer/native/ios/renderer/component/smartViewPager/NativeRenderSmartViewPagerView.mm
renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/text/HippyText.mm
renderer/native/ios/renderer/component/text/HippyTextManager.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/UIView+DirectionalLayout.mm
renderer/native/ios/renderer/component/view/UIView+Hippy.mm
renderer/native/ios/renderer/component/waterfalllist/HippyShadowWaterfallItem.m
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm

refactor(ios): use hippySubviews prop for compatibility

---

renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
renderer/native/ios/renderer/component/waterfalllist/HippyShadowWaterfallItem.h
renderer/native/ios/renderer/component/waterfalllist/HippyShadowWaterfallItem.m
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm

fix(ios): remove invalid if statement at cell reuse

---

ios/sdk/component/viewPager/HippyViewPager.m

Sync Changes to 2.15.x

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
renderer/native/ios/renderer/component/textinput/HippyTextView.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/HippyView.m
renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm
renderer/native/ios/renderer/component/waterfalllist/HippyShadowWaterfallItem.m
renderer/native/ios/utils/HippyRenderUtils.h
renderer/native/ios/utils/HippyRenderUtils.m
tests/ios/HippyRenderUtilsTest.m

fix(ios): resolve floating point size comparison issues

---

renderer/native/android/src/main/java/com/tencent/renderer/node/TextVirtualNode.java

fix(android): add buildTruncateAtEndStaticLayout impl

---

packages/hippy-react/package.json
packages/hippy-react/src/modules/animation.ts

feat(react): add animation stop

---

renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageLoader.java

fix(android): append init props for image load

---

renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java

fix(android): use Spanned to getSpans

---

driver/js/examples/hippy-vue-next-demo/src/main-native.ts
driver/js/packages/hippy-vue-next-style-parser/src/style-match/css-map.ts

fix(vue-next): fix beforeLoadStyle not work

---

framework/examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.m
framework/ios/base/bridge/HippyBridge.mm
renderer/native/ios/renderer/HippyRootView.mm
renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): resolve reload not working

---

driver/js/include/driver/napi/jsc/jsc_ctx.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/utils/NSObject+CtxValue.mm
tests/ios/HippyCtxValueConvertTest.mm

fix(ios): resolve conversion error between NSString and CtxValue

---

driver/js/examples/hippy-react-demo/src/components/Modal/index.jsx
renderer/native/ios/renderer/HippyComponentData.mm
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/view/HippyViewManager.mm

fix(ios): onShow event of modal component not working

---

modules/vfs/android/build.gradle
modules/vfs/android/src/main/java/com/tencent/vfs/VfsManager.java

fix(android): add try catch for vfs processor chain get

---

renderer/native/ios/renderer/component/textinput/HippyBaseTextInput.h
renderer/native/ios/renderer/component/textinput/HippyBaseTextInput.m
renderer/native/ios/renderer/component/textinput/HippyTextField.h
renderer/native/ios/renderer/component/textinput/HippyTextField.m
renderer/native/ios/renderer/component/textinput/HippyTextView.h
renderer/native/ios/renderer/component/textinput/HippyTextView.mm
renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm

fix(ios): keyboard related events not working for TextView

---

renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm

fix(ios): accuracy of ViewPager's onPageScroll and ScrollStateChanged API

---

framework/ios/base/modules/HippyModuleMethod.mm
framework/ios/utils/NSObject+CtxValue.h
framework/ios/utils/NSObject+CtxValue.mm
hippy.podspec
tests/ios/HippyCtxValueConvertTest.mm

sync from main to v3.3.x

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): nullptr exception of engine resources in rare scenarios

---

modules/android/pool/src/main/java/com/openhippy/pool/ImageDataPool.java

fix(android): support set custom image pool size

---

docs/api/hippy-react/components.md
docs/api/hippy-vue/external-components.md
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.m

feat(ios): add showScrollIndicator prop for waterfall component

---

renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm

feat(ios): add HippyFontChangeTriggerNotification for font update 2

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm

refactor(ios): minor update of UIManager and ShadowView

---

ios/sdk/debug/websocket/HippySRWebSocket.h
ios/sdk/debug/websocket/HippySRWebSocket.m
ios/sdk/debug/websocket/HippyWebSocketManager.m

fix(ios): websocket module support extra headers

---

README.md

feat(doc): update README.md

---

driver/js/packages/hippy-react/src/components/list-view.tsx
driver/js/packages/hippy-react/src/components/waterfall-view.tsx

feat(react): remove unregisted event

---

driver/js/packages/hippy-vue-native-components/src/ul-refresh.ts

feat(vue): support ul refresh scroll

---

driver/js/src/modules/contextify_module.cc

fix(core): LoadUntrustedContent crash protect

---

driver/js/src/modules/contextify_module.cc
framework/ios/base/bridge/HippyBridge.mm

sync from main to 3.3.x

---

driver/js/packages/hippy-vue/src/native/index.ts

feat(devtools): fix devtools element not show

---

devtools/devtools-integration/native/src/v8/trace_control.cc

feat(devtools): add v8 js profile

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): delay release engine resource to avoid deadlock

---

renderer/native/ios/renderer/NativeRenderManager.mm

fix(ios): thread race when getting uiManager

---

renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefresh.m
renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefresh.m
renderer/native/ios/renderer/component/refresh/HippyRefresh.h
renderer/native/ios/renderer/component/refresh/HippyRefresh.m
renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm

fix(ios): abnormal onFooterPulling callback (#4106)

---

core/include/core/napi/v8/js_native_turbo_v8.h

fix(core): fix turbo memory leak

---

dom/src/dom/taitank_layout_node.cc

fix(core): check crash on config SetScaleFactor (#3967)

---

dom/src/dom/root_node.cc

fix(devtools): fix DOM tree flickering for animation page

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(devtools): fix network debug information for ios in chrome devtool

---

dom/src/dom/animation/animation_manager.cc

fix(core): fix invalid animation crash

---

dom/src/dom/animation/animation_manager.cc

fix(core): fix invalid animation crash (#4117)

---

renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/text/HippyText.mm
renderer/native/ios/renderer/component/view/HippyShadowView.h
renderer/native/ios/renderer/component/view/HippyShadowView.mm
renderer/native/ios/renderer/component/view/HippyView.m
renderer/native/ios/renderer/component/view/UIView+Hippy.h
renderer/native/ios/renderer/component/view/UIView+Hippy.mm

fix(ios): dynamic changes to zIndex not working

---

framework/examples/ios-demo/HippyDemo/TurboModuleDemo/TurboBaseModule.mm
framework/ios/base/bridge/HippyBridge+BundleLoad.h
framework/ios/base/bridge/HippyBridge+BundleLoad.mm
framework/ios/base/bridge/HippyBridge+ModuleManage.h
framework/ios/base/bridge/HippyBridge+ModuleManage.mm
framework/ios/base/bridge/HippyBridge+PerformanceAPI.h
framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm
framework/ios/base/bridge/HippyBridge+Private.h
framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/executors/HippyJSExecutor.mm
framework/ios/base/modules/HippyEventDispatcher.mm
framework/ios/base/modules/HippyModuleData.mm
framework/ios/module/dev/HippyDevMenu.mm
framework/ios/module/dev/HippyRedBox.mm
framework/ios/module/turbo/HippyOCTurboModule.mm
modules/ios/base/HippyDefines.h
renderer/native/ios/renderer/HippyComponent.h
renderer/native/ios/renderer/HippyRootView.mm
renderer/native/ios/renderer/HippyUIManager.h
renderer/native/ios/renderer/HippyUIManager.mm
tests/ios/HippyBridgeTest.mm
tests/ios/HippyUIManagerTest.mm
tests/ios/HippyUIViewCategoryTest.m

refactor(ios): code clean and structure optimization for HippyBridge

---

driver/js/examples/hippy-react-demo/src/modules/Animation/index.jsx
framework/ios/base/bridge/HippyBridge.mm
hippy.podspec
modules/ios/domutils/HippyDomUtils.h
modules/ios/domutils/HippyDomUtils.mm
modules/ios/footstoneutils/HippyFootstoneUtils.mm
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/utils/HippyConvert+NativeRender.m

cp to V3.3.x

---

docs/development/native-event.md
framework/ios/base/bridge/HippyBridge.h
framework/ios/base/bridge/HippyBridge.mm
framework/ios/base/modules/HippyEventDispatcher.h
framework/ios/base/modules/HippyEventDispatcher.mm
framework/ios/module/eventobserver/HippyEventObserverModule.mm
tests/ios/HippyEventDispatcherTest.m

test(ios): add test for event dispatcher and code clean

---

android/sdk/src/main/jni/src/jni/convert_utils.cc

fix(android): java HippyMap leak oom by jni local ref

---

framework/examples/ios-demo/HippyDemo/TurboModuleDemo/TurboBaseModule.mm
framework/ios/base/modules/HippyModulesSetup.m
framework/ios/module/turbo/HippyOCTurboModule.mm
framework/ios/module/turbo/HippyTurboModule.h

chore(ios): resolve turbo module typo

---

renderer/native/ios/renderer/HippyUIManager.mm

fix(ios): thread race when getting ViewManager classes

---

framework/ios/base/bridge/HippyBridge.h

chore(ios): add import in HippyBridge for compile compatibility

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(jsc): fix jscctx finalize crash

---

framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java

build(android): resolve build error

---

modules/footstone/src/platform/ios/looper_driver.cc

fix(jsc): fix ios c autorelease

---

modules/footstone/src/platform/ios/looper_driver.cc

fix(ios): occasional crash of CFRunloop in looper driver

---

framework/ios/base/executors/HippyJSEnginesMapper.mm

fix(core): fix ios thread joinable terminate crash

---

driver/js/src/napi/jsc/jsc_ctx.cc

fix(core): try fix ios hash throw overflow crash

---

driver/js/packages/hippy-react/src/components/text-input.tsx

feat(react): add text input type

---

driver/js/include/driver/scope.h
driver/js/src/base/js_convert_utils.cc
driver/js/src/modules/performance/performance_module.cc
driver/js/src/modules/performance/performance_navigation_timing_module.cc
driver/js/src/scope.cc
framework/ios/base/executors/HippyJSExecutor.mm
framework/ios/module/turbo/HippyOCTurboModule.mm

fix(core): fix c++ stack overflow

---

modules/footstone/src/platform/ios/looper_driver.cc

fix(ios): occasional crash of CFRunloop in looper driver (#4164)

---

framework/ohos/src/main/ets/hippy_framework/devsupport/DevRemoteServerData.ets

fix(ohos): fix remote server url parse

---

framework/ios/base/bridge/HippyBridge+BundleLoad.mm
framework/ios/base/executors/HippyJSExecutor.mm
framework/ios/utils/NSObject+CtxValue.mm
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/NativeRenderManager.mm
renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/textinput/HippyShadowTextView.mm
renderer/native/ios/renderer/component/view/HippyShadowView.mm

refactor(ios): remove all unnecessary autorelease pool

---

PUBLISH.md

feat(ohos):  hippy ohos publish doc

---

modules/footstone/include/footstone/check.h
modules/footstone/src/deserializer.cc
modules/footstone/src/worker.cc
modules/footstone/src/worker_manager.cc

fix(core): fix cpp analyze results

---

renderer/native/ios/renderer/component/listview/HippyNextBaseListViewManager.m
renderer/native/ios/renderer/component/text/HippyShadowText.mm

fix(ios): layout issue of pure images nested in text scenarios

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/pager_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/components/pager_view.cc

fix(ohos):  fix pager change index bug

---

modules/footstone/src/worker.cc

fix(core): rollback android thread join anr

---

docs/api/hippy-react/components.md
docs/api/hippy-vue/components.md
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/list_node.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_convert_utils.h
framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/list_node.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/list_view.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/waterfall_view.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_convert_utils.cc

feat(ohos):  list scrollToIndex support scrollAlign for vl

---

renderer/native/ios/renderer/component/scrollview/HippyNestedScrollCoordinator.m
renderer/native/ios/renderer/component/scrollview/HippyNestedScrollProtocol.h

fix(ios): optimize smoothness of nested scroll in special scenarios

---

renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm

fix(ios): resolve occasional index OOB when no items in ViewPager

---

docs/development/use-hermes-engine.md

docs(hermes): update hermes usage guide

---

framework/ohos/src/main/ets/hippy_framework/adapter/file/FileRequestAdapter.ets
framework/ohos/src/main/ets/hippy_framework/bridge/bundleloader/HippyRemoteBundleLoader.ets

fix(ohos): HippyRemoteBundleLoader crash protect

---

dom/src/dom/dom_node.cc

fix(core): fix DomNode cb_map erase bug

---

framework/ohos/src/main/ets/renderer_native/serialization/NativeRenderSerializer.ets

fix(ohos): fix NativeRenderSerializer write obj not map

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/scroll_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/components/base_view.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/scroll_view.cc

fix(ohos): fix ScrollView event

---

framework/ohos/src/main/ets/renderer_native/NativeRenderBuilderForCApi.ets

fix(ohos): fix import problem

---

framework/ohos/src/main/ets/hippy_framework/adapter/http/DefaultHttpAdapter.ets
framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets

fix(ohos): fix HippyHttpRequest

---

renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

Fixed a click event experience issue where a slight movement of the finger without leaving the click object will not cause the click to fail, and make sure touch events are sent in pairs

fix(ios): resolve gestures related bugs

---

framework/ios/base/bridge/HippyBridge+VFS.h
framework/ios/base/bridge/HippyBridge+VFS.mm
hippy.podspec
modules/vfs/ios/HippyVFSDefines.h
renderer/native/ios/renderer/component/image/HippyImageViewManager.mm
tests/ios/HippyFileHandlerTest.mm

refactor(ios): add oc wrapper for vfs module

---

framework/examples/ios-demo/HippyDemo/HippyDemoViewController.m
renderer/native/ios/renderer/component/image/HippyImageView.m
renderer/native/ios/renderer/component/view/HippyView.m
renderer/native/ios/renderer/component/view/HippyViewManager.mm

refactor(ios): replace deprecated UIGraphics API with alternative

---

driver/js/include/driver/napi/jsh/jsh_ctx.h
driver/js/src/napi/jsh/jsh_ctx.cc

fix(ohos): fix jsh finalize crash

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

chore(workflows): update issue template assignees

---

docs/development/ohos-integration-guidelines.md

feat(ohos):  doc for integration question

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/api_c/hippy.h

feat(ohos):  add layout engine comment

---

framework/ohos/src/main/cpp/impl/connector/src/js_driver_napi.cc

fix(ohos): fix OnResourceLoadEnd crash

---

renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

where click event may be triggered by mistake when manually swiping related to 23a31556b

fix(ios): resolve touch handler issue

---

framework/ohos/src/main/cpp/impl/renderer/native/src/api_c/hippy.cc

fix(ohos): fix c create root multithread safe

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/view/HippyViewManager.mm

fix(ios): add protection when setting unsupported prop for component

---

renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

fix(ios): resolve touch events not paired issue under special scenarios

---

docs/api/hippy-react/components.md
docs/api/hippy-vue/components.md
driver/js/examples/hippy-react-demo/src/components/ListView/index.jsx
driver/js/examples/hippy-vue-demo/src/components/demos/demo-list.vue
driver/js/examples/hippy-vue-next-demo/src/components/demo/demo-list.vue

docs(js): remove deprecated editable related props in demo

---

driver/js/src/vm/v8/inspector/v8_inspector_client_impl.cc

fix(ohos):  fix v8 debug chrome cmd crash

---

xcodeinitscript.sh

build(ios): build compatibility of devtools module with cmake 4.0

---

dom/include/dom/dom_argument.h
dom/src/dom/dom_argument.cc
modules/footstone/include/footstone/deserializer.h
modules/footstone/include/footstone/string_view.h
modules/footstone/src/deserializer.cc

fix(ios): char_traits compile error for xcode 16.3

---

driver/js/examples/hippy-react-demo/src/components/Focusable/index.jsx
driver/js/examples/hippy-react-demo/src/routes.js
driver/js/packages/hippy-react/src/components/focusable.tsx

fix(react): fix focusable view container error

---

driver/js/src/js_driver_utils.cc
framework/voltron/core/src/bridge/bridge_ffi_impl.cc

fix(android):  fix github jobs error

---

framework/ios/base/executors/HippyJSExecutor.mm
framework/voltron/core/src/bridge/bridge_ffi_impl.cc
framework/voltron/core/src/bridge/ios/VoltronJSCExecutor.mm

build(voltron): resolve voltron build failures

---

renderer/native/ios/renderer/component/view/HippyView.m

fix(ios): 1px gap in gradient background under special circumstances

---

renderer/native/ios/renderer/component/scrollview/HippyNestedScrollCoordinator.m
renderer/native/ios/renderer/component/scrollview/HippyNestedScrollProtocol.h

fix(ios): optimization of nested scroll in multi-layer nested scenarios

---

dom/include/dom/dom_argument.h
dom/src/dom/dom_argument.cc
dom/src/dom/dom_node.cc
framework/examples/ios-demo/HippyDemo/HippyDemoViewController.m
framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm
framework/ios/base/bridge/HippyBridge+VFS.h
framework/ios/base/bridge/HippyBridge+VFS.mm
hippy.podspec
modules/footstone/include/footstone/deserializer.h
modules/footstone/include/footstone/string_view.h
modules/footstone/src/deserializer.cc
modules/vfs/ios/HippyVFSDefines.h
renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/image/HippyImageView.m
renderer/native/ios/renderer/component/image/HippyImageViewManager.mm
renderer/native/ios/renderer/component/listview/HippyNextBaseListViewManager.m
renderer/native/ios/renderer/component/scrollview/HippyNestedScrollCoordinator.m
renderer/native/ios/renderer/component/scrollview/HippyNestedScrollProtocol.h
renderer/native/ios/renderer/component/view/HippyView.m
renderer/native/ios/renderer/component/view/HippyViewManager.mm
renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm
renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm
tests/ios/HippyFileHandlerTest.mm
xcodeinitscript.sh

cp from main to v3.3.x

---

renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

chore(ios): remove debug assert in touch handler to avoid interference

---

framework/examples/ohos-c-demo/src/main/ets/pages/Index.ets
framework/examples/ohos-demo/src/main/ets/pages/PageConfiguration.ets
framework/examples/ohos-har-demo/src/main/ets/pages/Index.ets
framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets
framework/ohos/src/main/ets/hippy_framework/HippyEngineContextImpl.ets
framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets
framework/ohos/src/main/ets/hippy_framework/adapter/monitor/DefaultEngineMonitorAdapter.ets
framework/ohos/src/main/ets/hippy_framework/adapter/monitor/HippyEngineMonitorAdapter.ets
framework/ohos/src/main/ets/hippy_framework/index.ets

feat(ohos):  add ModuleListener

---

framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_provider.cc

fix(ohos):  fix UpdateTextMeasurer crash

---

renderer/native/ios/renderer/component/view/HippyShadowView+Internal.h
renderer/native/ios/renderer/component/view/HippyShadowView.mm

fix(ios): memory optimization & fix potential thread race in shadowView

---

framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm

fix(ios): resolve potential thread race in performance api

---

modules/ios/base/HippyConvert.m
renderer/native/ios/renderer/component/view/HippyBorderDrawing.h
renderer/native/ios/renderer/component/view/HippyBorderDrawing.m
renderer/native/ios/renderer/component/view/HippyView.h
renderer/native/ios/renderer/component/view/HippyView.m
renderer/native/ios/renderer/component/view/HippyViewManager.mm

It is currently known to occur only on certain devices running iOS18 also replace some deprecated apis

fix(ios): abnormal background color drawing with corner radius

---

framework/ohos/src/main/cpp/impl/renderer/native/CMakeLists.txt
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/custom_node.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/rich_text_view.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/text_measure/text_measurer.h
framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/arkui_node_registry.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/custom_node.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/rich_text_view.cc

feat(ohos): text draw to custom node

---

framework/ohos/src/main/cpp/impl/renderer/native/src/text_measure/text_measurer.cc

fix(ohos):  fix font api14 macro

---

framework/ohos/src/main/ets/hippy_framework/adapter/http/HippyHttpRequest.ets

fix(ohos):  fix http user agent

---

framework/ohos/src/main/cpp/impl/connector/src/native_renderer_napi.cc
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/native_render_manager.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/text_measure/text_measurer.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_pixel_utils.h
framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/text_measure/text_measurer.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_pixel_utils.cc
framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets
framework/ohos/src/main/ets/hippy_framework/connector/NativeRenderer.ets
framework/ohos/src/main/ets/hippy_library/HippyLibrary.ets
framework/ohos/src/main/ets/support/utils/PixelUtil.ets

feat(ohos): font weight scale follow system setting

---

framework/ios/base/bridge/HippyBridgeDelegate.h
modules/ios/base/HippyLog.h
renderer/native/ios/renderer/HippyComponentData.h
renderer/native/ios/renderer/HippyComponentData.mm
renderer/native/ios/renderer/HippyFont.h
renderer/native/ios/renderer/HippyFont.mm
renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/text/HippyTextManager.mm
renderer/native/ios/renderer/component/view/HippyViewManager.h
renderer/native/ios/renderer/component/view/HippyViewManager.mm

refactor(ios): refactor and obsolete code removal

---

framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
framework/android/src/main/java/com/tencent/mtt/hippy/adapter/monitor/DefaultEngineMonitorAdapter.java
framework/android/src/main/java/com/tencent/mtt/hippy/adapter/monitor/HippyEngineMonitorAdapter.java
framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/TimeMonitor.java

fix(android): add MonitorGroup for HippyEngineMonitorAdapter

---

framework/ohos/src/main/ets/hippy_framework/bridge/HippyBridgeManagerImpl.ets

fix(ohos): fix preload return code

---

framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets
framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets

fix(ohos): fix preload no uicontext

---

framework/ohos/src/main/ets/hippy_framework/HippyEngine.ets

fix(ohos): engine init param check log

---

driver/js/include/driver/napi/js_ctx.h
driver/js/include/driver/napi/jsc/jsc_ctx.h
driver/js/src/napi/jsc/jsc_ctx.cc
driver/js/src/scope.cc

fix(ios): fix jsc ctx finalize crash

---

framework/ohos/src/main/cpp/impl/connector/src/js_driver_napi.cc

fix(ohos): no scope crash protect

---

renderer/native/ios/renderer/HippyUIManager.mm
renderer/native/ios/renderer/component/modal/HippyModalHostView.m
renderer/native/ios/renderer/component/modal/HippyModalHostViewController.m
renderer/native/ios/renderer/component/modal/HippyModalHostViewManager.mm

fix(ios): dynamic size adaptation support of modal component

---

framework/ohos/src/main/ets/hippy_framework/index.ets

fix(ohos): fix useNormalizedOHMUrl and dynamic import

---

renderer/native/ios/renderer/touch_handler/HippyTouchHandler.mm

fix(ios): nested sub text not responds to click event in touch handler

---

framework/examples/ohos-c-demo/src/main/ets/hippy_extend/ExampleAPIProvider.ets
framework/examples/ohos-c-demo/src/main/ets/hippy_extend/ExampleViewA.ets
framework/examples/ohos-c-demo/src/main/ets/pages/Index.ets

feat(ohos): add custom view for c demo

---

driver/js/src/napi/hermes/hermes_ctx.cc

refactor(ios): hermes ctx code update

---

framework/ios/base/executors/HippyJSExecutor.mm

refactor(ios): remove redundant lock in js engine

---

renderer/native/ios/renderer/component/text/HippyShadowText.mm
renderer/native/ios/renderer/component/textinput/HippyTextField.m
renderer/native/ios/renderer/component/textinput/HippyTextView.mm

also remove some obsolete code

fix(ios): onChange not fired under password mode of input component

---

framework/ohos/src/main/cpp/impl/connector/src/native_renderer_napi.cc
framework/ohos/src/main/cpp/impl/renderer/native/CMakeLists.txt
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/text_input_view.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/uimanager/hr_keyboard_manager.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/utils/hr_event_utils.h
framework/ohos/src/main/cpp/impl/renderer/native/src/components/text_input_view.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/uimanager/hr_keyboard_manager.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/utils/hr_event_utils.cc
framework/ohos/src/main/ets/hippy_framework/HippyEngineManagerImpl.ets
framework/ohos/src/main/ets/hippy_framework/HippyWindowInfo.ets
framework/ohos/src/main/ets/hippy_library/HippyLibrary.ets

feat(ohos): add keyboard height listener

---

docs/development/native-integration.md
docs/development/ohos-integration-guidelines.md
framework/ohos/README.md

feat(ohos): add hippy engine release doc

---

devtools/devtools-integration/native/src/adapter/impl/hippy_dom_tree_adapter.cc

chore(devtools): remove debug assert when inspect non-exist node

---

driver/js/src/scope.cc
framework/ios/base/executors/HippyJSExecutor.mm

refactor(ios): exception optimization and remove redundant autorelease

---

driver/js/src/napi/hermes/hermes_ctx.cc

refactor(ios): open class feature switch for hermes

---

ios/sdk/component/view/HippyViewManager.mm
ios/sdk/utils/HippyGradientObject.m

fix(ios): exception may occur while setting linearGradient prop

---

docs/README.md

docs(home): update hippy document link

---

framework/ohos/src/main/ets/hippy_framework/adapter/http/HttpTaskCallbackImpl.ets

fix(ohos): Non-200 status code structure return

---

framework/ios/base/executors/HippyJSExecutor.mm

fix(ios): very occasional exception while setting context name of JSC

---

framework/ohos/src/main/cpp/impl/renderer/native/src/components/rich_text_view.cc

fix(ohos): fix image span for list item recycle

---

renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm

Note that this is not a complete modification to support rtl,
Modifications to the layout process are still needed to fully support it

fix(ios): rtl layout issue for scroll component

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/arkui_node.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/rich_text_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/arkui_node.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/rich_text_view.cc

fix(ohos): fix draw text to custom node dirty flag

---

framework/ohos/src/main/ets/hippy_library/HippyLibrary.ets

feat(ohos): add worker module for perf

---

framework/examples/ohos-har-demo/oh-package.json5
framework/examples/ohos-har-demo/src/main/ets/pages/Index.ets
framework/examples/ohos-har-demo/src/main/ets/pages/Index2.ets
framework/ohos/CHANGELOG.md
framework/ohos/oh-package.json5

Feature/ohos update3.3.1

---

framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/scroll_node.cc

fix(ohos): fix scroll event notify frequency

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/base_view.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/scroll_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/components/base_view.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/scroll_view.cc

fix(ohos): fix scroll event notify frequency boundary case

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/pager_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/components/pager_view.cc

fix(ohos): fix pager scroll event perf

---

framework/examples/ios-demo/HippyDemo/HippyDemoViewController.m
framework/ios/base/HippyDeviceBaseInfo.mm
framework/ios/base/bridge/HippyBridgeDelegate.h

feat(ios): add a setter api for default window size in Dimensions

---

framework/ios/base/HippyDeviceBaseInfo.mm
framework/ios/base/bridge/HippyBridge+Private.h
framework/ios/base/bridge/HippyBridge.mm

chore(ios): bind dimensions cache data to bridge instance

---

driver/js/src/vm/jsc/jsc_vm.cc
framework/ios/utils/NSObject+CtxValue.mm
tests/ios/HippyCtxValueConvertTest.mm

fix(ios): string with null character support in bridge

---

framework/ios/debug/websocket/HippySRWebSocket.m

chore(ios): Xcode 26 compatibility

---

framework/ohos/src/main/cpp/impl/renderer/native/src/components/image_view.cc

fix(ohos): fix ImageView capInsets px

---

framework/ohos/src/main/cpp/impl/renderer/native/src/text_measure/text_measurer.cc

fix(ohos): crash protect for std stod exception

---

framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/arkui/arkui_node.h
framework/ohos/src/main/cpp/impl/renderer/native/include/renderer/components/base_view.h
framework/ohos/src/main/cpp/impl/renderer/native/src/arkui/arkui_node.cc
framework/ohos/src/main/cpp/impl/renderer/native/src/components/base_view.cc

fix(ohos): fix attach detach window event

---

framework/ohos/src/main/cpp/impl/renderer/native/src/text_measure/text_measurer.cc

fix(ohos): fix default system font when not found custom font

---

framework/ohos/src/main/cpp/impl/renderer/native/src/native_render_manager.cc

fix(ohos): fix image span pos when image span is trimed

---

framework/android/connector/driver/js/gradle.properties

feat(android): v8 10.6.194.26 version support 16k pages patch

---

driver/js/examples/hippy-vue-demo/src/components/demos/demo-textarea.vue
renderer/native/ios/renderer/component/textinput/HippyTextView.h
renderer/native/ios/renderer/component/textinput/HippyTextView.mm
renderer/native/ios/renderer/component/textinput/HippyTextViewManager.mm

* fix(ios): textColor not work for MultiLine textinput
* fix(ios): enhance text input handling

fix(ios): textColor not work for multiline textinput (#4396)

---

renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java

fix(android): fix height param size of onContentChange event
