- README.md
- README.zh_CN.md
1. fix typo in readme.
2. add link to each other in English README and simplified Chinese README.
> fix: typo in readme

- README.md
The Chinese README states "每日触达数亿用户", which in English translates to "reaches hundreds of millions of users daily", but the English README states it reaches "tens of billions" of users (there are only 7 billion people on the planet). This should read "hundreds of millions".
I also changed "concerning" to "reaching" as it's a more natural word for this context.
> fix: correct minor typos in English README

- packages/hippy-debug-server/index.js
It can't parse arguments before this repair, only default option works.
SEE: https://github.com/yargs/yargs/blob/master/docs/api.md#choiceskey-choices
> fix(debug-server): fix yargs usage error

- examples/hippy-react-demo/src/components/WebView/index.jsx
CRLF in header will make the android webview crash.
SEE:
https://github.com/chromium/chromium/blob/master/net/http/http_request_headers.cc#L152
https://github.com/chromium/chromium/blob/master/net/http/http_util.h#L106
Fix the following error
```
[ERROR:http_request_headers.cc(152)] "User-Agent: Mozilla/5.0 (Linux; U; Android 5.1.1;
zh-cn; vivo X7 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/37.0.0.0 MQQBrowser/8.2
Mobile Safari/537.36" has invalid header value.
```
> fix(react-demo):  android  invalid header error

- packages/hippy-vue/src/renderer/element-node.js
- packages/hippy-vue/src/util/__tests__/index.test.js
- packages/hippy-vue/src/util/index.js
The old implementation of setStyle('flex', 1), will enter into parseFloat logic and returns NaN.
> fix(vue): setStyle px unit determine.

- packages/hippy-react/src/components/text.tsx
```
<Text>{"A"}B</Text>
```
rendered as `AB AB`,expected is `AB`.
```
<Text>{"A"} </Text>
```
rendered as `A A `,expected is `A `
> fix(hippy-react): Text component text repeated rendering

- android/sdk/src/main/java/com/tencent/mtt/hippy/utils/ArgumentUtils.java
`Bundle[]` will be recognized as `Parcelable[]` after a Bundle is unmarshalled. 
- A `Bundle[]` instance can only be passed into another Bundle by `putParcelableArray()`
- When starting an activity with `Intent.putExtras()`, the `Bundle[]` instance will be converted into a `Parcelable[]` instance
- When converting a bundle with `Parcelable[]` instances (actually `Bundle[]` instances), the unrecognized type will cause a exception. 
- treat any `Parcelable[]` instance as `Bundle[]` instance when converting arrays
- only `Bundle` subelements will be converted into `HippyMap`
> fix(android): treat Parcelable[] as Bundle[]

- ios/sdk/component/textinput/HippyShadowTextView.mm
fix crash caused by incorrect creation of UIFont
> fix(ios): fix crash caused by incorrect creation of UIFont

- packages/hippy-react/src/renderer/render.ts
> feat(hippy-react): merge createNode operation

- ios/sdk/component/image/HippyImageView.m
设置defaultImage的时候，如果当前hippyImageView已经展示图片而不是占位图，不应该更新图片。
触发场景：正常列表已经加载成功，这个时候切换日夜间模式，前端需要替换对应的占位图样式，此时已经加载好的图片被更新成了占位图。
> fix(ios): set default image need not update imageview

- docs/hippy-vue/components.md
- packages/hippy-vue/src/elements/built-in.js
> fix(hippy-vue): fixed focus event support for div

- packages/hippy-react-web/src/adapters/apply-layout.ts
- packages/hippy-react-web/src/index.ts
- packages/hippy-react-web/src/native.ts
@hippy/react-web 支持服务端渲染，主要变动内容：
- 判断 `window` 和 `localStorage` 变量是否非空
- 在服务端环境下，支持设置 Dimensions 数值，这里参考 https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Dimensions/index.js#L51-L60
> feat(hippy-react-web): support isomorphic rendering

- packages/hippy-react-web/src/components/image.tsx
> fix(hippy-react-web): fixed image newProps src unRendered problem

- ios/sdk/component/footerrefresh/HippyFooterRefreshManager.m
- ios/sdk/component/headerrefresh/HippyHeaderRefresh.m
- ios/sdk/component/headerrefresh/HippyHeaderRefreshManager.m
- ios/sdk/component/refresh/HippyRefresh.h
- ios/sdk/component/refresh/HippyRefresh.m
> feat(ios): pull header feature to set refresh time

- packages/hippy-vue/src/elements/__tests__/index.test.js
- packages/hippy-vue/src/elements/index.js
Cannot registerElement with kebab-case name  which converted to camelCase is the same with component.name
> fix(hippy-vue): fix registerElement elem name and comp name problem

- android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/BinaryWriter.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/SafeDirectWriter.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/nio/writer/SafeHeapWriter.java
> fix(android): avoid `Serializer` exceptions when long value

- packages/hippy-react-web/src/adapters/transfer.ts
修复web端显示文字组件lineHeight异常
1. 文字组件lineHeight需传入带px单位的字符串
2. toPx函数不会直接去修改其传入参数，仅会返回修改后的值，这里需要手动修改webStyle.lineHeight
> fix(hippy-react-web): correct lineHeight style values

- android/sdk/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java
> fix(android): getRenderNodeHeight headerEventHelper null crash

- ios/sdk/component/text/HippyShadowText.h
- ios/sdk/component/text/HippyShadowText.mm
we needs consider baseline offfset for nested view
> fix(ios): fix nested text layout error

- dom/include/dom/layer_optimized_render_manager.h
- dom/src/dom/layer_optimized_render_manager.cc
change the type of kJustLayoutProps from std::unordered_set to
std::array to avoid potential memory leak.
> fix(dom): rename RenderManagerProxy to LayerOptimizedRenderManager

- .github/workflows/update_v8.yml
> chore(android): use NDK clang++ instead of `llvm-build` shipped by V8

- android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/HippyImageSpan.java
问题说明：
原有的HippyImageSpan，在设置行间距后，图文的对齐方式会被破坏。动画演示可以参考https://mk.woa.com/note/2339#:~:text=%E6%96%87%E6%9C%AC%E7%9A%84%E9%AB%98%E5%BA%A6%E3%80%82-,%E5%9B%BE%E6%96%87%E6%B7%B7%E6%8E%92%E7%9A%84%E5%AF%B9%E9%BD%90%E9%97%AE%E9%A2%98,-%E6%8E%8C%E6%8F%A1%E4%BA%86%E4%BB%A5%E4%B8%8A
解决方案：
引入了手Q在用的RIJEnhancedImageSpan。原有的gif相关绘制，保持原有逻辑
> fix(android): fix HippyImageSpan align problems

- examples/hippy-vue-demo/src/components/demos/demo-remote-bundle.vue
- examples/hippy-vue-demo/src/components/demos/index.js
- examples/ios-demo/HippyDemo.xcodeproj/project.pbxproj
- examples/ios-demo/HippyDemo/TestModule.m
- examples/ios-demo/HippyDemo/ViewController.m
- ios/sdk/base/HippyBatchedBridge.mm
- ios/sdk/base/HippyBridge.h
- ios/sdk/base/HippyBridge.mm
- ios/sdk/base/HippyBundleURLProvider.h
- ios/sdk/base/HippyBundleURLProvider.m
- ios/sdk/base/HippyInvalidating.h
- ios/sdk/base/HippyRootView.mm
- ios/sdk/debug/devtools/HippyDevInfo.h
- ios/sdk/debug/devtools/HippyDevInfo.m
- ios/sdk/debug/devtools/HippyDevManager.h
- ios/sdk/debug/devtools/HippyDevManager.m
- ios/sdk/debug/devtools/HippyDevWebSocketClient.h
- ios/sdk/debug/devtools/HippyDevWebSocketClient.m
> feat(ios): websocket url add hash and close with code and reason

- ios/sdk/base/HippyBatchedBridge.mm
- ios/sdk/base/HippyBundleURLProvider.h
- ios/sdk/base/HippyBundleURLProvider.m
- ios/sdk/debug/devtools/HippyDevInfo.h
- ios/sdk/debug/devtools/HippyDevInfo.m
- ios/sdk/debug/devtools/HippyDevWebSocketClient.m
- ios/sdk/debug/devtools/inspector/model/HippyCSSPropsDefine.m
> feat(ios): parse websocket url from bundle url

- ios/sdk/component/image/HippyAnimatedImageView.m
UIImageView does not response displayer in ios13
> fix(ios): fix image display crash

- ios/sdk/component/image/HippyAnimatedImageView.m
Fix https://github.com/Tencent/Hippy/issues/1688
in iOS 10~13, UIImageView does not implements this delegate method. See:
Only iOS 14+ implements this method:
> fix(ios) animatedImageView call displayLayer crash bug

- docker/android-release/Dockerfile
> chore(docker): replacing `centos` with `debian` as base image

- .github/workflows/android_build_tests.yml
> fix(ci): fix android build tests workflow throw `gradle not found` error

- .github/workflows/gh_pr_labeler.yml
add accessible permission to avoid
`Resource not accessible by integration` error
> fix(workflows): add accessible permission to avoid error

- android/sdk/src/main/java/com/tencent/mtt/hippy/serialization/PrimitiveValueSerializer.java
switch one byte string encoding
from ascii to latin1
during the serialization
> feat(android): change one byte string encoding

- buildconfig/cmake/compiler_toolchain.cmake
Before LLVM 14 [1],
Outline atomics will crash on Samsung Exynos 9810 CPU [2]
with big cores are ARMv8.2 and LITTLE are ARMv8.0.
Since LSE is for ARMv8.1 and later, so it should be disabled.
[1] https://reviews.llvm.org/rGcce4a7258b81159e57a411896011ee2742f17def
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=1272795
> fix(cmake): disable outline atomics on android

- ios/sdk/component/refresh/HippyRefresh.m
need to reset timer when new timer invoked
> fix(ios): fix refresh component delay reset bug

- ios/sdk/component/textinput/HippyTextField.m
> fix(ios): fix undo crash for uitextfiled component

- ios/sdk/base/executors/HippyJSCExecutor.mm
we use std::lock to keep js runner from being destroyed when Engine is in use
> fix(ios): try to avoid destroying variables in use

- ios/sdk/component/textinput/HippyTextField.m
> fix(ios): hippy-vue textInput isFocused not working

- ios/sdk/module/uimanager/HippyUIManager.mm
[NSObject conformsToProtocol:] ses a global mutex_t runtimeLock to lock, which may case lag in main thread
> perf(ios): use respondsToSelector instead of conformsToProtocol

- .github/workflows/3rd_prebuilt_v8.yml
- .github/workflows/docker_build_image.yml
- .github/workflows/gh_issue_crash_report.yml
- .github/workflows/gh_pr_checks_approval.yml
- .github/workflows/hip_archive_artifact.yml
- .github/workflows/security_codeql_analyses.yml
replaced obsolete workflow output command `set-output` with `GITHUB_OUTPUT` environment file.
> ci(workflows): replaced obsolete workflow command

- .github/CODEOWNERS
> ci(codeowner): change codeowner classificatioin

- core/third_party/base/src/platform/ios/logging.cc
- examples/hippy-react-demo/src/app.jsx
- examples/ios-demo/HippyDemo/ViewController.m
- ios/sdk/utils/HippyLog.mm
> fix(ios): fix ConsoleModule.log not working

- android/sdk/src/main/jni/include/loader/adr_loader.h
- android/sdk/src/main/jni/src/loader/adr_loader.cc
> feat(core): dynamic loading support custom protocols

- ios/sdk/component/scrollview/HippyScrollView.h
- ios/sdk/component/scrollview/HippyScrollView.m
> feat(ios): add method to create custom scrollview

- android/sdk/src/main/java/com/tencent/mtt/hippy/dom/node/TextNode.java
- docs/en-us/style/appearance.md
- docs/style/appearance.md
> fix(android): text with negative letterSpacing wraps at wrong position

- .github/workflows/gh_pr_auto_updater.yml
> feat(workflows): add pull requests auto updater

- android/sdk/src/main/jni/CMakeLists.txt
- buildconfig/cmake/compiler_toolchain.cmake
enable Safe ICF to optimize binary size,  reduced ~36k size
```
selected section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
removing identical section core/libcore.a(scope.cc.o):(.text)
selected section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
removing identical section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
removing identical section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
selected section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
removing identical section CMakeFiles/hippy.dir/src/bridge/entry.cc.o:(.text)
removing identical section CMakeFiles/hippy.dir/src/jni/jni_env.cc.o:(.text)
removing identical section CMakeFiles/hippy.dir/src/performance/memory.cc.o:(.text)
removing identical section …
```
> feat(android): enable Safe ICF to optimize binary size

- framework/ios/base/bridge/HippyBridge.mm
The caller may attempt to look up a module immediately after creating the HippyBridge, therefore the initialization of all modules cannot be placed in a sub-thread
> fix(ios): move module init from asynchronization to synchronization

- android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/inspector/Inspector.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManager.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/modules/HippyModuleManagerImpl.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerRegistry.java
- ios/sdk/debug/devtools/HippyDevManager.m
- ios/sdk/module/dev/HippyDevMenu.mm
> feat(devtools): add rendererType and componentCount report

- renderer/native/android/src/main/cpp/include/renderer/native_render_jni.h
- renderer/native/android/src/main/cpp/include/renderer/native_render_manager.h
- renderer/native/android/src/main/cpp/src/renderer/native_render_jni.cc
- renderer/native/android/src/main/cpp/src/renderer/native_render_manager.cc
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerManager.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
> feat(android): add filter for css style to native renderer

- core/third_party/base/include/base/unicode_string_view.h
- core/third_party/base/src/base/unicode_string_view.cc
> fix(core): fix std hash for xcode15

- ios/sdk/base/executors/HippyJSCExecutor.mm
- ios/sdk/module/animation2/HippyNextAnimationModule.m
> fix(ios): fix context leak when using shared engine

- packages/global.d.ts
- packages/hippy-react-web/src/components/list-view.tsx
- packages/hippy-react-web/src/components/modal.tsx
- packages/hippy-react-web/src/modules/stylesheet.ts
- packages/hippy-react/src/components/modal.tsx
- packages/hippy-react/src/components/text-input.tsx
- packages/hippy-react/src/components/text.tsx
- packages/hippy-react/src/components/view.tsx
- packages/hippy-react/src/modules/animation-set.ts
- packages/hippy-react/src/modules/animation.ts
- packages/hippy-react/src/types/global.d.ts
- packages/hippy-react/src/types/index.ts
> feat(hippy-react): modal visible default true and optional props

- driver/js/include/driver/scope.h
- driver/js/src/napi/jsc/jsc_ctx.cc
> fix(jsc): fix gc finalize bug and performance

- driver/js/src/vm/v8/v8_vm.cc
- framework/android/build.gradle
- framework/android/gradle.properties
> feat(js): open js profiler

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
> fix(android): reduce duplicate textchange event

- ios/sdk/component/textinput/HippyTextField.m
> fix(ios): onChange event not triggered when typing Chinese Pinyin

- driver/js/packages/hippy-vue/src/renderer/native/style/css-selectors.js
> feat(vue): revert css match

- android/sdk/src/main/jni/src/bridge/entry.cc
- core/include/core/base/file.h
- core/src/base/file.cc
> fix(v8): v8 code cache file broken protect

- dom/include/dom/taitank_layout_node.h
- dom/src/dom/taitank_layout_node.cc
> fix(dom): fix thread conflict on measure function

- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
- renderer/native/android/src/main/java/com/tencent/renderer/utils/ChoreographerUtils.java
> fix(android): revert sInForeground impl

- framework/android/src/main/java/com/tencent/mtt/hippy/adapter/font/DefaultFontScaleAdapter.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/FontAdapter.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/TypeFaceUtil.java
> feat(android): support get custom type face

- driver/js/include/driver/js_driver_utils.h
- driver/js/src/js_driver_utils.cc
- framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
> fix(driver): fix multi thead conflict when destroy engine

- dom/src/dom/root_node.cc
- driver/js/src/modules/scene_builder_module.cc
- driver/js/src/napi/jsc/jsc_ctx.cc
- modules/footstone/include/footstone/logging.h
- modules/footstone/src/platform/ios/logging.cc
- modules/ios/base/HPLog.h
- renderer/native/ios/renderer/NativeRenderImpl.mm
- renderer/native/ios/renderer/NativeRenderManager.mm
> feat(perf): add logs to pinpoint performance issues

- renderer/native/android/src/main/cpp/src/renderer/native_render_jni.cc
> fix(dom): fix docallback multi thread conflict

- dom/include/dom/diff_utils.h
- dom/include/dom/dom_node.h
- dom/src/dom/diff_utils.cc
- dom/src/dom/dom_manager.cc
- dom/src/dom/dom_manager_unittests.cc
- dom/src/dom/dom_node.cc
- dom/src/dom/root_node.cc
- driver/js/packages/hippy-vue/src/renderer/element-node.js
- driver/js/packages/hippy-vue/src/renderer/native/index.js
- driver/js/src/modules/scene_builder_module.cc
> feat(vue): add style diff perf

- framework/ios/base/bridge/HippyBridge.mm
- modules/footstone/include/footstone/logging.h
> fix(perf): enable perflog output in debug mode only

- dom/src/dom/dom_node.cc
- dom/src/dom/root_node.cc
> fix(dom): fix skip style diff update style map null

- framework/ios/base/bridge/HippyBridge.mm
- hippy.podspec
- modules/ios/base/HippyDefines.h
- modules/ios/base/HippyUtils.h
- modules/ios/base/HippyUtils.m
> chore(ios): make sdk version using macro defines

- framework/examples/ios-demo/podfile
- renderer/native/ios/renderer/component/listview/NativeRenderBaseListViewDataSource.mm
- renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfall.h
- renderer/native/ios/renderer/component/waterfalllist/NativeRenderObjectWaterfall.mm
- renderer/native/ios/renderer/component/waterfalllist/NativeRenderWaterfallView.mm
> fix(ios): listview performance optimization and bug fix

- renderer/native/ios/renderer/HippyRootView.mm
- renderer/native/ios/renderer/component/view/UIView+Hippy.mm
> fix(ios): fix an endless loop when updating rootView's frame

- driver/js/src/modules/animation_module.cc
> fix(core): fix GetInternalField animation 0x241d000023a1 crash

- docs/en-us/hippy-vue/vue3.md
- docs/hippy-vue/vue3.md
> docs(vue-next): add register custom-component doc & use case

- docs/api/hippy-react/modules.md
- docs/api/hippy-vue/vue-native.md
> chore(doc): update `asyncStorage` doc

- android/sdk/src/main/java/com/tencent/mtt/hippy/views/waterfalllist/HippyWaterfallView.java
- android/sdk/src/main/java/com/tencent/mtt/hippy/views/waterfalllist/WaterfallEndChecker.java
> fix(android): waterfall preloadItemNumber not working

- .github/CODEOWNERS
- framework/voltron/CHANGELOG.md
- framework/voltron/core/src/bridge/android/bridge_impl.cc
- framework/voltron/example/android/build.gradle
- framework/voltron/example/android/gradle/wrapper/gradle-wrapper.properties
- framework/voltron/example/lib/main.dart
- framework/voltron/lib/voltron/loader.dart
- framework/voltron/pubspec.yaml
- modules/vfs/voltron/CHANGELOG.md
- modules/vfs/voltron/pubspec.yaml
- modules/voltron/ffi/CHANGELOG.md
- modules/voltron/ffi/lib/ffi_manager.dart
- modules/voltron/ffi/pubspec.yaml
- renderer/voltron/CHANGELOG.md
- renderer/voltron/pubspec.yaml
> voltron support dynamic library load

- framework/examples/ios-demo/HippyDemo/HomePage/HomePageViewController.mm
- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/bridge/HippyBridge.mm
- modules/ios/base/HippyUtils.h
> fix(ios): change sdkVersion variable name , keep compatible with hippy2

- .github/CODEOWNERS
- framework/examples/voltron-demo/IOSProj/IOSProj.xcodeproj/project.pbxproj
- framework/examples/voltron-demo/android-proj/app/src/main/java/com/example/android_proj/MainActivity.java
- framework/examples/voltron-demo/flutter_module/lib/base_voltron_page.dart
- framework/examples/voltron-demo/flutter_module/pubspec.yaml
- framework/examples/voltron-demo/flutter_proj/lib/base_voltron_page.dart
- framework/examples/voltron-demo/flutter_proj/pubspec.yaml
- framework/voltron/CHANGELOG.md
- framework/voltron/example/ios/Podfile.lock
- framework/voltron/example/lib/base_voltron_page.dart
- framework/voltron/lib/engine/engine_define.dart
- framework/voltron/lib/engine/js_engine_context.dart
- framework/voltron/lib/engine/js_init_params.dart
- framework/voltron/lib/engine/voltron_js_engine.dart
- framework/voltron/lib/voltron/loader.dart
- framework/voltron/pubspec.yaml
- renderer/voltron/CHANGELOG.md
- renderer/voltron/lib/bridge/render_bridge.dart
- renderer/voltron/lib/controller/controller.dart
- renderer/voltron/lib/render/manager.dart
- renderer/voltron/lib/util/dimension_util.dart
- renderer/voltron/lib/util/screen_util.dart
- renderer/voltron/pubspec.yaml
> feat(voltron): add voltron_screen_info to make flutter_module faster

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerViewController.java
> fix(android): fix `bounce` can't cancel the system effect

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/Component.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/drawable/TextDrawable.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextComponentController.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/RenderNode.java
> feat(android): support fakeBold for text node

- modules/ios/base/HippyLog.h
> refactor(ios): Generating logs by default, regardless of Debug or not

- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageComponent.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextImageSpan.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/ImageVirtualNode.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/TextVirtualNode.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/VirtualNode.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/VirtualNodeManager.java
> feat(android): Image load events

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
> feat(android): make `TextInput` default color same as iOS

- docs/api/style/transform.md
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/MatrixUtil.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/TransformUtil.java
> fix(android): fix transform order and convert perspective same as iOS

- renderer/native/ios/renderer/component/view/UIView+Hippy.mm
> fix(ios): prevent crashes due to nan values when doing hippySetFrame

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
> feat(android): onKeyboardWillShow only triggers on focused component

- framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.mm
- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/executors/HippyJSExecutor.mm
- framework/ios/debug/devtools/HippyDevInfo.m
- renderer/native/ios/renderer/HippyRootView.mm
> fix(ios): fixed an issue where some part of devtools were not available

- driver/js/packages/hippy-vue-next/src/runtime/element/hippy-element.ts
> fix(vue3): delete source prop for img

- driver/js/packages/hippy-vue-next/src/modules/style.ts
> fix(vue3): skip patch style for same props

- core/third_party/base/include/base/logging.h
- core/third_party/base/src/platform/ios/logging.cc
> build(ios): fix no std:function build error on Xcode15.3

- framework/ios/base/executors/HippyJSExecutor.mm
> fix(ios): fix memory issue when calling JSTurboObjectWithName

- docs/api/hippy-vue/vue3.md
- driver/js/examples/hippy-vue-next-demo/scripts/hippy-webpack.android.js
- driver/js/examples/hippy-vue-next-demo/scripts/hippy-webpack.ios.js
- driver/js/examples/hippy-vue-next-demo/scripts/hippy-webpack.web-renderer.js
> fix(vue-next): fix js release bundle size too big issue

- renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageDataHolder.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/image/ImageLoader.java
> fix(android): remove ImageDataHolder recycle

- modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/ArgumentUtils.java
> fix(android): compatible HashMap and ArrayList for ArgumentUtils

- renderer/native/ios/renderer/HippyUIManager.mm
Some businesses depend on the invocation order of the insertHippySubview method,
so we use std::map instead to ensure that the view created first calls that method first
> fix(ios): ensure insertHippySubview is called sequentially

- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/base/modules/HippyModulesSetup.h
- framework/ios/base/modules/HippyModulesSetup.m
- renderer/native/ios/renderer/HippyUIManager.h
- renderer/native/ios/renderer/HippyUIManager.mm
- renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
> fix(ios): fix module provider not working and code refactor

- devtools/devtools-backend/CMakeLists.txt
- devtools/devtools-backend/include/tunnel/ws/web_socket_channel.h
- devtools/devtools-backend/src/module/domain/network_domain.cc
- framework/examples/ios-demo/podfile
- hippy.podspec
> fix(ios): solve some problems of podspec

- driver/js/packages/hippy-vue-next/__test__/runtime/element/hippy-element.test.ts
- driver/js/packages/hippy-vue-next/src/runtime/component/index.ts
> feat(vue-next): compatible vue2 component tag name format

- driver/js/examples/hippy-react-demo/src/pages/gallery.jsx
- driver/js/examples/hippy-vue-demo/src/pages/menu.vue
- driver/js/examples/hippy-vue-next-demo/src/pages/menu.vue
- driver/js/include/driver/performance/performance_navigation_timing.h
- driver/js/src/modules/performance/performance_navigation_timing_module.cc
- framework/android/connector/driver/js/src/main/cpp/include/connector/js_driver_jni.h
- framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
- framework/android/connector/driver/js/src/main/java/com/openhippy/connector/JsDriver.java
- framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
- framework/android/src/main/java/com/tencent/mtt/hippy/adapter/monitor/DefaultEngineMonitorAdapter.java
- framework/android/src/main/java/com/tencent/mtt/hippy/adapter/monitor/HippyEngineMonitorAdapter.java
- framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
- framework/android/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
- modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/TimeMonitor.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/HippyRootView.java
- renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
> feat(android): support fcp monitor

- framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineContext.java
- framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
- modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/common/BaseEngineContext.java
- renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
> feat(android): add BaseEngineContext interface

- renderer/native/ios/renderer/component/view/HippyView.h
- renderer/native/ios/renderer/component/view/HippyViewManager.mm
> fix(ios): fix timing issue of backgroundImage prop

- driver/js/src/napi/jsc/jsc_ctx.cc
- framework/ios/utils/NSObject+CtxValue.mm
- tests/ios/HippyOC2CtxValueTest.mm
> fix(ios): fix conversion crash from oc object to CtxValue

- driver/js/include/driver/performance/performance.h
- driver/js/src/js_driver_utils.cc
- driver/js/src/performance/performance.cc
- driver/js/src/scope.cc
- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/base/executors/HippyJSExecutor.mm
- renderer/native/ios/renderer/HippyComponent.h
- renderer/native/ios/renderer/component/view/HippyViewManager.mm
- renderer/native/ios/renderer/component/view/UIView+Hippy.h
- renderer/native/ios/renderer/component/view/UIView+Hippy.mm
- renderer/native/ios/renderer/component/view/UIView+MountEvent.h
- renderer/native/ios/renderer/component/view/UIView+MountEvent.m
- renderer/native/ios/utils/HippyConvert+NativeRender.h
- renderer/native/ios/utils/HippyConvert+NativeRender.m
- tests/ios/HippyUIViewCategoryTest.m
> feat(ios): add fcp monitor support

- docs/development/ios-3.0-upgrade-guidelines.md
- docs/development/native-adapter.md
- framework/ios/base/bridge/HippyBridge+Private.h
- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/module/imageloader/HippyImageLoaderModule.mm
- framework/ios/module/imageloader/HippyImageViewCustomLoader.h
- framework/ios/module/loader/HippyBase64DataHandler.h
- framework/ios/module/loader/HippyBase64DataHandler.mm
- framework/ios/module/loader/HippyBridge+VFSLoader.mm
- framework/ios/module/loader/HippyFileHandler.h
- framework/ios/module/loader/HippyFileHandler.mm
- framework/ios/module/turbo/HippyTurboModuleManager.h
- modules/vfs/ios/HippyVFSDefines.h
- modules/vfs/ios/VFSUriHandler.h
- modules/vfs/ios/VFSUriHandler.mm
- modules/vfs/ios/VFSUriLoader.h
- modules/vfs/ios/VFSUriLoader.mm
- renderer/native/ios/renderer/HippyUIManager+Private.h
- renderer/native/ios/renderer/HippyUIManager.h
- renderer/native/ios/renderer/HippyUIManager.mm
- renderer/native/ios/renderer/NativeRenderManager.mm
- renderer/native/ios/renderer/component/image/HippyImageViewManager.mm
- renderer/native/ios/renderer/component/view/HippyView.m
- renderer/native/ios/renderer/component/view/HippyViewManager.mm
> feat(ios): add custom image loader support

- framework/examples/android-demo/src/main/java/com/openhippy/example/PageConfiguration.kt
> fix(android): debugServerHost invalid setting

- driver/js/packages/hippy-vue-next/src/runtime/element/hippy-element.ts
- driver/js/packages/hippy-vue-next/src/runtime/node/hippy-node.ts
> feat(vue-next): add vue3 css style inherit

- ios/sdk/base/HippyTouchHandler.m
In a multi-finger scenario,
the _touchBeganView local variable only records the last touch view
since touch began is entered multiple times,
causing the began and cancel/end events to be unmatched.
To fix this, we use a simple approach -
that record all touch began Views and send events to all recorded views at the end.
Please note that we have not fully adapted the multi-fingered scenario.
> fix(ios): loss of touch end or cancel event in multi-finger scenarios

- driver/js/src/napi/jsc/jsc_ctx.cc
- framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.mm
- framework/examples/ios-demo/HippyDemo/TestModule.mm
- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/base/modules/HippyModuleMethod.mm
- framework/ios/module/imageloader/HippyImageLoaderModule.mm
- hippy.podspec
- modules/ios/base/HippyDefines.h
- modules/ios/base/HippyLog.mm
- modules/ios/base/HippyUtils.m
- modules/vfs/ios/VFSUriLoader.mm
- renderer/native/ios/renderer/HippyRootView.h
- renderer/native/ios/renderer/HippyRootView.mm
- renderer/native/ios/renderer/component/image/HippyImageViewManager.mm
- renderer/native/ios/renderer/component/view/HippyViewManager.mm
- tests/ios/HippyUtilsTest.m
> Sync some bug fixes and optimizations

- ios/sdk/component/viewPager/HippyViewPager.m
> feat(ios): pageIndex of ViewPager auto update after data changes

- renderer/native/ios/renderer/component/viewPager/HippyViewPager.mm
> feat(ios): update ViewPager's pageIndex automatically after data changes

- ios/sdk/base/HippyDeviceBaseInfo.m
- ios/sdk/component/image/HippyDefaultImageProvider.m
- ios/sdk/component/view/HippyBackgroundImageCacheManager.m
- ios/sdk/component/view/HippyShadowView.mm
- ios/sdk/component/view/HippyViewManager.mm
- ios/sdk/component/waterfalllist/HippyCollectionViewWaterfallLayout.m
- ios/sdk/layout/x5LayoutUtil.m
> fix(ios): potential deadlock in layout & unify all ScreenScale calls

- docs/development/android-3.0-upgrade-guidelines.md
- docs/feature/feature3.0/image-decoder-adapter.md
> refactor(docs): update 3.0 upgrade guidelines md

- examples/hippy-react-demo/src/components/TextInput/index.jsx
- examples/hippy-vue-demo/src/components/demos/demo-textarea.vue
- ios/sdk/component/textinput/HippyShadowTextView.h
- ios/sdk/component/textinput/HippyShadowTextView.mm
- ios/sdk/component/textinput/HippyTextField.h
- ios/sdk/component/textinput/HippyTextField.m
- ios/sdk/component/textinput/HippyTextView.h
- ios/sdk/component/textinput/HippyTextView.mm
- ios/sdk/component/textinput/HippyTextViewManager.mm
> feat(ios): add paragraph styles support for TextInput

- framework/ios/base/executors/HippyJSExecutor.mm
> fix(ios): potential thread race in HippyJSExecutor

- renderer/native/ios/renderer/component/view/HippyViewManager.mm
> chore(ios): add addFrameCallback method for devtools to avoid warning

- docs/development/ios-3.0-integration-guidelines.md
- docs/development/ios-3.0-upgrade-guidelines.md
> docs(ios): update integration and upgrade guildlines

- docs/development/ios-3.0-integration-guidelines.md
> chore(ios): update integration guide

- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/HippyRecyclerListAdapter.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/hippylist/recyclerview/helper/skikcy/StickyHeaderHelper.java
> fix(android): different sticky item position crash

- docs/api/hippy-react/components.md
- driver/js/examples/hippy-react-demo/src/components/TextInput/index.jsx
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInputController.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/TextInputRenderNode.java
> feat(android): text input support lineHeight

- ios/sdk/module/animation2/HippyNextAnimation.h
- ios/sdk/module/animation2/HippyNextAnimationGroup.m
- ios/sdk/module/animation2/HippyNextAnimationModule.m
- ios/sdk/module/animation2/pop/HPOPAnimator.h
- ios/sdk/module/animation2/pop/HPOPAnimator.mm
- ios/sdk/module/animation2/pop/HPOPAnimatorPrivate.h
> fix(ios): improve synchronization between animationSets

- ios/sdk/module/animation2/HippyNextAnimationModule.m
- ios/sdk/module/netinfo/HippyNetInfoIntenal.m
> fix(ios): delay of animationSet not working under new sync mechanism

- renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefresh.m
- renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefresh.m
- renderer/native/ios/renderer/component/refresh/HippyRefresh.h
- renderer/native/ios/renderer/component/refresh/HippyRefresh.m
> fix(ios): header and footer refresh bugs

- docs/api/style/appearance.md
- driver/js/examples/hippy-react-demo/src/components/Text/index.jsx
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/views/textinput/HippyTextInput.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/TextStyleSpan.java
- renderer/native/android/src/main/java/com/tencent/renderer/component/text/TypeFaceUtil.java
- renderer/native/android/src/main/java/com/tencent/renderer/node/TextVirtualNode.java
> fix(android): font weight compatible with version 2.x

- framework/android/src/main/java/com/tencent/mtt/hippy/modules/nativemodules/network/NetworkModule.java
- framework/ios/module/network/HippyNetWork.h
- framework/ios/module/network/HippyNetWork.mm
> feat(ios,android): add request duration in fetch response header

- framework/ios/module/loader/HippyFileHandler.h
- framework/ios/module/loader/HippyFileHandler.mm
- tests/ios/HippyFileHandlerTest.mm
> feat(ios): add app bundle and container path support for hpfile url

- ios/sdk/base/HippyFont.h
- ios/sdk/base/HippyFont.mm
- ios/sdk/base/HippyRootView.mm
- ios/sdk/component/textinput/HippyBaseTextInput.h
- ios/sdk/component/textinput/HippyBaseTextInput.m
- ios/sdk/component/textinput/HippyShadowTextView.h
- ios/sdk/component/textinput/HippyShadowTextView.mm
- ios/sdk/component/textinput/HippyTextViewManager.mm
- ios/sdk/module/uimanager/HippyUIManager.h
- ios/sdk/module/uimanager/HippyUIManager.mm
> feat(ios): add HippyFontChangeTriggerNotification for native font update

- core/src/napi/jsc/jsc_ctx.cc
- ios/sdk/module/turbo/HippyOCTurboModule.mm
> fix(ios): turbo module type convert nullptr crash

- driver/js/src/scope.cc
- framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
- framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm
- framework/ios/base/bridge/HippyBridge+Private.h
- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/base/executors/HippyJSExecutor.h
- framework/ios/base/executors/HippyJSExecutor.mm
> fix(ios, android): performance records inaccurate issues

- dom/src/dom/taitank_layout_node.cc
> fix(core): check crash on config SetScaleFactor

- driver/js/include/driver/scope.h
- driver/js/src/modules/timer_module.cc
- driver/js/src/napi/jsc/jsc_ctx.cc
- driver/js/src/scope.cc
- framework/ios/base/executors/HippyJSExecutor.mm
> fix(ios): add exception handle process for jsc

- modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/utils/TimeMonitor.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/HippyRootView.java
> fix(android): onGlobalLayout use root view size

- ios/sdk/component/viewPager/HippyViewPager.m
> fix(ios): improved accuracy of ViewPager's ScrollStateChanged API

- ios/sdk/component/viewPager/HippyViewPager.m
> fix(ios): improve accuracy of ViewPager's onPageScroll parameters

- driver/js/packages/hippy-vue-next/package.json
- driver/js/packages/hippy-vue-next/src/modules/attrs.ts
- driver/js/packages/hippy-vue-next/src/patch-prop.ts
> feat(vue-next): fix onInterceptTouchEvent not work

- examples/hippy-vue-next-demo/src/main-native.ts
- packages/hippy-vue-next-style-parser/src/style-match/css-map.ts
> feat(vue-next): fix beforeLoadStyle not work

- android/sdk/src/main/jni/src/bridge/java2js.cc
> fix(v8): add log for call function cpp buffer fail

- driver/js/include/driver/scope.h
- framework/examples/ios-demo/HippyDemo/RenderPage/HippyDemoViewController.m
- framework/ios/base/bridge/HippyBridge.mm
> refactor(ios): remove unused code in scope and update demo

- framework/ios/base/bridge/HippyBridge.mm
> fix(ios): null pointer exception of bridge setup in rare scenarios

- driver/js/include/driver/napi/jsc/jsc_try_catch.h
- driver/js/src/napi/jsc/jsc_try_catch.cc
- framework/ios/base/bridge/HippyBridge.mm
- modules/ios/base/HippyAssert.m
> fix(ios): resolve jsc_try_catch invalid issue

- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/module/loader/HippyFileHandler.mm
- modules/ios/base/HippyUtils.h
- modules/ios/base/HippyUtils.m
- renderer/native/ios/renderer/HippyRootView.mm
- tests/ios/HippyUtilsTest.m
> fix(ios): resolve sandbox dir issue in debug mode

- renderer/native/ios/renderer/HippyUIManager.mm
- renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
- renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
> fix(ios): onAttachedToWindow event not triggered

- framework/ios/base/modules/HippyModuleMethod.mm
> fix(ios): resolve compatibility issue when using ResponseSenderBlock

- framework/ios/utils/NSObject+CtxValue.h
- framework/ios/utils/NSObject+CtxValue.mm
- tests/ios/HippyCtxValueConvertTest.mm
> fix(ios): resolve boolean ctx value conversion issue

- framework/ios/utils/NSObject+CtxValue.mm
- tests/ios/HippyCtxValueConvertTest.mm
- tests/ios/HippyOC2CtxValueTest.mm
> fix(ios): type error when conversion of bool value to ctx value

- docs/development/android-3.0-upgrade-guidelines.md
- modules/android/hippy_support/src/main/java/com/tencent/mtt/hippy/annotation/HippyControllerProps.java
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/ControllerUpdateManger.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
> feat(android): compatible with custom event register

- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewDataSource.m
> fix(ios): banner view of waterfall not working

- docs/api/hippy-react/components.md
- docs/api/hippy-vue/components.md
- driver/js/examples/hippy-react-demo/src/externals/Slider/Slider.jsx
- renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm
> docs(react,vue): update docs of pointerEvents prop

- framework/ios/base/executors/HippyJSExecutor.mm
- renderer/native/ios/renderer/HippyUIManager.mm
> fix(ios): add nullptr exception protection in rare scenarios

- ios/sdk/base/HippyComponentData.mm
> chore(ios): add Invalid prop keyPath check

- driver/js/examples/hippy-react-demo/src/components/ListView/index.jsx
- driver/js/examples/hippy-vue-demo/src/components/demos/demo-list.vue
- driver/js/examples/hippy-vue-next-demo/src/components/demo/demo-list.vue
- framework/ios/base/bridge/HippyBridge.mm
- modules/footstone/include/footstone/logging.h
> fix(ios): thread race of bundle load op in very small scenarios

- renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
- renderer/native/ios/renderer/component/listview/HippyNextBaseListViewDataSource.m
- renderer/native/ios/renderer/component/listview/HippyNextShadowListItem.h
- renderer/native/ios/renderer/component/listview/HippyNextShadowListItem.m
> feat(ios): add keep-alive setting prop to list item (experimental)

- driver/js/examples/hippy-react-demo/scripts/hippy-webpack.web-renderer.dev.js
- driver/js/examples/hippy-react-demo/src/modules/Animation/index.jsx
- driver/js/packages/hippy-web-renderer/src/component/list-view.ts
> fix(web): fix webrender listview item relayout

- driver/js/packages/hippy-web-renderer/src/third-lib/size-position-manager.js
- driver/js/packages/hippy-web-renderer/src/third-lib/virtual-list.js
> fix(web): fix webrender not show when length is 1

- dom/include/dom/dom_manager.h
- dom/src/dom/dom_manager.cc
- dom/src/dom/root_node.cc
- dom/src/dom/scene_builder.cc
- framework/android/connector/driver/js/src/main/cpp/include/connector/js_driver_jni.h
- framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
- framework/android/connector/driver/js/src/main/java/com/openhippy/connector/JsDriver.java
- framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
- framework/ios/base/bridge/HippyBridge+PerformanceAPI.h
- framework/ios/base/bridge/HippyBridge+PerformanceAPI.mm
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/HippyRootView.java
- renderer/native/android/src/main/java/com/tencent/renderer/FrameworkProxy.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRender.java
- renderer/native/android/src/main/java/com/tencent/renderer/NativeRenderer.java
- renderer/native/ios/renderer/HippyRootView.mm
> fix(android,ios): performance record inaccurate when engine reuse

- docs/api/hippy-react/components.md
- docs/api/hippy-vue/external-components.md
- driver/js/examples/hippy-react-demo/src/components/WaterfallView/index.jsx
- driver/js/examples/hippy-vue-demo/src/components/native-demos/demo-waterfall.vue
- driver/js/examples/hippy-vue-next-demo/src/components/native-demo/demo-waterfall.vue
- driver/js/packages/hippy-react/src/components/waterfall-view.tsx
- renderer/native/ios/renderer/component/waterfalllist/HippyShadowWaterfallItem.h
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallItemViewManager.m
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.h
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewDataSource.h
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewDataSource.m
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.m
> feat(ios): waterfall component support footer view

- framework/ios/base/bridge/HippyBridge.h
- framework/ios/base/bridge/HippyBridge.mm
- modules/vfs/ios/HippyFileHandler.h
- modules/vfs/ios/HippyFileHandler.mm
- tests/ios/HippyFileHandlerTest.mm
> fix(ios): potential thread race in vfs file module

- renderer/native/ios/renderer/component/footerrefresh/HippyFooterRefresh.m
- renderer/native/ios/renderer/component/headerrefresh/HippyHeaderRefresh.m
- renderer/native/ios/renderer/component/refresh/HippyRefresh.h
- renderer/native/ios/renderer/component/refresh/HippyRefresh.m
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm
> fix(ios): abnormal onFooterPulling callback

- docs/api/_sidebar.md
- docs/api/feedback.md
- docs/api/hippy-react/_sidebar.md
- docs/api/hippy-react/customize.md
- docs/api/hippy-react/feedback.md
- docs/api/hippy-react/modules.md
- docs/api/hippy-vue/_sidebar.md
- docs/api/hippy-vue/customize.md
- docs/api/hippy-vue/feedback.md
- docs/api/hippy-vue/vue-native.md
- docs/api/hippy-vue/web.md
- docs/api/performance.md
- docs/api/style/_sidebar.md
- docs/api/style/feedback.md
- docs/development/native-component.md
- docs/development/report.md
> chore(doc): add react vue performance doc

- docs/development/_sidebar.md
- docs/development/native-module.md
- docs/development/v8-api.md
> fix(doc): update android v8 and module document

- renderer/native/ios/renderer/HippyUIManager.h
- renderer/native/ios/renderer/HippyUIManager.mm
- renderer/native/ios/renderer/component/view/UIView+MountEvent.m
> fix(ios): fcp record of performance api may not working

- devtools/devtools-backend/src/module/domain/dom_domain.cc
- devtools/devtools-integration/native/include/devtools/devtools_utils.h
- devtools/devtools-integration/native/src/devtools_utils.cc
- renderer/native/android/src/main/java/com/tencent/mtt/hippy/utils/DevtoolsUtil.java
- renderer/native/ios/renderer/component/view/HippyViewManager.mm
> fix(devtools): fix the mapping between DOM tree and UI inspector

- framework/ios/base/bridge/HippyBridge.mm
- framework/ios/base/executors/HippyJSEnginesMapper.mm
- renderer/native/ios/renderer/HippyUIManager.h
- renderer/native/ios/renderer/HippyUIManager.mm
> fix(ios): data race issues when bridge and engine dealloc

- driver/js/examples/hippy-react-demo/src/modules/Animation/index.jsx
- framework/ios/base/bridge/HippyBridge.mm
- modules/ios/domutils/HippyDomUtils.h
- modules/ios/domutils/HippyDomUtils.mm
- modules/ios/footstoneutils/HippyFootstoneUtils.mm
- renderer/native/ios/renderer/HippyUIManager.mm
- renderer/native/ios/utils/HippyConvert+NativeRender.m
add protect when handling buffer
> refactor(ios): update transform converter and animation demo

- devtools/devtools-backend/include/api/devtools_backend_service.h
- devtools/devtools-backend/include/tunnel/net_channel.h
- devtools/devtools-backend/include/tunnel/tcp/tcp_channel.h
- devtools/devtools-backend/include/tunnel/tunnel_service.h
- devtools/devtools-backend/include/tunnel/ws/web_socket_channel.h
- devtools/devtools-backend/src/api/devtools_backend_service.cc
- devtools/devtools-backend/src/tunnel/tcp/tcp_channel.cc
- devtools/devtools-backend/src/tunnel/tunnel_service.cc
- devtools/devtools-backend/src/tunnel/ws/web_socket_channel.cc
- devtools/devtools-integration/android/src/main/cpp/src/devtools_jni.cc
- devtools/devtools-integration/native/include/devtools/devtools_data_source.h
- devtools/devtools-integration/native/src/devtools_data_source.cc
- framework/ios/base/executors/HippyJSExecutor.mm
> fix(devtools): add reconnect when websocket closed by server

- examples/ios-demo/HippyDemo/TestModule.m
- examples/ios-demo/HippyDemo/ViewController.m
> chore(ios): update hippy demo, adapt to hippy3

- framework/ios/base/bridge/HippyBridge+BundleLoad.mm
- framework/ios/module/imageloader/HippyImageLoaderModule.mm
- framework/ios/module/network/HippyNetWork.mm
- modules/vfs/ios/HippyBridge+VFSLoader.h
- modules/vfs/ios/HippyBridge+VFSLoader.mm
> refactor(ios): refactor hippyBridge's vfs category methods

- driver/js/packages/hippy-vue-css-loader/src/css-parser.ts
- driver/js/packages/hippy-vue-next-style-parser/src/style-parser/css-parser.ts
> feat(vue): not filter rpx when parse style

- docs/api/hippy-react/components.md
- docs/api/hippy-vue/components.md
- renderer/native/ios/renderer/component/listview/HippyNextBaseListViewManager.m
- renderer/native/ios/renderer/component/listview/HippyNextListTableView.h
- renderer/native/ios/renderer/component/listview/HippyNextListTableView.m
- renderer/native/ios/renderer/component/scrollview/HippyNestedScrollCoordinator.h
- renderer/native/ios/renderer/component/scrollview/HippyNestedScrollCoordinator.m
- renderer/native/ios/renderer/component/scrollview/HippyNestedScrollProtocol.h
- renderer/native/ios/renderer/component/scrollview/HippyScrollView.h
- renderer/native/ios/renderer/component/scrollview/HippyScrollView.mm
- renderer/native/ios/renderer/component/scrollview/HippyScrollViewManager.mm
- renderer/native/ios/renderer/component/scrollview/HippyScrollableProtocol.h
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallView.mm
- renderer/native/ios/renderer/component/waterfalllist/HippyWaterfallViewManager.m
- renderer/native/ios/utils/HippyConvert+NativeRender.h
- renderer/native/ios/utils/HippyConvert+NativeRender.m
- tests/ios/HippyNestedScrollTest.m
> feat(ios): nested scroll api support

- driver/js/src/scope.cc
- framework/ios/base/executors/HippyJSExecutor.mm
> fix(jsc): fix jsc memery release

- renderer/native/ios/renderer/NativeRenderManager.mm
> fix(ios): avoid deadlock in native render manager

- driver/js/src/napi/jsc/jsc_ctx.cc
- framework/ios/utils/NSObject+CtxValue.mm
> fix(ios): optimize variable array usage in convertToCtxValue and jscctx

- .github/CODEOWNERS
> fix(core): fix code owner file

- framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
- framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
> fix(core): fix android scope null when init engine exception

- renderer/native/ios/renderer/component/listview/HippyNextBaseListView.mm
> fix(ios): listview endReached not working when preloadItemNumber is 0

- ios/sdk/base/executors/HippyJSCExecutor.mm
- ios/sdk/module/animation2/HippyNextAnimationModule.m
> fix(ios): resolve animation thread race & add protection for running script

- docs/api/hippy-react/components.md
- docs/api/hippy-vue/components.md
- framework/examples/ios-demo/HippyDemo/HippyDemoViewController.m
- xcodeinitscript.sh
> chore(ios): update demo and docs

- dom/include/dom/root_node.h
- dom/src/dom/animation/animation_manager.cc
- dom/src/dom/root_node.cc
- driver/js/src/modules/animation_frame_module.cc
> fix(core): vsync event used by frame is stopped by animation ending
